<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.1
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is: vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(

	// Footer
	'APPTITLE' => 'vtiger CRM',
	'POWEREDBY'=> 'Βασισμένο  vtiger CRM',
	'LBL_READ_LICENSE' => 'Άδεια Χρήσης',
	'LBL_PRIVACY_POLICY' => 'Πολιτική Απορρήτου',

	// Common Actions
	'LBL_NEW' => 'Νέο',
	'LBL_LINKED' => 'Συνδεδεμένο',
	'LBL_SELECT_ALL' => 'Επιλογή όλων',
	'LBL_SELECT_TO_LOAD_LIST' => 'Επιλέξτε φόρτωμα Λίστας',
	'LBL_CREATING_NEW' => 'Δημιουργία Νέας',
	'LBL_ADDING_NEW' => 'Προσθήκη νέας',
	'LBL_EDITING' => 'Επεξεργασία',
	'LBL_SAVE' => 'Αποθήκευση',
	'LBL_CANCEL' => 'Ακύρωση',
	'LBL_BACK' => 'Πίσω',
	'LBL_IMPORT' => 'Εισαγωγή',
	'LBL_EXPORT' => 'Εξαγωγή',
	'LBL_FIND_DUPLICATES' => 'Βρείτε διπλότυπα',
	'LBL_MORE' => 'Περισσότερα',
	'LBL_LESS' => 'Λιγότερα',
	'LBL_ACTIONS' => 'Ενέργειες',
	'LBL_ADD' => 'Προσθήκη',
	'LBL_EDIT' => 'Επεξεργασία',
	'LBL_DELETE' => 'Διαγραφή',
	'LBL_COMMENT' => 'Σχόλια',
	'LBL_STARRED' => 'Μην ακολουθείτε',
	'LBL_NOT_STARRED' => 'Κλικ για να ακολουθήσετε',
	'LBL_QUICK_VIEW' => 'Σύντομη Προβολή',
	'LBL_NOTIFICATION_CENTER' => 'Κέντρο ειδοποιήσεων',
	'LBL_NOTIFICATION' => 'Ειδοποίηση',
	'LBL_STARRED_RECORD_TO' => '%s έως %s',
	'LBL_STARRED_RECORD_UPDATED' => '%s επικαιροποίηση %s',
	'LBL_SETTINGS'=> 'Ρυθμίσεις',
	'LBL_ADD_COMMENT' => 'Αφήστε Σχόλιο',
	'LBL_EDIT_FIELDS' => '%s Πεδία & Διάταξη',
	'LBL_EDIT_WORKFLOWS' => '%s Ροές εργασίας',
	'LBL_EDIT_PICKLIST_VALUES' => 'Τιμές Λίστας επιλογών',
	'LBL_EDIT_MAILSCANNER' => 'Μετατροπέας Mail',
	'LBL_RECORD_DELETE' => 'Η εγγραφή που προσπαθείτε να προβάλετε έχει διαγραφεί.',
	'LBL_RECORD_NOT_FOUND' => 'Η εγγραφή στην οποία προσπαθείτε να προσπελάσετε δεν βρέθηκε',
	'LBL_EDIT_REASON' => 'Αιτία επεξεργασίας',
	//'LBL_EDIT_CURRENT_FILTER' => 'Επεξεργασία Τρέχον φίλτρου',
	//'LBL_DELETE_CURRENT_FILTER' => 'Διαγραφή Τρέχον φίλτρου',
	'LBL_SELECT' => 'Επιλέξτε',
	'LBL_CLEAR' => 'Καθαρισμός',
	'LBL_YES' => 'Ναι',
	'LBL_NO' => 'Όχι',
	'LBL_SHOW_COMPLETE_DETAILS' => 'Πλήρης Λεπτομέρειες',
	'LBL_MINILIST_FIELDS_ARE_NOT_AVAILABLE_FOR_YOU' => 'Συγνώμη! Δεν είναι διαθέσιμα τα πεδία minilist για εσάς.',
	'LBL_MASS_EDITING' => 'Μαζική Επεξεργασία',
	'LBL_DESELECT_ALL_RECORDS' => 'Αποεπιλογή όλων των εγγραφών σε όλες τις σελίδες',
	'LBL_QUICK_CREATE' => 'Γρήγορη δημιουργία',
	'LBL_QUICK_EDIT' => 'Γρήγορη Επεξεργασία',
	'LBL_SEND_EMAIL' => 'Αποστολή Email',
	//SEND EMAIL translations
	'LBL_ALL_EMAILS' => 'All email accounts',
	'LBL_MUTIPLE_EMAIL_SELECT_ONE' => 'Διαλέξτε μία από τις παρακάτω επιλογές',
	//SEND EMAIL translations
	'LBL_GO_TO_FULL_FORM' => 'Μετάβαση σε πλήρης φόρμα',
	'LBL_SEND_SMS' => 'Αποστολή SMS',
	'LBL_FOUND' => 'βρέθηκε',
	'LBL_CLICK_ADD' => 'Κλικ για Προσθήκη',
	'LBL_ADD_MORE_FIELDS' => 'Προσθέστε περισσότερα πεδία',
	'LBL_ADD_NOTE' => 'Προσθήκη Αρχείο',
	'LBL_CREATE_NEW' => 'Δημιουργία Νέου',
	'LBL_ADD_EVENT' => 'Προσθήκη Συμβάντος',
	'LBL_ADD_TASK' => 'Προσθήκη εργασίας',
	'LBL_MARKETING_AND_SALES' => 'MARKETING & ΠΩΛΗΣΕΙΣ',
	'LBL_TOOLS_HEADER' => 'ΕΡΓΑΛΕΊΑ',
	'LBL_SUPPORT' => 'ΥΠΟΣΤΗΡΙΞΗ',
	'LBL_INVENTORY' => 'ΑΠΟΘΗΚΗ',
	'LBL_ANALYTICS' => 'ΣΤΑΤΙΣΤΙΚΑ',
	'LBL_CONTACT' => 'ΔΙΑΧΕΙΡΙΣΗ ΕΠΙΚΟΙΝΩΝΙΑΣ',
	'LBL_HOME' => 'Αρχική',
	'LBL_NO_ATTACHMENTS' => 'Δεν υπάρχουν συνημμένα',
	'LBL_COMPOSE_EMAIL_WARNING' => ' Warning : Your email might land in spam. Add Vtiger as an authorized sender for your domain. Learn more',
	// Common Link Labels
	'LBL_REARRANGE_DASHBOARD_TABS' => 'Αναδιάταξη καρτελών',
	'LBL_DONE' => 'Εγινε',
	'LBL_DELETE_DASHBOARD_TAB' =>'Διαγραφή καρτέλας',
	'LBL_DASHBOARD_TAB_ALREADY_EXIST' => 'Το όνομα της καρτέλας υπάρχει ήδη',
	'LBL_TABS_LIMIT_EXCEEDED' => 'Συγνώμη! Δεν είναι δυνατή η προσθήκη περισσότερων από 10 καρτελών',
	'LBL_TODOS' => 'Εργασίες',
	'LBL_LAST_VIEWED_RECORDS' => 'Τελευταίες προβεβλημένες εγγραφές',
	'LBL_DASHBOARD' => 'Πίνακας ελέγχου',
	'LBL_USER_SETTINGS' => 'Ρυθμίσεις Χρήστη',
	'LBL_MY_PREFERENCES' => 'Οι Προτιμήσεις Μου',
	'LBL_SIGN_OUT' => 'Αποσύνδεση',
	'LBL_HELP' => 'Βοήθεια',
	'LBL_DOCUMENTATION' => 'Τεκμηρίωση',
	'LBL_VIDEO_TUTORIAL' => 'Οδηγός χρήσης σε Βίντεο',
	'LBL_FEEDBACK' => 'Παρατηρήσεις',
	'LBL_CHAT_SUPPORT'=>'Chat με την Υποστήριξη',
	'LBL_CRM_SETTINGS' => 'Ρυθμίσεις CRM',
	'LBL_ON_DEMAND_ADMIN' => 'Προσθήκη/Διαγραφή χρηστών',
	'LBL_ANNOUNCEMENT' => 'Ανακοίνωση',
	'LBL_CALENDAR' => 'Ημερολόγιο',
	'LBL_POST' => 'Δημοσίευση',
	'LBL_GUIDER' => 'Οδηγός',
	'LBL_VIDEOS' => 'Βίντεο',
	'LBL_DISPLAY_TYPE' => 'Τύπος Προβολής',
	'LBL_DISPLAY_WIDETYPE' => 'Ευρεία',
	'LBL_DISPLAY_MEDIUMTYPE' => 'Μεσαία',
	'LBL_DISPLAY_NARROWTYPE' => 'Στενής',
	'LBL_TAG_THIS_RECORD' => 'Ετικέτα την εγγραφή',
	'LBL_SAME_TAG_EXISTS' => 'Υπάρχει διπλότυπη ετικέτα',
	'LBL_MAKE_PUBLIC' => 'Κάντε το Δημόσιο',
	'LBL_PAGE' => 'Σελίδα',
	'LBL_LISTVIEW_PAGE_JUMP' => 'Προσπεράστε σελίδα',
	'LBL_LISTVIEW_JUMP_TO' => 'Προσπεράστε στην',
	'LBL_PROFILE_PASSWORD' => 'Προφίλ / Συνθηματικό',
	'LBL_INFO' => 'Πληροφορίες',
	'LBL_CANT_MOVE_FROM_PUBLIC_TO_PRIVATE' => 'Δεν είναι δυνατή η μετάβαση από την Δημόσια ετικέτα στην Ιδιωτική ετικέτα.',
	'LBL_EDIT_TAG'=>'Επεξεργασία Ετικέτας',
	'LBL_NO_TAG_EXISTS' => 'Δεν υπάρχει ετικέτα' ,
	'LBL_RELATED_USERS' => 'Σχετιζόμενοι χρήστες',

	// Common Fields
	'LBL_USER' => 'Χρήστης',
	'LBL_GROUP' => 'Ομάδα',
	'Last Modified By' => 'Τελευταία τροποποίηση από',
	'Created Time' => 'Δημιουργήθηκε στις',
	'Modified Time' => 'Τροποποιήθηκε στις',
	'Description' => 'Περιγραφή',
	'Assigned To'=>'Ανατέθηκε σε/στον',

	//Loading Labels
	'LBL_LOADING' => 'Φόρτωση',
	'LBL_LOADING_WIDGET' => 'Φόρτωση Widget',
	'LBL_LOADING_LISTVIEW_CONTENTS'	=> 'Γίνετε Φόρτωση παρακαλώ περιμένετε',

	// Detail View
	'LBL_HISTORY' => 'Ιστορικό',
	'LBL_UPDATES' => 'Ενημερώσεις',
	'LBL_SHOW_FULL_DETAILS' => 'Εμφάνιση πλήρων λεπτομερειών',
	'LBL_SUMMARY_DETAILS' => 'Περιληπτικά Στοιχεία',
	'LBL_ADD_NEW_COMMENT' =>'Προσθήκη Νέου Σχόλιου',
	'LBL_NO_UPDATES' => 'Καμμία Ενημέρωση',
	'LBL_ACTIVITIES' => 'Δραστηριότητες',
	'LBL_NO_PENDING_ACTIVITIES' => 'Καμμία εκκρεμής δραστηριότητα',
	'LBL_SUMMARY' => 'Περίληψη',
	'LBL_KEY_FIELD' => 'Βασικό πεδίο',
	'LBL_DETAILS' => 'Λεπτομέρειες',
	'LBL_NAME_EMAIL' => 'Όνομα και Email',

	// Popup window
	'LBL_SEARCH_FOR' => 'Αναζήτηση για',
	'LBL_IN' => 'σε',
	'LBL_TYPE_SEARCH' => 'Πληκτρολογήστε για Αναζήτηση',
	'LBL_SEARCH_BUTTON' => 'Κουμπί Αναζήτησης',
	'LBL_ADVANCE_SEARCH' => 'Σύνθετη',
	'LBL_LOADING_PLEASE_WAIT' => 'Φορτώνει...Παρακαλώ περιμένετε',
	'LBL_PLEASE_SELECT_MODULE' => 'Παρακαλώ επιλέξτε οποιαδήποτε ενότητα για αναζήτηση',

	//DropDown Category
	'LBL_USERS' => 'Χρήστες',
	'LBL_GROUPS' => 'Ομάδες',

	//EditView Form Links
	'LBL_FULL_FORM' => 'Πλήρης Φόρμα',
	'LBL_SIMPLE_FORM' => 'Απλή Φόρμα',

	//Recent Comments
	'LBL_IS_REMOVED' => 'έχει αφαιρεθεί',
	'LBL_ADD_YOUR_COMMENT_HERE' => 'Αφήστε το Σχόλιο σας εδώ....',
	'LBL_REASON_FOR_CHANGING_COMMENT' => 'Αιτία τροποποίησης σχόλιου',
	'LBL_REPLY' => 'Απάντηση',
	'LBL_VIEW_THREAD' => 'Δείτε την συζήτηση',
	'LBL_NO_COMMENTS' => 'Κανένα Σχόλιο',
	'LBL_REPLIES' => 'απαντήσεις',
	'LBL_REPLY_ALL' => 'Απάντηση σε όλα',

	//Translation for all modules
	'Accounts' => 'Οργανισμοί',
	'Assets' => 'Περιουσιακά Στοιχεία',
	'Calendar' => 'Ημερολόγιο',
	'Campaigns' => 'Καμπάνιες',
	'Contacts' => 'Επαφές',
	'Documents' => 'Αρχεία',
	'Leads' => 'Δυνητικοί',
	'ModComments' => 'Σχόλια',
	'Potentials' => 'Ευκαιρίες',
	'PriceBooks' => 'Τιμοκατάλογοι',
	'Products' => 'Προιόντα',
	'Project' => 'Έργα',
	'ProjectMilestone' => 'Ορόσημα του Έργου',
	'ProjectTask' => 'Εργασίες του Έργου',
	'ServiceContracts' => 'Συμβόλαια Υπηρεσιών',
	'Services' => 'Υπηρεσίες',
	'Vendors' => 'Προμηθευτές',
	'Rss' => 'RSS',
	'Quotes'=>'Προσφορές',
	'PurchaseOrder'=>'Εντολή Αγοράς',
	'SalesOrder'=>'Εντολή Πώλησης',
	'Invoice'=>'Τιμολόγιο',
	'MailManager' => 'Διαχειριστής Mail',
	'Activities' => 'Δραστηριότητες',
	'Portal' => 'Ιστοσελίδες μας',
	'Email Templates' => 'Πρότυπα Email',
	'Recycle Bin' => 'Κάδος ανακύκλωσης',

	//Basic String Translation
	'LBL_ADD_RECORD' => 'Προσθήκη Εγγραφής',
	'LBL_RECENTLY_MODIFIED' => 'Πρόσφατη Τροποποίηση',
	'LBL_RECORDS_LIST' => 'Λίστα Εγγραφών',
	'LBL_RECORD_SUMMARY' => 'Σύνοψη Ενότητας',
	'LBL_RECORD_SUMMARY' => 'Λεπτομέριες Ενότητας',
	'LBL_ACCESS_DENIED_FOR' => 'Η Πρόσβαση απαγορεύται για',
	'LBL_GO_BACK' => 'Πίσω',
	'LBL_NO_DATA_AVAILABLE' => 'Δεν υπάρχουν διαθέσιμα δεδομένα',

	// Global Search
	'LBL_GLOBAL_SEARCH' => 'Πληκτρολογήστε μία λέξη και πατήστε enter',
	'LBL_ALL_RECORDS' => 'Όλες οι εγγραφές',
	'LBL_NO_RECORDS_FOUND' => 'Δεν Βρέθηκε καμμία εγγραφή',

	//Filters & Advance Filter
	'LBL_AND' => 'και',
	'LBL_OR' => 'ή',
	'LBL_APPLBL_NONEROVE' => 'Εγκριση',
	'LBL_DENY' => 'Άρνηση',
	'LBL_EQUALS' => 'ίσο με',
	'LBL_NOT_EQUAL_TO' => 'δεν είναι ίσο με',
	'LBL_STARTS_WITH' => 'ξεκινάει με',
	'LBL_ENDS_WITH' => 'τελειώνει με',
	'LBL_CONTAINS' => 'περιέχει',
	'LBL_DOES_NOT_CONTAIN' => 'δεν περιέχει',
	'LBL_LESS_THAN' => 'μικρότερο από',
	'LBL_GREATER_THAN' => 'μεγαλύτερο από',
	'LBL_LESS_THAN_OR_EQUAL' => 'μικρότερο ή ίσο',
	'LBL_GREATER_OR_EQUAL' => 'μεγαλύτερο ή ίσο',
	'LBL_BEFORE' => 'πρίν',
	'LBL_AFTER' => 'μετά',
	'LBL_BETWEEN' => 'μεταξύ',
	'LBL_SEARCH' => 'Αναζήτηση',
	'LBL_SEARCH_IN' => 'Αναζήτηση σε',
	'LBL_ADD_CONDITION' => 'Προσθήκη Συνθήκης',
	'LBL_ADD_GROUP' => 'Προσθήκη ομάδας κατάστασης',
	'LBL_FILTER_CONDITIONS' => 'Συνθήκες φίλτρων',
	'LBL_ALL_CONDITIONS' => 'Όλες οι συνθήκες',
	'LBL_ALL_CONDITIONS_DESC' => 'Όλες οι συνθήκες πρέπει να ικανοποιούνται',
	'LBL_ANY_CONDITIONS' => 'Οποιαδήποτε συνθήκη',
	'LBL_ANY_CONDITIONS_DESC' => 'Τουλάχιστον μία συνθήκη πρέπει να ικανοποιείται',
	'LBL_SELECT_FIELD' => 'Επιλέξτε Πεδίο',
	'LBL_SELECT_MODULE' => 'Επιλογή Ενότητας',
	'LBL_CREATE_NEW_FILTER' => 'Δημιουργία Νέου Φίλτρου',
	'All' => 'Όλα',
	'Others' => 'Λοιπά',
	'Pending' => 'Εκκρεμούν',
	'Public' => 'Δημόσια',

	//Advance Search
	'LBL_SAVE_FILTER' => 'Αποθήκευση Φίλτρου',
	'LBL_SAVE_MODIFY_FILTER' => 'Αποθήκευση/Τροποποίηση Αναζήτησης',
	'LBL_SEARCH_RESULTS' => 'Αποτελέσματα Αναζήτησης',
	'LBL_SAVE_AS_FILTER' => 'Αποθήκευση ως Φίλτρο',

	//Exception String Translation
	'LBL_NOT_ACCESSIBLE' => 'Άρνηση Πρόσβασης',

	//Line Items
	'LBL_ITEM_DETAILS'=> 'Λεπτομέρειες Αντικειμένου',
	'LBL_CURRENCY' => 'Ισοτιμία',
	'LBL_TAX_MODE' => 'Φορολογική λειτουργία',
	'LBL_INDIVIDUAL' => 'Ατομικό',
	'LBL_GROUP' => 'Ομάδα',
	'LBL_TOOLS' => 'Εργαλεία',
	'LBL_ITEM_NAME' => 'Όνομα Αντικειμένου',
	'LBL_QTY_IN_STOCK' => 'Απόθεμα',
	'LBL_QTY' => 'Ποσότητα',
	'LBL_LIST_PRICE' => 'Τιμή Πώλησης',
	'LBL_TOTAL' => 'Σύνολο',
	'LBL_NET_PRICE' => 'Καθαρή Αξία',
	'LBL_DISCOUNT' => 'Έκπτωση',
	'LBL_TOTAL_AFTER_DISCOUNT' => 'Σύνολο Μετά τήν Έκπτωση',
	'LBL_TAX' => 'Φόρος',
	'LBL_ADD_PRODUCT' => 'Προσθήκη προϊόντος',
	'LBL_ADD_SERVICE' => 'Προσθήκη Υπηρεσίας',
	'LBL_LI_ADD_PRODUCT' => 'Προϊόν',
	'LBL_LI_ADD_SERVICE' => 'Υπηρεσία',
	'LBL_ITEMS_TOTAL' => 'Σύνολο Αντικειμένων',
	'LBL_SHIPPING_AND_HANDLING_CHARGES' => 'Έξοδα αποστολής και μεταφοράς',
	'LBL_PRE_TAX_TOTAL' => 'Σύνολο προ Φόρου',
	'LBL_TAX_FOR_SHIPPING_AND_HANDLING' => 'Φόρος αποστολής και μεταφοράς',
	'LBL_SET_SHIPPING_AND_HANDLING_TAXES_FOR' => 'Ορίστε ΦΠΑ για Αποστολή και Μεταφορά',
	'LBL_ADJUSTMENT' => 'Προσαρμογή',
	'LBL_DEDUCT' => 'Αφαίρεση',
	'LBL_GRAND_TOTAL' => 'Σύνολο',
	'LBL_ZERO_DISCOUNT' => 'Μηδενική Έκπτωση',
	'LBL_OF_PRICE' => 'Τιμή',
	'LBL_DIRECT_PRICE_REDUCTION' => 'Απευθείας Μείωση Τιμής',
	'LBL_SET_DISCOUNT_FOR' => 'Ορίστε Έκπτωση για',
	'LBL_STOCK_NOT_ENOUGH' => 'Μη Επαρκές Απόθεμα',
	'LBL_MAX_QTY_SELECT' => 'Η Μέγιστη Τιμή είναι',
	'LBL_DRAG' => 'Σύρτε',
	'LBL_TOTAL_TAX_AMOUNT' => 'Συνολικό ποσό Φόρου',
	'LBL_DIRECT_AMOUNT_DISCOUNT' => 'Έκπτωση άμεσου ποσού',
	'LBL_FINAL_DISCOUNT_AMOUNT' => 'Τελικό Ποσό Έκπτωσης',
	'LBL_MORE_CURRENCIES' => 'Περισσότερες Ισοτιμίες',
	'LBL_SET_TAX_FOR' => 'Ορισμός Φόρου Για',
	'LBL_GROUP_TAX' => 'Φόρος Ομίλου',
	'LBL_BILLING_ADDRESS_FROM' => 'Αντιγραφή Διεύθυνσης Πληρωμής από',
	'LBL_SHIPPING_ADDRESS_FROM' => 'Αντιγραφή Διεύθυνσης Αποστολής από',
	'LBL_COPY_SHIPPING_ADDRESS' => 'Διεύθυνση Αποστολής',
	'LBL_COPY_BILLING_ADDRESS' => 'Διεύθυνση Χρέωσης',
	'LBL_OVERALL_DISCOUNT' => 'Συνολική έκπτωση',
	'LBL_CHARGES' => 'Χρεώσεις',
	'LBL_CHARGES_TOTAL' => 'Συνολικές χρεώσεις',
	'LBL_TAXES_ON_CHARGES' => 'Φόροι επί των χρεώσεων',
	'LBL_DEDUCTED_TAXES' => 'Αφαίρεση Φόρων',
	'LBL_DEDUCTED_TAXES_TOTAL' => 'Αφαίρεση Φόρων - Σύνολο',
	'LBL_DEFAULT' => 'Προκαθορισμένο',
	'LBL_ITEM' => 'Αντικείμενο',
	'LBL_ADD_DASHBOARD' =>'Προσθήκη Πίνακα',

	//DetailView Actions
	'LBL_CREATE' => 'Δημιουργία',
	'LBL_GENERATE' => 'Παραγωγή',
	'LBL_DUPLICATE' => 'Διπλότυπο',
	'Add Note' => 'Προσθήκη Αρχείου',

	//Dashboard String
	'LBL_ADD_WIDGET' => 'Προσθήκη Widget',
	'LBL_COMMENTS' => 'Σχόλια',
	'LBL_REFRESH' => 'Ανανέωση',
	'LBL_CLOSE' => 'Κλείσιμο',
	'LBL_ALL' => 'Όλα',
	'LBL_UPDATED' => 'ενημερωμένα',
	'LBL_VIA_TASK' => 'μέσω εργασίας',
	'LBL_form' => 'από',
	'LBL_FROM' => 'Από',
	'LBL_TO' => 'Πρός',
	'LBL_to' => 'πρός',
	'LBL_ON' => 'στις',
	'LBL_OF' => 'του',
	'LBL_BY' => 'απο',
	'LBL_ADDED' => 'προστέθηκε',
	'LBL_FOR' => 'για',
	'LBL_CREATED' => 'δημιουργήθηκε',
	'LBL_DELETED' => 'διαγράφτηκε',
	'LBL_RESTORED' => 'επαναφέρθηκε',
	'LBL_COMMENTED' => 'σχολιάστηκε',
	'LBL_REMOVED' => 'αφαιρέθηκε',
	'LBL_REMOVE' => 'αφαίρεση',
	'LBL_AT' => 'στις',
	'LBL_MINE' => 'Δικό Μου',
	'LBL_ME' => 'Εγώ',
	'History' => 'Ιστορικό',
	'Upcoming Tasks' => 'Επερχόμενες Εργασίες',
	'LBL_YEAR' => 'έτος',
	'LBL_YEARS' => 'έτοι',
	'LBL_MONTH' => 'μήνας',
	'LBL_MONTHS' => 'μήνες',
	'LBL_DAY' => 'ημέρα',
	'LBL_DAYS' => 'ημέρες',
	'LBL_DAY(S)' => 'ημέρα(ες)',
	'LBL_HOUR' => 'ώρα',
	'LBL_HOURS' => 'ώρες',
	'LBL_HOUR(S)' => 'ώρα(ες)',
	'LBL_MINUTE' => 'λεπτό',
	'LBL_MINUTES' => 'λεπτά',
	'LBL_SECOND' => 'δευτερόλεπτο',
	'LBL_SECONDS' => 'δευτερόλεπτα',
	'LBL_JUSTNOW' => 'μόλις τώρα',
	'LBL_CUSTOM_INFORMATION' => 'Προσαρμοσμένες πληροφορίες',
	'LBL_NO_RECENT_UPDATES' => 'Καμμία πρόσφατη ενημέρωση',
	'LBL_NO_DATA' => 'Χωρίς δεδομένα',
	'LBL_PERMISSION_DENIED' => 'Άρνηση Έγκρισης',
	'LBL_HANDLER_NOT_FOUND' => 'Handler not found',
	'LBL_FILTER' => 'Φίλτρο',
	'LBL_DUE' => 'μέσα σε',
	'LBL_DAYS' => 'ημέρες',
	'LBL_COMPLETED' => 'ολοκληρώθηκαν',
	'LBL_AGO' => 'πριν από',
	'LBL_CHANGED' => 'αλλάχθηκαν',
	'SINGLE_Users' => 'Χρήστης',
	'LBL_MATCHED_THIS_CRITERIA'=> 'αντιστοιχούν αυτά τα κριτήρια',
	'LBL_NO_SCHEDULED_ACTIVITIES' => 'Καμμία προγραμματισμένη δραστηριότητα',
	'LBL_NO_OVERDUE_ACTIVITIES' => 'Καμμία εκπρόθεσμη δραστηριότητα',
	'LBL_NO_UPDATES_OR_COMMENTS' => 'Καμμία ενημέρωση η σχόλια',
	'LBL_MINI_LIST' => 'Mini Λίστα',
	'LBL_NOTEPAD' => 'Σημειωματάριο',
	'LBL_NOTEPAD_NAME' => 'Όνομα Σημειωματάριου',
	'LBL_NOTEPAD_CONTENT' => 'Περιεχόμενο Σημειωματάριου',
	'LBL_LAST_SAVED_ON' => 'Τελευταία Αποθήκευση στις',
	'Mini List' => 'Mini Λίστα',
	'Notebook' => 'Σημειωματάριο',
	'LBL_RESULT_FOR_THE_TAG' => 'Αποτέλεσμα για την ετικέτα',
	'LBL_ALL_USERS' => 'Όλοι οι χρήστες',
	'LBL_BOTH' => 'Και τα δυο',
	'LBL_SHOW' => 'Προβολή',
	'LBL_MY' => 'Μου',
	'LBL_SELECT_DATE_RANGE' => 'Επιλέξτε Εύρος ημερομηνιών',

	// Basic Strings- custom view
	'LBL_VIEW_NAME' => 'Όνομα Λίστας',
	'LBL_CREATE_VIEW' => 'Δημιουργία νέας προβολής',
	'LBL_BASIC_DETAILS' => 'Βασικές πληροφορίες',
	'LBL_CHOOSE_COLUMNS' => 'Επιλέξτε στήλες και διάταξη',
	'LBL_MAX_NUMBER_FILTER_COLUMNS' => 'Μέγιστο 15',
	'LBL_FILTER_ON_DATE' => 'Φιλτράρισμα ημερομηνίας',
	'LBL_CHOOSE_FILTER_CONDITIONS' => 'Επιλέξτε συνθήκες φίλτρων',
	'LBL_ADD_CONDITION' => 'Προσθήκη Συνθήκης',
	'LBL_SET_AS_DEFAULT' => 'Ορισμός ως Προεπιλογή',
	'LBL_LIST_IN_METRICS' => 'Εμφάνηση στους Μετρητές',
	'LBL_SET_AS_PUBLIC' => ' Ορισμός ως Δημόσιο',
	'LBL_AND' => 'και',
	'LBL_OR' => 'ή',
	'LBL_ADD_MORE_COLUMNS' => 'Προσθήκη περισσότερων στηλών',
	'LBL_ADD_GROUP' => 'Προσθήκη Ομάδος',

	//DateFilter Conditions
	'LBL_CUSTOM' => 'Προσαρμοσμένο',
	'LBL_PREVIOUS_FY' => 'Προηγούμενο FY',
	'LBL_CURRENT_FY' => 'Τρέχων FY',
	'LBL_NEXT_FY' => 'Επόμενο FY',
	'LBL_PREVIOUS_FQ' => 'Προηγούμενο FQ',
	'LBL_CURRENT_FQ' => 'Τρέχων FQ',
	'LBL_NEXT_FQ' => 'Επόμενο FQ',
	'LBL_YESTERDAY' => 'Χθές',
	'LBL_TODAY' => 'Σήμερα',
	'LBL_TOMORROW' => 'Αύριο',
	'LBL_LAST_WEEK' => 'Προηγούμενη Εβδομάδα',
	'LBL_CURRENT_WEEK' => 'Τρέχων Εβδομάδα',
	'LBL_NEXT_WEEK' => 'Επόμενη Εβδομάδα',
	'LBL_LAST_MONTH' => 'Προηγούμενος Μήνας',
	'LBL_CURRENT_MONTH' => 'Τρέχων Μήνας',
	'LBL_NEXT_MONTH' => 'Επόμενος Μήνας',
	'LBL_LAST_7_DAYS' => 'Τελευταίες 7 ημέρες',
	'LBL_LAST_14_DAYS' => 'Τελευταίες 14 ημέρες',
	'LBL_LAST_30_DAYS' => 'Τελευταίες 30 ημέρες',
	'LBL_LAST_60_DAYS' => 'Τελευταίες 60 ημέρες',
	'LBL_LAST_90_DAYS' => 'Τελευταίες 90 ημέρες',
	'LBL_LAST_120_DAYS' => 'Τελευταίες 120 ημέρες',
	'LBL_NEXT_30_DAYS' => 'Επόμενες 30 ημέρες',
	'LBL_NEXT_60_DAYS' => 'Επόμενες 60 ημέρες',
	'LBL_NEXT_90_DAYS' => 'Επόμενες 90 ημέρες',
	'LBL_NEXT_120_DAYS' => 'Επόμενες 120 ημέρες',

	//advanced Filter Options
	'LBL_NONE' => 'κανένα',
	'LBL_EQUALS' => 'ίσο με',
	'LBL_NOT_EQUAL_TO' => 'δεν είναι ίσο με',
	'LBL_STARTS_WITH' => 'ξεκινάει με',
	'LBL_ENDS_WITH' => 'τελειώνει με',
	'LBL_CONTAINS' => 'περιέχει',
	'LBL_DOES_NOT_CONTAIN' => 'δεν περιέχει',
	'LBL_LESS_THAN' => 'μικρότερο από',
	'LBL_GREATER_THAN' => 'μεγαλύτερο από',
	'LBL_LESS_THAN_OR_EQUAL' => 'μικρότερο ή ίσο',
	'LBL_GREATER_OR_EQUAL' => 'μεγαλύτερο ή ίσο',
	'LBL_BEFORE' => 'πρίν',
	'LBL_AFTER' => 'μετά',
	'LBL_BETWEEN' => 'μεταξύ',
	'LBL_IS_EMPTY'=> 'κενό',
	'LBL_IS_NOT_EMPTY' => 'is not empty',
	'LBL_APPROVE' => 'Έγκριση',
	'LBL_HAS_CHANGED' => 'έχει αλλάξει',
	'LBL_HAS_CHANGED_TO' => 'έχει αλλάξει σε',
	'LBL_HAS_CHANGED_FROM' => 'έχει αλλάξει από',
	'LBL_LESS_THAN_OR_EQUAL_TO' => 'μικρότερο ή ίσο με',
	'LBL_GREATER_THAN_OR_EQUAL_TO' => 'μεγαλύτερο ή ίσο με',
	'LBL_IS_NOT' => 'δεν είναι',
	'LBL_IS_ADDED' => 'έχει προστεθεί',
	'LBL_IS_TODAY' => 'είναι σήμερα',
	'LBL_IS_TOMORROW' => 'είναι αύριο',
	'LBL_IS_YESTERDAY' => 'είναι χτές',
	'LBL_LESS_THAN_DAYS_LATER' => 'λιγότερο από ημέρες αργότερα',
	'LBL_MORE_THAN_DAYS_LATER' => 'περισσότερο από ημέρες αργότερα',

	//Detail view summary widgets
	'LBL_OWNER' => 'Κάτοχος',
	'LBL_CREATED_ON' => 'Δημιουργήθηκε στις',
	'LBL_MODIFIED_ON' => 'Τροποποιήθηκε στις',
	'LBL_MODIFIED' => 'Τροποποιήθηκε',
	'LBL_COMMENTED' => 'Σχολιάστηκε',

	//calender set-reminder
	'LBL_BEFORE_EVENT' => ' Πρίν από το Συμβάν',

	//Dashboard widgets
	'History' => 'Ιστορικό',
	'Upcoming Activities' => 'Προσεχείς Δραστηριότητες',
	'Overdue Activities' => 'Εκπρόθεσμες Δραστηριότητες',
	'Funnel' => 'Χωνί',
	'Potentials by Stage' => 'Ευκαιρίες Ανά Στάδιο',
	'Pipelined Amount' => 'Pipeline Πωλήσεων',
	'Total Revenue' => 'Συνολικά Έσοδα',
	'Top Potentials' => 'Κορυφαίες Ευκαιρίες',
	'Forecast' => 'Πρόγνωση',
	'Leads Created' => 'Εγγεγραμμένες Προοπτικές',
	'Leads by Status' => 'Προοπτικές ανά Κατάσταση',
	'Leads by Source' => 'Προοπτικές ανα Πηγή ',
	'Leads by Industry' => 'Προοπτικές ανά Κλάδο',
	'Tickets by Status' => 'Δελτία ανά Κατάσταση',
	'Open Tickets' => 'Ανοιχτά Δελτία',
	'Funnel Amount' => 'Συνολικό Ποσό ανά Επίπεδο Πωλήσεων',
	'Key Metrics' => 'Βασικές Μετρήσεις',
	'Mini List' => 'Mini Λίστα',
	'Tag Cloud' => 'Ετικετοσύννεφο',
	'Notebook' => 'Σημειωματάριο',

	//Exports strings
	'LBL_EXPORT_ALL_DATA' => 'Εξαγωγή Όλων των Δεδομένων',
	'LBL_EXPORT_DATA_IN_CURRENT_PAGE' => 'Εξαγωγή Δεδομένων σε Αυτή την Σελίδα',
	'LBL_EXPORT_SELECTED_RECORDS' => 'Εξαγωγή των Επιλεγμένων εγγραφών',
	'LBL_EXPORT_RECORDS' => 'Εξαγωγή εγγραφών',
	'LBL_NO_RECORD_SELECTED' => 'Καμία εγγραφή δεν έχει Επιλεχθεί',
	'LBL_CAN_NOT_REMOVE_DEFAULT_WIDGET' => 'Το προεπιλεγμένο widget δεν αφαιρείται',
	'LBL_CUSTOM_VIEW_NAME_DUPLICATES_EXIST' => 'Αυτό το φίλτρο υπάρχει ήδη',
	'LBL_TYPE_AND_SEARCH' => 'Πληκτρολόγηση και αναζήτηση',
		'LBL_EXPORT_CURRENCY_TOOLTIP_TEXT'=>'For exporting Currency values in Line items, Vtiger will use this setting to export as this currency. Any currency values outside the line items tables, will be exported as in User\'s preferred currency (selected in \'My Preferences\')',
		'LBL_EXPORT_LINEITEM_CURRENCY'=>'Choose Currency (For Line Item Values)',
		'LBL_EXPORT_USER_CURRENCY' =>'Το προτιμώμενο νόμισμά μου',
		'LBL_EXPORT_RECORD_CURRENCY'=>'Νόμισμα που καθορίζεται στην εγγραφή',
	'LBL_EXPORT_FORMAT' => 'Μορφή Εξαγωγής',
	'LBL_EXPORT_DATA' => 'Εξαγωγή Δεδομένων',

	'LBL_CUSTOMIZE' => 'Προσαρμογή',
	'LBL_ADD_MANAGE_MODULES' => 'Modules',
	'LBL_CUSTOMIZE_MAIN_MENU' => 'Αριστερά Μενού',
	'LBL_LABELS' => 'Labels',
	'LBL_WORKFLOWS' => 'Workflows',
	'LBL_PICKLIST' => 'Picklists',

	// Added Common Keys for all modules
	'Account Name' => 'Όνομα Εταιρείας',
	'Add Comment' => 'Προσθήκη Σχόλιου',
	'Adjustment' => 'Προσαρμογή',
	'Annual Revenue' => 'Ετήσια Έσοδα',
	'Apparel'=>'Ενδύματα',
	'Banking'=>'Τραπεζικός',
	'Billing Address' => 'Διεύθυνση Χρέωσης ',
	'Billing City' => 'Πόλη Χρέωσης',
	'Billing Code' => 'Ταχ. Κώδικας Χρέωσης',
	'Billing Country' => 'Χώρα Πληρωμής',
	'Billing Po Box' => 'Τ.Θ. Χρέωσης',
	'Billing State' => 'Νομός Χρέωσης',
	'Biotechnology'=>'Βιοτεχνολογία',

	//for SO PO and Quotes
	'FedEx'=>'FedEx',
	'UPS'=>'UPS',
	'USPS'=>'USPS',
	'DHL'=>'DHL',
	'BlueDart'=>'BlueDart',
	'Carrier' => 'Μεταφορέας',
	'Category'=>'Κατηγορία',
	'Chemicals'=>'Χημικά',
	'City' => 'Πόλη',

	'Cold Call'=>'Τηλεφωνική Επαφή',
	'Existing Customer'=>'Υφιστάμενος Πελάτης',
	'Self Generated'=>'Αυτοδημιούργητος',
	'Employee'=>'Υπάλληλος',
	'Partner'=>'Συνέταιρος',
	'Public Relations'=>'Δημόσιες Σχέσεις',
	'Direct Mail'=>'Απευθείας Email',
	'Conference'=>'Συνέδριο',
	'Trade Show'=>'Εμπορική Έκθεση',
	'Web Site'=>'Ιστοσελίδα',
	'Word of mouth'=>'Δια Στόματος',
	'Other'=>'Άλλο',

	//for leads and accounts
	'--None--'=>'--Κανένα--',
	'Acquired'=>'Αποκτήθηκε',
	'Active'=>'Ενεργός',
	'Market Failed'=>'Η αγορά απέτυχε',
	'Project Cancelled'=>'Το Έργο Ματαιώθηκε',
	'Shutdown'=>'Έκλεισε',
	'Apparel'=>'Ενδύματα',
	'Banking'=>'Τραπεζικός',
	'Biotechnology'=>'Βιοτεχνολογία',
	'Chemicals'=>'Χημικά',
	'Communications'=>'Επικοινωνίες',
	'Construction'=>'Κατασκευές',
	'Consulting'=>'Συμβουλευτική',
	'Education'=>'Εκπαίδευση',
	'Electronics'=>'Ηλεκτρονικά',
	'Energy'=>'Ενέργεια',
	'Engineering'=>'Μηχανολογικά',
	'Entertainment'=>'Διασκέδαση',
	'Environmental'=>'Περιβαλλοντολογική',
	'Finance'=>'Οικονομική',
	'Food & Beverage'=>'Φαγητό και Αναψυκτικά',
	'Government'=>'Κρατική',
	'Healthcare'=>'Υγεία',
	'Hospitality'=>'Φιλοξενία',
	'Insurance'=>'Ασφάλιση',
	'Machinery'=>'Επιστήμες Μηχανικών',
	'Manufacturing'=>'Βιομηχανία',
	'Media'=>'Μ.Μ.Ε',
	'Not For Profit'=>'Μη Κερδοσκοπική',
	'Recreation'=>'Μεταποίησης',
	'Retail'=>'Λιανικής',
	'Shipping'=>'Μεταφορική',
	'Technology'=>'Τεχνολογίας',
	'Telecommunications'=>'Τηλεπικοινωνιών',
	'Transportation'=>'Ταξίδια',
	'Utilities'=>'Παροχών',

	'Contact Name' => 'Όνομα Επαφής',
	'Conversion Rate' => 'Ποσοστό μετατροπής',

	'Shipping Address' => 'Διεύθυνση Αποστολής',
	'Shipping City' => 'Πόλη Αποστολής',
	'Shipping State' => 'Νομός Αποστολής',
	'Shipping Code' => 'Κωδικός Αποστολής',
	'Shipping Country' => 'Χώρα Αποστολής',
	'Shipping Po Box' => 'Τ.Θ.',
	'Country' => 'Χώρα',
	'Description' => 'Περιγραφή',

	'Created'=>'Δημιουργήθηκε',
	'Approved'=>'Εγκρίθηκε',
	'Delivered'=>'Παραδόθηκε',
	'Cancelled'=>'Ακυρώθηκε',

	'Currency' => 'Νόμισμα',
	'LBL_BASE_CURRENCY' => 'Προεπιλεγμένο Νόμισμα',

	'Discount Percent' => 'Ποσοστό Έκπτωσης',
	'Discount Amount' => 'Ποσό Έκπτωσης',
	'Item Discount Amount' => 'Ποσό Έκπτωσης Αντικειμένου',
	'Net Price' => 'Καθαρή τιμή', 
	'Item Discount Percent' => 'Ποσοστό Έκπτωσης Αντικειμένου',

	'Due Date' => 'Προθεσμία',
	'Due Date & Time' => 'Ημερομηνία & Ώρα Προθεσμίας',
	'Email' => 'Πρωτεύον Email',
	'Secondary Email' => 'Δευτερεύον Email',
	'Other Email' => 'Άλλο Email',
	'Email Opt Out' => 'Εξαίρεση από Email',
	'Is Converted From Lead' => 'Μετατράπηκε απο Δυνητικός',
	'Expected Close Date' => 'Αναμενόμενη ημερομηνία κλεισίματος',
	'Fax' => 'Φαξ',

	'Last Name' => 'Επώνυμο',
	'First Name' => 'Όνομα',

	'High' => 'Υψηλή',
	'Low' => 'Χαμηλή',
	'In Progress' => 'Σε Εξέλιξη',

	'Subject' => 'Θέμα',
	'Shipping Address'=>'Διεύθυνση Αποστολής',
	'Shipping Po Box'=>'Τ.Θ.',
	'Shipping City'=>'Πόλη Αποστολής',
	'Shipping State'=>'Νομός Αποστολής',
	'Shipping Code'=>'Τ.Κ. Αποστολής',
	'Shipping Country'=>'Χώρα Αποστολής',
	'Terms & Conditions' => 'Όροι Και Προϋποθέσεις',
	'Item Name' => 'Ονομασία Αντικειμένου',
	'Quantity' => 'Ποσότητα',
	'List Price' => 'Τιμή Πώλησης',
	'Image' => 'Εικόνα',
	'Purchase Cost' => 'Κόστος αγοράς',
	'Margin' => 'Περιθώριο',
	'Item Comment' => 'Σχολιασμός Αντικειμένου',
	'Tax1' => 'Φόρος1',
	'Tax2' => 'Φόρος2',
	'Tax3' => 'Φόρος3',
	'Excise Duty' => 'Ειδικός Φόρος Κατανάλωσης',
	'Total' => 'Σύνολο',
	'Sub Total' => 'Υποσύνολο',
	'Tax Type' => 'Φορολογικός τύπος',
	'S&H Amount' => 'Ποσόστωση ταχυδρόμησης',
	'Status' => 'Κατάσταση',
	'Vendor Name'=>'Όνομα Προμηθευτή',

	'LBL_ADDRESS_INFORMATION' => 'Λεπτομέρειες Διεύθυνσης',
	'LBL_DESCRIPTION_INFORMATION' => 'Λεπτομέριες Περιγραφής',
	'LBL_TERMS_INFORMATION' => 'Όροι και Προϋποθέσεις',
	'LBL_PRICING_INFORMATION' => 'Πληροφορίες Τιμολόγησης',
	'LBL_RELATED_PRODUCTS' => 'Λεπτομέρειες προιόντος',
	'LBL_REMINDER_INFORMATION' => 'Λεπτομέρειες υπενθύμισης',

	'LBL_FOLDER_SAVED' => 'Ο φάκελος αποθηκεύτηκε',
	'LBL_FOLDER_EXISTS' => 'Ο φάκελος υπάρχει ήδη',
	'LBL_FOLDER_DELETED' => 'Ο φάκελος διαγράφηκε',
	'LBL_EDIT_FOLDER' => 'Επεξεργασία φακέλου',

	'Lead Source' => 'Προέλευση Δυνητικού',
	'Mobile' => 'Κινητό Τηλέφωνο',

	'Notify Owner' => 'Ειδοποίηση κατώχου',
	'Other Phone' => 'Δευτερεύον Τηλ',
	'Phone' => 'Πρωτεύον Τηλέφωνο',

	'State' => 'Νομός',
	'Po Box' => 'Τ.Θ.',
	'Postal Code' => 'Τ.Κ.',

	'Potential Name' => 'Όνομα Ευκαιρίας',
	'Priority'=>'Προτεραιότητα',

	'Product Name' => 'Όνομα Προϊόντος',
	'Rating' => 'Κατάταξη',

	'Related To' => 'Σχετίζετε με',
	'Type' => 'Τύπος',

	'Reviewed'=>'Ελέγχθηκε',
	'Salutation' => 'Προσφώνηση',
	'Street' => 'Οδός',
	'Support Start Date' => 'Ημ. Έναρξης Υποστήριξης',
	'Support Expiry Date' => 'Ημ. Λήξης Υποστήριξης',
	'Sales Start Date'=>'Ημ. Έναρξης Πώλησης',
	'Sales End Date'=>'Ημ.Λήξης Πώλησης',

	//Dashboard list of widgets translation
	'Open Tickets' => 'Ανοιχτά Αιτήματα',
	'LBL_SELECT_STATUS' => 'Επιλέξτε Κατάσταση',
	'LBL_BLANK' => '-Κενό-',

	//PageTitle translations
	'LBL_VTIGER_CRM_HONEST_OPEN_SOURCE' => 'vtiger CRM On Demand',

	//Translations used in inventory modules for sopy address
	'SINGLE_Accounts' => 'Εταιρεία',
	'SINGLE_Contacts' => 'Επαφή',

	//Weekdays in 3 letters translations
	'LBL_Sun' => 'Κυρ',
	'LBL_Mon' => 'Δευ',
	'LBL_Tue' => 'Τρι',
	'LBL_Wed' => 'Τετ',
	'LBL_Thu' => 'Πεμ',
	'LBL_Fri' => 'Παρ',
	'LBL_Sat' => 'Σαβ',

	//Months in 3 letters translations
	'LBL_Jan' => 'Ιαν',
	'LBL_Feb' => 'Φεβ',
	'LBL_Mar' => 'Μαρ',
	'LBL_Apr' => 'Απρ',
	'LBL_May' => 'Μαι',
	'LBL_Jun' => 'Ιου',
	'LBL_Jul' => 'Ιου',
	'LBL_Aug' => 'Αυγ',
	'LBL_Sep' => 'Σεπ',
	'LBL_Oct' => 'Οκτ',
	'LBL_Nov' => 'Νοε',
	'LBL_Dec' => 'Δεκ',

	'LBL_CALENDAR_SETTINGS' => 'Ρυθμίσεις Ημερολογίου',
	'Reminder Interval' => 'χρονικό διάστημα υπενθύμισης',

	//Translations used in inventory modules for address
	'SINGLE_Accounts' => 'Εταιρεία',
	'SINGLE_Contacts' => 'Επαφή',
	'HelpDesk' => 'Αιτήματα',
	'LBL_TAG_CLOUD' => 'Ετικετοσύννεφο',

	'LBL_NO_RECORDS' => 'Καμία Εγγραφή',
	'LBL_NO_RELATED' => 'Κανένας Συσχετισμός',
	'LBL_GLOBAL_SEARCH_MAX_MESSAGE' => 'Μόνο τα 100 πρώτα αποτελέσματα των ενοτήτων εμφανίζονται παρακάτω. Για σχετικά αποτελέσματα απο μια ενότητα παρακαλώ επιλέξτε την ενότητα για αναζήτηση',
	'LBL_GLOBAL_SEARCH_MAX_MESSAGE_FOR_MODULE' => 'Μόνο τα 100 πρώτα αποτελέσματα εμφανίζονται παρακάτω. Παρακαλώ χρησιμοποιήστε την Σύνθετη Αναζήτηση αν δεν ικανοποιήστε από το αποτέλεσμα',

	// used in reports detail view
	'LBL_ACTION' => 'Ενέργεια',
	'LBL_NOTE' => 'Σημείωση',
	'LBL_SELECT_OPTION' => 'Διαλέξτε μία Επιλογή',

	//Module Manager
	'LBL_TOOLTIP' => 'Διαχείριση Αναδυόμενης Βοήθειας',
	'LBL_MODULE_SEQUENCE_NUMBERING' => '%s Αρίθμησης',
	'LBL_CUSTOM_FIELD_MAPPING' => 'Προσαρμοσμένη Διασύνδεση Πεδίων',
	'LBL_WEBFORMS' => 'Δικτυακή Φόρμα',

	//Compose Email Strings
	'SINGLE_Emails' => 'Email',
	'Emails' => 'Emails',
	'LBL_SELECT_EMAIL_IDS' => 'Επιλογή Email',
	'LBL_SUBJECT' => 'Θέμα',
	'LBL_ATTACHMENT' => 'Επισυναπτόμενο',
	'LBL_BROWSE_CRM' => 'Περιήγηση CRM',
	'LBL_SEND' => 'Αποστολή',
	'LBL_SAVE_AS_DRAFT' => 'Αποθήκευση ως Πρόχειρο',
	'LBL_GO_TO_PREVIEW' => 'Προεπισκόπηση',
	'LBL_SELECT_EMAIL_TEMPLATE' => 'Επιλογή Πρότυπου Email',
	'LBL_COMPOSE_EMAIL' => 'Σύνταξη Email',
	'LBL_CC' => 'Cc',
	'LBL_BCC' => 'Bcc',
	'LBL_ADD_CC' => 'Προσθήκη Cc',
	'LBL_ADD_BCC' => 'Προσθήκη Bcc',
	'LBL_MAX_UPLOAD_SIZE' => 'Ανώτατο όριο',
	'LBL_EXCEEDED' => 'Υπερβαίνει',
	'LBL_OPERATION_NOT_PERMITTED' => 'Η ενέργεια δεν Επιτρέπεται',
	'LBL_MERGE' => 'Συγχώνευση',
	'LBL_FIND_DUPLICATES' => 'Find Duplicates',
	'LBL_MERGING_CRITERIA_SELECTION' => 'Επιλογή Κριτηρίων Συγχώνευσης',
	'LBL_AVAILABLE_FIELDS' => 'Διαθέσιμα Πεδία',
	'LBL_MERGE_RECORDS_DESCRIPTION' => 'Η κύρια εγγραφή θα διατηρηθεί μετά τη συγχώνευση. Μπορείτε να επιλέξετε τη στήλη για να διατηρήσουν τις τιμές.
										Η άλλη εγγραφή θα διαγραφεί, αλλά οι σχετικές πληροφορίες θα συγχωνευθούν.',
	'LBL_MERGE_RECORDS_IN' => 'Συγχώνευση εγγραφών στα',
	'LBL_FIELDS' => 'Πεδία',
	'LBL_RECORD' => 'Εγγραφές',
	'LBL_NO_DUPLICATED_FOUND' => 'Δεν βρέθηκαν διπλότυπα',
	'LBL_MERGE_SELECT' => 'Συγχώνευση Επιλεγμένων',

	//sbproducts translation
	'LBL_BACK_TO_PRODUCTS' => 'Πίσω στα Προϊόντα',

	//Translations used for Export to Pdf
	'Valid Date' => 'Έγκυρη Ημερομηνία',
	'Phone: ' => 'Τηλ: ',
	'Issued Date' => 'Ημερομηνία Έκδοσης',
	'Shipping & Handling Charges' => 'Χρεώσεις Ταχυδρόμησης',
	'Shipping & Handling Tax:' => 'Φόρος Ταχυδρόμησης:',
	'Discount'=>'Έκπτωση',
	'Net Total' => 'Καθαρό Σύνολο',
	'Product Code'=>'Κωδ. Προϊόντος',
	'Customer Name'=>'Όνομα Πελάτη',
	'Price'=>'Τιμή',
	'Tax:' => 'Φ.Π.Α:',
	'Contact Name' => 'Όνομα Επαφής',
	'Grand Total:' => 'Γενικό Σύνολο:',
	'Fax: ' => 'Φαξ: ',
	'Website: ' => 'Ιστοσελίδα: ',
	'Tax' => 'Φόρος',
	'LBL_ALPHABETS' => 'Α,Β,Γ,Δ,Ε,Ζ,Η,Θ,Ι,Κ,Λ,Μ,Ν,Ξ,Ο,Π,Ρ,Σ,Τ,Υ,Φ,Χ,Ψ,Ω,',

	//Realted tab strings
	'Service Contracts' => 'Συμβόλαια Υπηρεσιών',
	'Projects' => 'Έργα',
	'Sales Order' => 'Εντολή Πώλησης',
	'Purchase Order' => 'Εντολή Αγοράς',
	'Payments' => 'Πληρωμές',
	'List and Campaigns' => 'Λίστα και Καμπάνιες',
	'Project Tasks' => 'Εργασίες του Έργου',
	'Project Milestones' => 'Ορόσημα Έργου',

	'Labels Editor' => 'Labels Editor',
	'LBL_IGNORE_EMPTY_VALUES' =>'Παράβλεψη κενών τιμών',

	//Related tabs of Products
	'Product Bundles' => 'Συνδυαστικά Πακέτα',
	'Parent Product' => 'Γονικό Προϊόν',
	'LBL_PRODUCT_BUNDLE' => 'Συνδυαστικό Πακέτο',
	'LBL_EDIT_QUANTITY' => 'Επεξεργασία Ποσότητας',
	'LBL_ADD_TO_PRODUCTS' => 'Προσθήκη Προϊόντος',

	'LBL_MANAGE_USERS' => 'Διαχείριση Χρηστών',
	'LBL_TRANSFER_OWNERSHIP' => 'Μεταβίβαση Κυριότητας',
	'LBL_SELECT_RELATED_MODULES' => 'Επιλέξτε Σχετικές ενότητες',
	'LBL_ASSIGNED_TO' => 'Ανατέθηκε σε',
	//Comments Field Labels for Workflow
	'Comment' => 'Σχόλιο',
	'Last Comment' => 'Τελευταίο Σχόλιο',
	'Last 5 Comments' => 'ελευταία 5 Σχόλια',
	'All Comments' => 'Όλα τα Σχόλια',

	//Feedback on removing old version
	'LBL_OLD_VERSION_REMOVED_SOON' => 'Important Note on Old look',
	'LBL_FEEDBACK_ON_REMOVING_OLD_VERSION' => 'We are happy to share that old look will be available until February, 2014 . We added the following features to the new look recently<br><br>1. Pivot Reports<br>2. Custom Charts<br>3. Quick Search in Lists<br><br>If you have suggestions on new look, please share with us below.',
	'LBL_FEEDBACK_PLACEHOLDER' => 'Share your suggestions here..',
	'LBL_SUBMIT_FEEDBACK' => 'Submit feedback',
	'LBL_DONT_SHOW_AGAIN' => 'Do not show this again',
	'LBL_CONTINUE_TO_OLD_LOOK' => 'Continue to Old Look',
	'LBL_LEFT_PANEL_SHOW_HIDE' => 'Left Panel Show/Hide',

	//Products Popup View
	'NOT_A_BUNDLE' => 'Δεν είναι Συνδυαστικό πακέτο',
	'LBL_SUB_PRODUCTS' => 'Υπο-προϊόντα',
	'LBL_MARK_AS_HELD' => 'Σημείωση ως Διεξήχθη',
	'LBL_MARK_AS_COMPLETED' => 'Σημειώστε ως Ολοκληρωμένο',
	'LBL_SMS_MAX_CHARACTERS_ALLOWED' => 'Για μηνύματα κειμένου επιτρέπονται έως 160 χαρακτήρες',
	'LBL_HIDE_COMPLETED_EVENTS' => 'Απόκρυψη ολοκληρωμένων συμβάντων ημερολογίου',
	'LBL_SETUP_WEBFORMS' => 'Ρυθμίσεις Δικτυακής Φόρμας',
	'LBL_SPECIAL_OPTIONS' => 'Ειδικές επιλογές',
	'LBL_PARENT_OWNER' => 'Κάτοχος γονικής Εγγραφής',
	'LBL_PASSWORD_LINK_EXPIRED_OR_INVALID_PASSWORD' => 'Ο σύνδεσμος πρόσβασης έχει λήξει ή έχετε πληκτρολογήσει μη έγκυρο συνθηματικό πρόσβασης',

	// Recurring Invoice
	'Half-Yearly' => 'Εξαμηνιαία',
	'LBL_FULLSCREEN' => 'Προβολή πλήρους οθόνης',
	'LBL_SETUP_WEBFORMS' => 'Ρυθμίσεις Δικτυακής Φόρμας',
	'LBL_MODULE_DISABLED' => ' Η ενότητα είναι απενεργοποιημένη',
	'Organization Name' => 'Όνομα Εταιρείας',
	'LBL_SOCIAL_TWITTER_WIDGET' => 'Δραστηριότητα Twitter',
	'LBL_WEEK' => 'Εβδομάδα',
	//Convert Lead and Potential
	'CANNOT_CONVERT' => 'Δεν είναι δυνατή η μετατροπή',
	'LBL_CONVERT_ERROR_TITLE' => 'Οι ενότητες είναι απενεργοποιημένες',
	'LBL_FOLLOWING_ARE_POSSIBLE_REASONS' => 'Πιθανές αιτίες περιλαμβάνουν:',
	'LBL_MANDATORY_FIELDS_ARE_EMPTY' => 'Τα υποχρεωτικά πεδία είναι κενά',

	// SMSNotifier Phone Format Warning
	'LBL_PHONE_FORMAT_WARNING' => 'Βεβαιωθείτε ότι ο αριθμός τηλεφώνου ακολουθεί την διεθνή μορφή E.164',
	'LBL_PHONEFORMAT_WARNING_CONTENT' => 'Η μορφοποίηση αριθμού E.164 μπορεί να έχει δεκαπέντε ψηφία και συνήθως γράφεται ως εξής: [+] [κωδικός χώρας] [αριθμός συνδρομητή, συμπεριλαμβανομένου του κωδικού περιοχής]
										 For example, to convert a US phone number (415 599 2671) to E.164 format, one would need to add the \'+\' prefix and the country code (which is 1) in front of the number (+1 415 599 2671). In the UK and many other countries internationally, local dialing requires the addition of a 0 in front of the subscriber number. However, to use E.164 formatting, this 0 must be removed. A number such as 020 7183 8750 in the UK would be formatted as +44 20 7183 8750.',
	'LBL_WARNING' => 'Προειδοποίηση',
	'LBL_ORIGIN' => 'Προέλευση',
	'SENT' => 'Απεσταλμένα',
	'RECEIVED' => 'Ληφθέντα',
	'QUEUED'=> 'Σε Αναμονή',
	'FAILED'=> 'Απέτυχαν',
	'SAVED' => 'Πρόχειρα',
	'MailManager' => 'Διαχείριση Email',
	'MAILSCANNER' => 'Μετατροπή Email',
	'LBL_SENDER_NAME' => 'Όνομα Αποστολέα',
	'SMSNotifier'=>'Ειδοποίηση με SMS',

	'Mobile Call' => 'Κλήση Κινητού',
	'LBL_NO_MORE_RESULTS' => 'Δεν υπάρχουν περισσότερα αποτελέσματα!',
	'Related To' => 'Σχετίζονται με',

	// Date Conditions
	'LBL_LESS_THAN_DAYS_AGO' => 'Λιγότερο από ημέρες πριν',
	'LBL_MORE_THAN_DAYS_AGO' => 'Πριν από αρκετές ημέρες',
	'LBL_IN_LESS_THAN' => 'Σε λιγότερο από',
	'LBL_IN_MORE_THAN' => 'Σε περισσότερες από',
	'LBL_DAYS_AGO' => 'Μέρες πριν',
	'LBL_DAYS_LATER' => 'Μέρες μετά',
	'LBL_LESS_THAN_HOURS_BEFORE' => 'Λιγότερο από ώρες πριν',
	'LBL_LESS_THAN_HOURS_LATER' => 'Λιγότερο από ώρες αργότερα',
	'LBL_MORE_THAN_HOURS_BEFORE' => 'Πάνω από ώρες πριν',
	'LBL_MORE_THAN_HOURS_LATER' => 'Περισσότερες από τις ώρες αργότερα',
	'LBL_INTERNAL_COMMENT' => 'Εσωτερικό σχόλιο',
	'LBL_NOTE_EXISTING_ATTACHMENTS_WILL_BE_REPLACED' => 'Σημείωση: Τα υπάρχοντα συνημμένα (εικόνες / αρχεία) θα αντικατασταθούν',

	//common standard fields
	'Created By' => 'Created By',
	'LBL_SEND_PDF_FOR_SIGNING' => 'Αποστολή PDF για υπογραφή',
	'LBL_CLICK_TO_EDIT' => 'Κάντε κλικ για επεξεργασία',
	'LBL_SIGNATURE_BLOCK' => 'Υπογραφή',
	'LBL_INCLUDE_SIGNATURE_INFO' => 'Η υπογραφή που έχει οριστεί στις Προτιμήσεις μου θα επισυναφθεί στο κάτω μέρος του email',
	'LBL_INCLUDE_SIGNATURE' => 'Συμπεριλάβετε την υπογραφή',

	// module builder created module first block label 
	'LBL_BASIC_INFORMATION' => 'Βασικές πληροφορίες',
	'LBL_CLICK_HERE'=>'Κάντε κλικ εδώ',

	//Recipient preferences labels
	'LBL_SELCT_EMAIL_RECIPIENTS' => 'Select Email Recipients',
	'LBL_REMEMBER_MY_PREF' => 'Remember my preference',
	'LBL_RECIPIENT_PREFS'=>'Recipient Preferences',
	'LBL_EMAIL_RECIPIENT_PREFS'=>'Email Recipient Preferences',
	'LBL_ERROR_SAVING_PREF' => 'Error in saving preferences. Please try later!',
	'LBL_NO_PREF_GIVEN' => 'No preferences given!',
	'LBL_PLEASE_ADD_EMAIL_FIELDS' => 'Please add email fields and try again',
	'LBL_RECIPIENT_SAVE_MESSAGE'=>'Save successful.These preferences will be treated as recipient email addresses when you send email from this module.',
	'LBL_PREF_RESET_MESSAGE' => 'Your recipient email preferences has been reset!',

	'LBL_COMPANY_DETAILS' => 'Company Details',
	'COMPANY_LOGO_HELP_TEXT' => 'Please upload your lovely company logo. <br>Besides showing your company logo on your CRM,<br>
									your company name and address details are used in <br>Email Campaigns (required to meet span regulations)<br>
									and in Quotes.',
	'COMPANY_LOGO_HELP_TEXT_2' =>"You can edit company details later from <br>
									'CRM Settings > Templates > Company Details' page",
	'LBL_CHOOSE_PREFERENCES' => 'Choose your Preferences',
	'PREFERENCES_HELP_TEXT' => 'Base Currency - Choose your primary currency. If you use multiple<br> 
								currencies, all the values are converted to base currency and stored,<br>
								using the conversion rate configured in CRM.',
	'PREFERENCES_HELP_TEXT_2' => 'Personal preferences can be configured by each user in your team.<br>
									These include Timezone, Language, Date Format, Number Format.<br>
									Number Format references are used for Currencies and other <br>
									number fields in the CRM<br>
									You can edit your preferences later from \'User Name > My Preferences \'',
	'LBL_CANNOT_BE_CHANGED_LATER' => 'Cannot be changed later',
	'IMPORT_CONTACTS_GOOGLE_HELP_TEXT' => 'We can bring contacts from Google and <br> you can also enable bi-direction sync to keep our<br>
									Vtiger contacts and Google contacts(in selected group) updated.<br>
									Click the button to authorize and get Contacts from Google.',
	'IMPORT_CONTACTS_CSV_HELP_TEXT' => 'You can import Contacts from CSV file.',
	'IMPORT_CONTACTS_CSV_HELP_TEXT2' => 'To Import Opportunities, Leads, Tickets, please look for Actions > Import button on any of the
										 list views.',
	'LBL_DOEST_FIRST_ROW_HEADER' => 'Does first row in your file contains column headers?',
	'LBL_SELECT_CSV_FILE' => 'Select CSV file',
	'LBL_START_IMPORTING' => 'Start Importing',
	'LBL_PRIMARY' => 'Primary',
	'LBL_GOOGLE_SYNC_INTIATED_MSG' => 'Your import is scheduled, Your contacts will be imported shortly.<br> Proceeding to Next step will not interrupt the import.',
	'LBL_IMPORT_SYNC_INTIATED_MSG' => 'Your import is in progress. You will receive an email when import is completed.<br> Proceeding to Next step will not interrupt the import.',
	'LBL_TELL_US_ABOUT_YOU' => 'Help us by telling us about your Company',
	'TELL_US_ABOUT_YOU_HELP_TEXT' => 'We continue to make improvements to the CRM, and <br>
									 knowing our users better will help us prioritize enhancements.',
	'TELL_US_ABOUT_YOU_HELP_TEXT_2' => 'The data you submitted here will not be revealed to anyone <Br>
										outside Vtiger.',
	'LBL_INVALID_IMAGE' => 'Invalid Image',
	'LBL_IMPORT_CONTACTS' => 'Import Contacts',
	'LBL_FROM_GOOGLE' => 'From Google',
	'LBL_FROM_CSV' => 'From CSV File',
	'LBL_NEXT' => 'Next',
	'LBL_FINISH' => 'Finish',
	'LBL_GET_CONTACTS_FROM_GOOGLE' => 'Get Contacts From Google',
	'LBL_PHONE_NUMBER' => 'Phone Number',
	'LBL_NUMBER_OF_EMPLOYEES' => 'Number of Employees',
	'LBL_INDUSTRY' => 'Industry',
	'LBL_HELP_DESK_EMAIL_HELP_TEXT' => 'Ticket related notifications will be sent from this Email address',
	'LBL_SOCIAL_DETAILS' => 'Link to social networks to find new customers, and respond to queries',
	'LBL_SOCIAL_AUTHORIZE_HELP'=>'Connect with your companys twitter account to post your messages and track engagement',
	'LBL_SOCIAL_AUTHORIZE' => 'Connect with Twitter',
	'LBL_SOCIAL_LINKED' => 'Your Vtiger is now linked to',
	'LBL_ENTER_KEYWORDS_HELP'=>'Vtiger will scan twitter and find messages with these words',
	'LBL_ENTER_KEYWORDS' => 'Enter Keywords',

	 // Social Module Strings
	'LBL_TWEETS' => 'Tweets',
	'LBL_FAVOURITES' => 'Favourites',
	'LBL_FOLLOWING' => 'Following',
	'LBL_FOLLOWERS' => 'Followers',
	'LBL_VIEW_FULL_PROFILE' => 'View Full Profile',
	'LBL_LOCATION' => 'Location',
	'LBL_DESCRIPTION' => 'Description',
	'LBL_JOINED' => 'Joined',
	'LBL_SEARCH_PROFILES_IN_TWITTER' => 'Search Profiles In Twitter',
	'LBL_CHOOSE_ANOTHER_PROFILE' => 'Choose Another Profile',
	'LBL_ADD_TICKET' => 'Add Ticket',
	'LBL_ADD_OPPORTUNITY' => 'Add Opportunity',
	'LBL_RETWEET' => 'Retweet',
	'LBL_RETWEETS' => 'Retweets',
	'LBL_UNDO_RETWEET' => 'Undo Retweet',
	'LBL_FAVOURITE' => 'Favourite',
	'LBL_UNDO_FAVOURITE' => 'Undo Favourite',
	'LBL_TWITTER_HANDLER_MSG' => 'To see this contact\'s profile summary and history add their Twitter Username or search profiles using the link below.',
	'LBL_ADD_EVENT_OR_TODO' => 'Add Event/Task',
	'LBL_ADD_TICKET_CONTACT' => 'Add Ticket + Contact',
	'LBL_ADD_CASE_CONTACT' => 'Add Case + Contact',
	'LBL_ADD_OPPORTUNITY_CONTACT' => 'Add Opportunity + Contact',
	'LBL_TWITTER_HANDLER_DETAILS' => 'Twitter Username Details',
	'LBL_PRIMARY_TWITTER' => 'Twitter Username',
	'LBL_ADD_TWITTER_HANDLER' => 'Add Twitter Username',
	'LBL_VIEW_TICKET' => 'View Ticket',
	'LBL_VIEW_CASE' => 'View Case',
	'LBL_VIEW_OPPORTUNITY' => 'View Opportunity',
	'LBL_CLICK_TO_SELECT_PROFILE' => 'Click to select profile',
	'LBL_INVALID_IMAGE' => 'Invalid Image',
	'LBL_NEXT' => 'Next',
	'LBL_FINISH' => 'Finish',
	// Module field to store Source of Record
	'Source' => 'Source',

	'LBL_DEFAULT_REPLY_TO' => 'Default Reply To for Emails', 
	'outgoing_server_from_email' => 'Outgoing Server From Email', 
	'hepldesk_support_email' => 'Helpdesk Support Email-Id', 
	'user_primary_email' => 'User Primary Email', 
	'LBL_DEFAULT_REPLY_TO_INFO' => 'This setting is applicable only for direct emails from CRM. It doesn\'t affect emails sent from workflows, email campaigns, etc.', 
	'search_in_all_fields'=>'Search in All fields',
	'search_in_name_field'=>'Search in Name field',
	'LBL_LOOKUP_SEARCH_MODE_INFO'=>'Ex: In Contact creation form, when you enter text in the organization name box this setting will control what fields in Organization are to be searched',

	'VAT' => 'VAT',
	'Sales' => 'Sales',
	'Service' => 'Service',
	'Pre Tax Total' => 'Pre Tax Total',
	'Received' => 'Received',
	'Balance' => 'Balance',
	'S&H Amount' => 'Charges',
	'S&H Percent' => 'Taxes On Charges',
	'Tax Region' => 'Tax Region',

	//Singular Modulenames
	'SINGLE_Potentials' => 'Opportunity',
	'SINGLE_HelpDesk' => 'Ticket',
	'SINGLE_Accounts' => 'Organization',
	'SINGLE_Contacts' => 'Contact',
	'SINGLE_Project' => 'Project',
	'LBL_ROLLUP_COMMENTS_INFO' => "If Roll up is set to 'On' comments on related records will be shown. 
								 For example, if you are viewing comments on an Organization record, comments added to related Contacts, Opportunities, Tickets, ..etc would also be displayed.",
	'LBL_ROLLUP_COMMENTS' => "Rollup Comments",

	//others
	'Engagement Score' => 'Engagement Score',
	'group' => 'Group',
	'individual' => 'Individual',
	'LBL_VIEW_FILE'=>'View file',
	'LBL_DOWNLOAD_FILE' => 'Download file',
	'LBL_PREVIEW_NOT_AVAILABLE' => 'Preview Not Available',
	'LBL_PREVIEW_SUPPORTED_FILES' => '<b><strong>Supported File Types : </strong></b><br><br><b>Pdf files</b><br><b>Text files - </b>txt,csv,ics<br><b>Open Document Files - </b>open document text(odt),open document spreadsheet(ods) and open document presentation(odp)<br><b>Multimedia files - </b>image, audio & video files<br>',
	'Mailing Address' => 'Mailing Address',
	'Other Address' => 'Other Address',
	'LBL_PREVIOUS' => 'Previous',
	'LBL_NEXT' => 'Next',
	'Workflows' => 'Workflows',
	'Primary Twitter' => 'Twitter Username',

	/* Vtiger7 Language Strings */
	'LBL_CLICK_HERE_TO_SELECT_ALL_RECORDS'=>'Select all records in this page',
	'LBL_CLICK_HERE_TO_MANAGE_LIST_COLUMNS'=>'Click here to manage List columns',
	'LBL_SHOW_MORE' =>'Show more',
	'LBL_DISPLAYING_RESULTS' => 'Displaying Results',
	'LBL_ADD_STAR' => 'Add Star',
	'LBL_REMOVE_STAR' => 'Remove Star',
	'LBL_UPDATE_LIST' => 'Update List',
	'LBL_SHARE_THIS_LIST' => 'Share this list',
	'LBL_ADD_USERS_ROLES' => 'Add users and roles',
	'LBL_LISTS' => 'Lists',
	'LBL_SEARCH_FOR_LIST' => 'Search for List',
	'LBL_MY_LIST' => 'My List',
	'LBL_SHARED_LIST' => 'Shared List',
	'LBL_MERGE_SELECTED_RECORDS' => 'Merge selected records',
	'LBL_MATCH_CRITERIA' => 'Duplicate Search Criteria',
	'LBL_MATCH_FIELDS' => 'Match Fields',
	'LBL_EDIT_CUSTOM'=>'Edit List',
	'LBL_SHOW_MAP'=>'Show Map',
	'LBL_ADD_TAB'=>'Add Tab',
	'LBL_TAB_NAME'=>'Dashboard Name',
	'LBL_SHARED_TAGS_ACCESS'=>'Shared tags are accessible by all users in Vtiger',
	'LBL_GOTO_TAGS'=>'Go to Settings > My preferences > My Tags to Edit or Delete your private tags',
	'LBL_UNLINK'=>'Unlink',
	'LBL_SWITCH_TO_OLD'=>'Switch to old version',
	'LBL_SLA_INFORMATION' => 'SLA Information',

	//configure columns
	'LBL_UPDATE_LIST' => 'Update List',
	'LBL_CONFIG_COLUMNS' => 'Configure Columns',
	'LBL_SELECTED_FIELDS' => 'Selected Fields',
	'LBL_AVAILABLE_FIELDS' => 'Available Fields',
	'LBL_SEARCH_FIELDS' => 'Search Fields',

	// Extensions
	'ExtensionStore' =>'Extension Store',
	'LBL_EXTENSIONS' => 'Extensions',
	'LBL_SYNC_LOG' => 'Sync Log',
	'LBL_SYNC_SETTINGS' => 'Sync Settings',
	'LBL_SYNC_NOW' => 'Sync Now',
	'LBL_DATE' => 'Date',
	'LBL_TIME' => 'Time',
	'LBL_SKIPPED' => 'Skipped',
	'vt_create' => 'Records Created in Vtiger',
	'vt_update' => 'Records Updated in Vtiger',
	'vt_delete' => 'Records Deleted in Vtiger',
	'vt_skip' => 'Records skipped in Vtiger',
	'app_create' => 'Records Created in %s',
	'app_update' => 'Records Updated in %s',
	'app_delete' => 'Records Deleted in %s',
	'app_skip' => 'Records skipped in %s',
	'LBL_DOWNLOAD_AS_CSV' => 'Download As CSV',
	'LBL_SOURCE_MODULE' => 'Source Module',
	'LBL_RECORD_NAME' => 'Record Name',
	'LBL_REASON' => 'Reason',
	'LBL_SELECT_MODULES_TO_SYNC' => 'Select modules to sync',
	'LBL_DATA' => 'Data',
	'LBL_ENABLE_SYNC' => 'Enable Sync',
	'LBL_FIELD_MAPPING' => 'Field Mapping',
	'LBL_SYNC_DIRECTION' => 'Sync Direction',
	'LBL_SYNC_BOTH_WAYS' => 'Sync Both Ways',
	'LBL_SAVE_SETTINGS' => 'Save Settings',
	'LBL_CONFIGURE' => 'Configure',
	'LBL_VIEW' => 'View',
	'LBL_CHANGE_USER' => 'Change User',

	'LBL_CREATE_LIST' => 'Create a New List',
	'sent' => 'Sent',
	'accepted' => 'Accepted',
	'SINGLE_Users' => 'User',
	'LBL_RECENT_COMMENTS' => 'Recent Comments',
	'LBL_ENGAGEMENT_HISTORY' => 'Engagement History',
	'LBL_NO_ENGAGEMENTS_FOUND' => 'No related Touchpoints',
	'LBL_MARKETING' => 'MARKETING',
	'LBL_SALES' => 'SALES',
	'LBL_PROJECT' => 'PROJECTS',
	'LBL_TOOLS' => 'TOOLS',
	'LBL_TAGS' => 'Tags',
	'LBL_SHARE_TAGS' => 'Public Tags',
	'LBL_SHARE_TAG' => 'Shared Tag(s)',
	'private' => 'private',
	'Tags' => 'Tags',
	'public' => 'shared',
	'Private/Shared' => 'Private/Shared',
	'LBL_TAG_FOR' => 'Tags For %s',
	'LBL_CURRENT_TAGS' => 'Current Tags',
	'LBL_CREATE_NEW_TAG'=> 'Create New Tag',
	'LBL_ADD_TAG' => 'Add Tag',
	'LBL_REMOVE_TAG' => 'Remove Tag',
	'LBL_TAG_SEPARATOR_DESC' => 'Use comma to separate multiple tags',
	'LBL_ENTER_TAG_NAME'=> 'Enter tag name',

	'LBL_SELECT_COLOR' => 'Select Color',
	'LBL_NO_TAG_EXISTS' => 'No Tag Exists',
	'LBL_ADD_NEW_TAG' => 'Add Tag',
	'LBL_SELECT_EXISTING_TAG' => 'Type here to select an existing tag',
	'LBL_CREATE_NEW_TAG' => 'Create new tag',
	'LBL_ADD_OR_SELECT_TAG' => 'Add/Select Tag',
	'LBL_SELECT_FROM_AVAIL_TAG' => 'Select from available tags',
	'LBL_MARKET_PLACE' => 'Market Place',

	'LBL_SHARE_THIS_LIST' => 'Share the list',
	'LBL_ADD_USERS_ROLES' => 'Add Users, Roles...',
	'EmailTemplates' => 'Email Templates',
	'LBL_BILLING' => 'Billing',
	'LBL_ENABLED' => 'Enabled',

	//Title added for buttons
	'LBL_CREATE_FILTER' => 'Create Filter',
	'LBL_IS' => 'is',
	'LBL_CREATION' => 'creation',
	'LBL_UPLOAD' => 'Upload',
	'LBL_ATTACH_FILES' => 'Attach Files',
	'LBL_KEY_FIELDS' => "Key Fields",
	'LBL_ADD_TODO' => 'Add Task',

	"LBL_VIEW_DETAILS" => "View Details",

	//Engagements History
	"LBL_HAPPENED_ON" => "Happened On",
	"LBL_HAPPENED" => 'Happened',
	"LBL_TYPE" => "Type",
	"LBL_STATUS" => "Status",
	"LBL_CUSTOMER" => "Related To",
	"LBL_SUMMARY" => "Summary",
	"LBL_ENGAGEMENTS" => "Touchpoints",

	'LBL_PLEASE_SELECT_ATLEAST_ONE_OPTION' => 'Please select at least one option',
	'LBL_STARRED' => 'Click to unfollow',
	'LBL_UNSTARRED' => 'Follow',
	'LBL_EDIT_EMAIL_PREFERENCE_TOOLTIP' => 'Edit these preferences from Settings dropdown in modules detail or list view',
	'LBL_SYSTEM' =>'System',
	'LBL_SHOW_MAP' => 'Show Map',
	'LBL_GOOGLE_MAP' => 'Google Map',
	'LBL_CREATION' => 'creation',
	'LBL_ADD_TODO' => 'Add Task',

	'LBL_KEY_METRICS' => 'Key Metrics',

	//Print template strings
	'LBL_TEMPLATE_NAME' => 'Template Name',
	'LBL_MODULE' => 'Module',
	'LBL_IS_DEFAULT' => 'Default Template',
	'LBL_SELECT_RECORD_FIELD' => 'Select Record Field',
	'LBL_PREVIEW' => 'Preview',
	'LBL_UNLINKED' => 'Unlinked',

	'LBL_FOLLOW' => 'Follow',
	'LBL_UNFOLLOW' => 'Unfollow',
	'Any' => 'Any',
	'LBL_NA' => '-NA-',
	'LBL_DISABLED' => 'Disabled',

	//help
	'LBL_HELP_ANSWERS' => 'Answers',
	'LBL_HELP_ARTICLES' => 'Articles',
	'LBL_HELP_TOUR' => 'Tour',
	'LBL_NO_HELP_ARTICLE_FOUND' => 'Sorry, no Article found',
	'LBL_HELP_SEARCH' => 'Search Help',
	'LBL_HELP_BROWSE_ALL' => 'Browse all',

	'LBL_EXPORT_FILE_NAME' => 'Export Filename',
	'LBL_EXTENSION_NOT_ALLOWED_FOR_NONADMIN' => '%s Sync is allowed only for admin users',
	'SINGLE_Invoice' => 'Invoice',
	'SINGLE_SalesOrder' => 'Sales Order',
	'SINGLE_PurchaseOrder' => 'Purchase Order',
	'SINGLE_Quotes' => 'Quote',
	'LBL_POST_YOUR_COMMENT_HERE' => 'Post your comment here',
	// Phone Calls
	'LBL_CLICK_TO_CALL' => 'Click-to-Call',
	'LBL_SHOW_TOTAL_NUMBER_OF_RECORDS' => 'Click for this list size',

	'LBL_GENERAL_FIELDS' => 'General Fields',
	'LBL_ROLL_UP' => 'Roll up',

	'LBL_TOUCH_POINTS' => 'Touchpoints',
	'LBL_HISTORY' => 'Touchpoints',
	'LBL_ENGAGEMENT_HISTORY' => 'Touchpoint History',
	'LBL_SETTINGS' => 'Settings',

	//List View and thumbnail view button labels
	'LBL_LIST_VIEW'=>'List View',
	'LBL_THUMBNAIL_VIEW'=>'Thumbnail View',
	'LBL_CHART_VIEW'=>'Chart View',
	'LBL_EMAIL_SUPPORT' => 'Email Support',
	'LBL_NO_ENTITIES_FOUND' => 'No %s found',

	'LBL_TRANSFER_ALL_CASES_TO' => 'Transfer All Cases To',
	'LBL_SLA_TO_BE_DELETED' => 'SLA To Be Deleted',
	'LBL_TO_USE_SWITCH_TO_NEW_LOOK' => 'To use <b>%s</b>, we recommend you to Switch to new look.',
	'LBL_INTERNAL_COMMENT_INFO' => 'The comment will only be seen by CRM users, if the internal comment checkbox is enabled. To notify customers (through configurable workflows or customer portal) leave this checkbox disabled',
	'LBL_CHANGE' => 'Change',
	'LBL_REVOKE_ACCESS' => 'Revoke Access',
	'GOOGLE_REVOKE_ACCESS_MESSAGE' => 'Clicking on this will remove existing Google authentication for Contacts and Calendar. It will not delete any records which are already synchronized.',
	'OFFICE_REVOKE_ACCESS_MESSAGE' => 'Clicking on this will remove existing Office365 authentication for Contacts, Calendar and Emails. It will not delete any records which are already synchronized.',
	'LBL_START_GUIDED_TOUR' => 'Start Guided Tour',
	'LBL_MENU' => 'Menu',
	'LBL_EMAIL_DOMAIN_HELPTEXT'=>'Email Domain field will be used to match Cases and Contacts created from Emails. '
	. 'For example, if a new support email comes from john@company.com, it would be linked to Organization that has '
	. 'company.com in the Email domain field. Multiple domains should be separated by commas',

	'LBL_SHARED_LIST_NON_ADMIN_MESSAGE' => 'This is a Shared list. Please contact your CRM Administrator to configure columns for All list',
	'LBL_SHARED_LIST_OWNER_MESSAGE' => 'This is a shared list. Please contact %s to change the columns of this list',

	'Mr.' => 'Mr.',
	'Ms.' => 'Ms.',
	'Mrs.' => 'Mrs.',
	'Dr.' => 'Dr.',
	'Prof.' => 'Prof.',
	'SINGLE_Cases'=>'Case',
	'LBL_TAX_MODE_INFO' =>'If Individual, Taxes will be picked from Product record. If Group, Taxes will be picked from Global settings.',
	'LBL_CURRENCY_INFO' =>'Values will be changed to the selected currency based on the configured conversion rate.',
	'LBL_TAX_REGION_INFO' =>'For Variable taxes, tax percentage will be based on selected Tax Region.',
	'LBL_TAX_CONFIGURE' =>'Configure tax region',
	'LBL_SEND_MSG_TO_SUPPORT' => 'Send email to support',
	'LBL_CHAT_WITH_SUPPORT' => 'Live chat with CRM expert',

	'LBL_ROLES' => 'Roles',
	'LBL_ROLEANDSUBORDINATE' => 'Role and Subordinates',
	'LBL_YOUR_LEARNING_SCORE' => 'Your CRM learning score',
	'LBL_SWITCH_TO_VTIGER7_NOW' => 'Switch to Vtiger7 by Feb 15th',
	'LBL_VTIGER6_RETIREMENT_NOTICE' => 'This version will be retired on Feb 15th 2016',
	'ModTracker' => 'Updates',
	'LBL_MAIL_SENT_SUCCESSFULLY' => 'Mail Sent Successfully',
	'LBL_FAILED_TO_SEND' => 'Failed to Send',

	'LBL_ESSENTIALS' => 'Essentials',
	'LBL_ALL_SETTINGS' => 'All Settings',
	'On' => 'On',
	'LBL_OPEN_IN_NEW_TAB' => 'Open in new tab',
	'LBL_DELETE_FOREVER'=>'Delete forever',
	'LBL_PLEASE_CLICK_ON_EDIT_TO_ADD_NOTE' =>'Please click on edit to add notes here..',
	'LBL_PLEASE_ENTER_YOUR_NOTE' => 'Please enter your notes here..',
	'LBL_PORTAL' => 'Portal',
	'LBL_SESSION' =>'Session',
	'LBL_SESSIONS' => 'Sessions',
	'week days later' => 'week days later',
	'more than week days later' => 'more than week days later',
	'less than week days later' => 'less than week days later',
	'week days ago' => 'week days ago',
	'more than week days ago' => 'more than week days ago',
	'less than week days ago' => 'less than week days ago',

	'LBL_DUPLICATES' => 'Duplicates',
	'LBL_DUPLICATES_DETECTED' => 'Duplicate(s) detected!',
	'LBL_DUPLICATES_FOUND_MESSAGE' => 'This %s cannot be saved since duplicate %s exists in Vtiger with matching values for %s.',
	'LBL_VTIGER_NOTIFICATION' => 'Message from : Vtiger System Notifications',
	'LBL_DUPLICATION_FAILURE_FROM_WORKFLOWS' => 'The following %s could not be saved from "%s" workflow, as another %s exists with the same values.',
	'LBL_DUPLICATION_FAILURE_FROM_WEBFORMS' => 'The following %s could not be saved from "%s" webform, as another %s exists with the same values.',
	'LBL_DUPLICATION_FAILURE_FOR_ADMIN' => 'You can %s to modify duplicate prevention rules.',
	'LBL_DUPLICATION_FAILURE_FOR_NON_ADMIN' => 'Contact your administrator for revising the duplicate rules',
	'LBL_DUPLICATE_RECORD_LISTS' =>'Duplicate %s(s) :',
	'LBL_COLUMNS_ADDED'=>'of %s columns added',
	'LBL_SHOW_ALL'=>'Show all',
	'LBL_LanguageEditor_WEBTITLE' => 'Labels Editor',
	'LBL_TAX_CALCULATIONS_WEBTITLE' => 'Tax Management',
	'LBL_Tags_WEBTITLE' => 'My Tags',
	'LBL_HIDE' => 'Hide',
	'LBL_PRINT' => 'Print',
	'LBL_FORWARD' => 'Forward',
	'LBL_NO_DEDUCTED_TAX'=>'No deducted taxes',
	'LBL_CLICK_TO_CONFIGURE'=>'Click here to configure',
	'LBL_KANBAN_VIEW_INFO' => 'Kanban view shows only the opportunities that match conditions of this list',
	'LBL_CUSTOM_FIELDS_MAX_LIMIT' => 'You can add only maximum of %s custom fields',
	'LBL_EXCEEDED_MODULE_RECORD_LIMIT' => '%s records limit (%s) exceeded',
	'LBL_EXCEEDED_MODULE_RECORD_LIMIT_TEXT' =>'We found that you have more than %s records in %s. <br> Exceed maximum limit of this edition. <br>Please remove the excess records and try again',
	'LBL_TEMPLATE_INFO_PART1'=>'To see all templates or templates of other modules, enter the module name or "All" in the Module Name search box.', 
	'LBL_TEMPLATE_INFO_PART2'=>'If recipients in TO field are not of the same module as the template, tracking will not be enabled for those recipients, and merge fields will not be merged.',
	'LBL_HIDDEN_BECAUSE_OF_DEPENDENCY' => 'Field is hidden because of dependency rule',
	'MAILCHIMP_REVOKE_ACCESS_MESSAGE' => 'Clicking on this will remove existing MailChimp authentication. It will not delete any records which are already synchronized.',
	// Added for Event Forms
	'LBL_VIEW_ANSWERS' => 'View answers',
	'LBL_ANSWERS' => 'Answers',

	//Default sort order translations
	'LBL_DEFAULT_SORT_ORDER' => 'Default sort column and sort order',
	'LBL_SELECT_COLUMN' => 'Select Column',
	'LBL_SELECT_SORT_ORDER' => 'Select Sort Order',
	'LBL_ASCENDING' => 'Ascending',
	'LBL_DESCENDING' => 'Descending',
	'LBL_DEFAULT_SORT_MESSAGE' => 'List is always sorted on this column by default for every new user session.',
	'LBL_QUEUED' => 'Queued',
	// End
	//Added for Inbox
	'LBL_EMAILS'=>'Emails',
	'LBL_CONVERSATIONS'=>'Conversations',
	'LBL_FROM_DISABLED_MESSAGE'=>'The mail server selected in Outgoing server settings page does not allow From address to be changed.',
	// End
	'LBL_MODULE_MANDATORY' => 'Module is mandatory',
	'Online' => 'Online',
	'Busy' => 'Busy',
	'LBL_BETA'=>'BETA',
	'JS_SHARED_WITH'=>'Shared with',
	 'LBL_REPLY_TO' =>'Reply to',
	'LBL_MODULE_ASSIGNMENT_RULES' => '%s Assignment Rules',

	'LBL_RECENT_UPDATES' => 'Recent Updates',
	'LBL_VIEW_UPDATES_IN_DETAIL' => 'Read More ...',
	'LBL_DEFAULT_DASHBOARD_TOOLTIP'=>'Make this dashboard as default by reordering it as the first tab!',
);

$jsLanguageStrings = array(
	'JS_EMAIL_SERVER_CONFIGURATION' => 'Please configure your outgoing server settings from the settings page',
	'JS_SMS_SERVER_CONFIGURATION' => 'Please configure your SMS notifier from the SMS notifier settings page',
	'JS_PLEASE_SELECT_ONE_RECORD' => 'Please select at least one record',
	//dropdown categary
	'JS_USERS' => 'Users',
	'JS_GROUPS' => 'Groups',
	'JS_ALL' => 'All',
	//Validation Error Message
	'JS_PLEASE_ENTER_VALID_VALUE' => 'Please enter a valid value',
	'JS_PLEASE_ENTER_VALID_TAG_NAME' => 'Please enter valid tag name',
	'JS_TAG_SAVED_SUCCESSFULLY' => 'Tag Saved Successfully',
	'JS_PLEASE_ENTER_VALID_EMAIL_ADDRESS' => 'Please enter a valid email address',
	'JS_CONTAINS_ILLEGAL_CHARACTERS' => 'Contains illegal characters',
	'JS_PHONE_NUMBER_LENGTH_EXCEEDED' => 'Phone number length exceeded limit',
	'JS_ACCEPT_POSITIVE_NUMBER' => 'Accepts only positive numbers',
	'JS_ACCEPT_WHOLE_NUMBERS' => 'Accepts only whole numbers',
	'JS_VALUE_SHOULD_BE_GREATER_THAN_ZERO' => 'Value should be greater than zero',
	'JS_NUMBER_SHOULD_BE_LESS_THAN_32' => 'Number should be less than 32',
	'JS_PLEASE_ENTER_VALID_DATE' => 'Please Enter Valid Date',
	'JS_PLEASE_ENTER_VALID_TIME' => 'Please Enter Valid Time',
	'JS_INVALID_PAGE_NUMBER' => 'Invalid Page Number',
	'JS_SUBJECT_VALUE_CANT_BE_EMPTY' => 'Subject value cannot be empty',
	'JS_PERCENTAGE_SHOULD_BE_LESS_THAN_100' => 'Percentage should be less than 100',


	'INVALID_NUMBER_OF' => 'Invalid number of',
	'INVALID_NUMBER' => 'Invalid number',
	'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_DELETE' => 'Are you sure that you want to delete?',

	'OVERWRITE_EXISTING_MSG1' => 'Overwrite the existing address with the selected ',
	'OVERWRITE_EXISTING_MSG2' => 'address details?',
	'SINGLE_Accounts' => 'Organization',
	'SINGLE_Contacts' => 'Contact',
	'SINGLE_Project' => 'Project',
	'SINGLE_ProjectMilestone' => 'Project Milestone',

	'LBL_DELETE_CONFIRMATION' => 'Are you sure you want to delete?', // This is added as duplicate as we need to show different message for different modules. Ex:Accounts has different message
	'LBL_UNLINK_CONFIRMATION' => 'Are you sure you want to unlink?',
	'LBL_DELETE_USER_CONFIRMATION' => 'When a User is deleted, user will be marked as "Inactive" and no new records can be assigned to the User, and the user will not be able to login. Are you sure you want to delete?',
	'LBL_DELETE_CONFIRMATION_NOTE' => 'Note : Deleted records will be kept in recycle bin and cleared after %s days',
	'LBL_MASS_DELETE_CONFIRMATION' => 'Are you sure you want to delete the selected Records?',
	'JS_LBL_SAVE' => 'Save',
	'JS_LBL_CANCEL' => 'Cancel',
	'JS_DUPLICTAE_CREATION_CONFIRMATION' => 'Organization Name already Exists.Do you want to create a duplicate record?',

	'SHOULD_BE_LESS_THAN_TODAY' => 'Must occur before today',
	'JS_PLEASE_SELECT_ATLEAST_ONE_OPTION' => 'Please select at least one option',
	'JS_SELECT_MODULE' => 'Please Select Module',
	'JS_PLEASE_SELECT_ATLEAST_ONE_MANDATORY_FIELD' => 'Please select at least one Mandatory Field',
	'JS_SELECT_MODULE' => 'Please select a module',
	'JS_PLEASE_ENTER_INTEGER_VALUE' => 'Please enter integer value',
	'JS_PLEASE_ENTER_DECIMAL_VALUE' => 'Please enter decimal value',
	'JS_PLEASE_ENTER_POSITIVE_DECIMAL_VALUE' => 'Please enter positive decimal value',

	'JS_START_TIME_SHOULD_BE_GREATER_THAN_CURRENT_TIME' => 'Start Time should be greater than Current Time',
	'JS_SHOULD_BE_LESS_THAN_CURRENT_DATE' => 'should be less than Current Date',
	'JS_SHOULD_BE_GREATER_THAN_CURRENT_DATE' => 'should be greater than Current Date',
	'JS_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO' => 'should be greater than or equal to',
	'JS_SHOULD_BE_LESS_THAN_OR_EQUAL_TO' => 'should be less than or equal to',
	'JS_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO' => 'should be greater than or equal to',
	'JS_CURRENT_DATE' => 'Current Date',
	'JS_PERCENTAGE_VALUE_SHOULD_BE_LESS_THAN_100' => 'Percentage value should be less than 100',
	'JS_ACCEPT_ONLY_NUMBER' => 'Accepts only numbers',
	'JS_THIS_FILE_HAS_ALREADY_BEEN_SELECTED' => 'This File has already been selected',
	'JS_MAX_FILE_UPLOAD_EXCEEDS' => 'max file Upload exceeds',
	'JS_THIS_DOCUMENT_HAS_ALREADY_BEEN_SELECTED' => 'This Document has already been attached',
	'JS_LIST_EXIST' => 'List already exists',


	//Roles
	'JS_FAILED_TO_SAVE' => 'Failed to save changes on server',

	//Import Translations
	'JS_IMPORT_FILE_CAN_NOT_BE_EMPTY' => 'Import File cannot be Empty',
	'JS_PLEASE_SELECT_ONE_FIELD_FOR_MERGE' => 'Select at least one matching field',
	'JS_MAP_NAME_CAN_NOT_BE_EMPTY' => 'Map Name cannot be empty',
	'JS_MAP_NAME_ALREADY_EXISTS' => 'Map Name already exists',
	'JS_SELECT_FILE_EXTENSION' => 'Please select a file with the following extension:',
	'JS_UPLOADED_FILE_SIZE_SHOULD_BE_LESS_THAN' => 'Upload file size should be less than',
	'JS_UPLOADED_FILE_SIZE_EXCEEDS' => 'Uploaded file size exceeds',
	'JS_PLEASE_SPLIT_FILE_AND_IMPORT_AGAIN' => 'Please split the file into smaller files and import again.',
	'JS_FIELD_MAPPED_MORE_THAN_ONCE' => 'Field mapped more than once',
	'JS_MAP_MANDATORY_FIELDS' => 'Please map mandatory fields',
	'JS_MAP_MERGE_CRITERIA_FIELDS' => 'Please map matching fields',
	'JS_PLEASE_ENTER_SOME_VALUE' => 'Please enter some value to search',
	'JS_VCF_FILE_IMPORT_WARNING' => 'You have selected a VCF file. Only Contacts can be imported from VCF file. To import this file, please initiate import from Contact module',
	'JS_ICS_FILE_IMPORT_WARNING' => 'You have selected a ICS file. Only Calendar can be imported from ICS file. To import this file, please initiate import from Calendar module',
	//Select2 elements validation message
	'JS_YOU_CAN_SELECT_ONLY'=> 'You can select only',
	'JS_ITEMS' => 'items',

	'JS_LBL_PERMISSION' => 'Permissions',
	'JS_CHECK_FILE_INTEGRITY' => 'Check File Integrity',
	'JS_DUPLICATE_RECORD' => 'Duplicate Record',

	//advance filter checkbox type condition values
	'JS_IS_ENABLED' => 'is enabled',
	'JS_IS_DISABLED' => 'is disabled',

	'JS_PLEASE_ENTER_SOME_TEXT_FOR_COMMENT' => 'Please enter some text for comment',
	'JS_LBL_COMMENT_VALUE_CANT_BE_EMPTY' => 'Comment value cannot be empty',
	'JS_REQUIRED_FIELD' => 'This field is required',
	'JS_CAN_NOT_REMOVE_DEFAULT_WIDGET' => 'Cannot remove Default Widget',
	'JS_SHOULD_BE_LESS_THAN_CURRENT_DATE' => 'should be less than Current Date',
	'JS_NO_CREATE_OR_NOT_QUICK_CREATE_ENABLED' => 'No create permissions or not enabled for quick create',

	//Image Action
	'LBL_IMAGE_DELETED_SUCCESSFULLY' => 'Image Deleted Successfully',
	'LBL_IMAGE_NOT_DELETED' => 'Image Not Deleted',
	'LBL_YES' => 'Yes',
	'LBL_NO' => 'No',
	'AM' => 'AM',
	'PM' => 'PM',
	'JS_ERROR' => 'Error',
	'JS_INFORMATION' => 'Information',
	'JS_DO_NOT_HAVE_AN_EMAIL_ID' => 'does not have an email address',
	'NONE_OF_THE_FIELD_VALUES_ARE_CHANGED_IN_MASS_EDIT' => 'None of the field values are changed in Mass Edit',

	//Notification messages for inventory module
	'JS_PLEASE_SELECT_AN_ACCOUNT_TO_COPY_ADDRESS' => 'Please select an Organization to copy address',
	'JS_PLEASE_SELECT_AN_CONTACT_TO_COPY_ADDRESS' => 'Please select a Contact to copy address',
	'JS_SELECTED_ACCOUNT_DOES_NOT_HAVE_AN_ADDRESS' => 'Selected Organization does not contain address to copy',
	'JS_SELECTED_CONTACT_DOES_NOT_HAVE_AN_ADDRESS' => 'Selected Contact does not contain address to copy',
	'JS_PLEASE_ENTER_PRIMARY_EMAIL_VALUE_TO_ENABLE_PORTAL_USER' => 'Please enter Primary email address to enable portal user',
	'JS_PRIMARY_EMAIL_FIELD_DOES_NOT_EXISTS' => 'Primary email field does not exist to enable portal user',

	//Tag Cloud validation messages
	'JS_PLEASE_ENTER_A_TAG' => 'Please enter a tag',
	'JS_TAG_NAME_ALREADY_EXIST' => 'Tag name already exist',
	'JS_MAX_TAG_LENGTH_EXCEEDS' => 'Tag length exceeds max size',

	'JS_NO_VIEW_PERMISSION_AFTER_SAVE'=> 'You will not have permissions to view this record after save. Would you like to continue?',
	'JS_NO_RECORDS_RELATED_TO_THIS_FILTER' => 'No Records Related to this List',

	// Calendar Reminder popup
	'JS_START_DATE_TIME' => 'Start Date & Time',
	'JS_END_DATE_TIME' => 'End Date & Time',
	'JS_POSTPONE' => 'Postpone',
	'JS_MESSAGE' => 'Message',

	'JS_NO_VIEW_PERMISSION_AFTER_SAVE'=> 'You will not have permissions to view this record after save. Would you like to continue?',

	//Settings page translations
	'JS_SUCCESSFULLY_PINNED' => 'Shortcut added successfully',
	'JS_SUCCESSFULLY_UNPINNED' => 'Shortcut removed successfully',
	'JS_SHORTCUT_ALREADY_ADDED' => 'This shortcut is already added',
	'JS_MESSAGE' => 'Message',
	'JS_MASS_EDIT_LIMIT' => 'Mass Edit operation can be done on 500 or less records at a time',

	//Module Manager
	'JS_MODULE_ENABLED' => 'Module Enabled',
	'JS_MODULE_DISABLED' => 'Module Disabled',

	//Crom tasks
	'JS_VALUE_SHOULD_NOT_BE_LESS_THAN' => 'Frequency of any cron job configured should not be less than',
	'JS_MINUTES' => 'mins',

	//PickList
	'JS_ITEM_RENAMED_SUCCESSFULLY' => 'Item Renamed Successfully',
	'JS_ITEM_ADDED_SUCCESSFULLY' => 'Item added Successfully',
	'JS_NO_ITEM_SELECTED' => 'No item Selected',
	'JS_MORE_THAN_ONE_ITEM_SELECTED' => 'More than one Item selected',
	'JS_ITEMS_DELETED_SUCCESSFULLY' => 'Items Deleted Successfully',
	'JS_DUPLICATE_ENTRIES_FOUND_FOR_THE_VALUE' => 'Duplicate entries found for the value',
	'JS_SELECT_RECORDS_TO_MERGE_FROM_SAME_GROUP' => 'You have to select the records in the same groups for merging',
	'JS_SELECT_ATLEAST_TWO_RECORD_FOR_MERGING' => 'Select atleast two records for merging',
	'JS_ALLOWED_TO_SELECT_MAX_OF_THREE_RECORDS' => 'You are allowed to select a maximum of three records',
	//Notification message for dashboard widget delete
	'JS_ARE_YOU_SURE_TO_DELETE_WIDGET' => 'Are you sure you want to delete widget - %s?',
	'JS_ARE_YOU_SURE_TO_DELETE_DASHBOARDTAB' => 'Are you sure you want to delete this dashboard tab - %s?',
	'JS_TABS_LIMIT_EXCEEDED' => 'Sorry! Can\'t add more than 10 tabs',
	'JS_DUPLICATE_ENTRIES_FOUND_FOR_THE_VALUE' => 'Duplicate entries found for the value',
	'JS_SELECT_RECORDS_TO_MERGE_FROM_SAME_GROUP' => 'You have to select the records in the same groups for merging',
	'JS_SELECT_ATLEAST_TWO_RECORD_FOR_MERGING' => 'Select atleast two records for merging',
	'JS_ALLOWED_TO_SELECT_MAX_OF_THREE_RECORDS' => 'You are allowed to select a maximum of three records',
	'JS_TOTAL_RECORDS' => 'Total records',
	'JS_PAGE_NOT_EXIST' => 'Page not exist',
	'JS_YOU_ARE_IN_PAGE_NUMBER' => 'You are in page number',

	//More currencies message
	'JS_PLEASE_ENABLE_BASE_CURRENCY_FOR_PRODUCT' => 'Please enable base currency for product',
	'JS_PLEASE_SELECT_BASE_CURRENCY_FOR_PRODUCT' => 'Please select base currency for product',
	'JS_BASE_CURRENCY_CHANGED_TO_DISABLE_CURRENCY' => 'Base Currency has to be changed to disable ',

	//Delete Records message
	'JS_RECORDS_ARE_GETTING_DELETED' => 'Records are getting deleted',
	'JS_RECORD_GETTING_DELETED' => 'Record getting deleted',
	'JS_NO_RESULTS_FOUND' => 'No Results Found',

	'JS_RECORDS TRANSFERRED SUCCESSFULLY' => 'Records ownership has been tranferred successfully',

	//TextSearch Language String
	'LBL_SEARCHING' => 'Searching in ',
	'JS_RECORDS_TRANSFERRED_SUCCESSFULLY' => 'Records ownership transferred successfully.',
	'JS_USER_DELETED_SUCCESSFULLY' => 'User deleted successfully.',

	'JS_MAX_RECORDS_LIMIT' => 'Maximum Records for Print is :',
	'JS_USER_EXISTS' => 'User Already Exists',
	'JS_REENTER_PASSWORDS' => 'Renter Passwords',
	'LBL_SIGN_IN_AS_USER'=>'Logging in as another user will terminate the current session. Are you sure want to continue?',
	'JS_REENTER_PASSWORDS' => 'Renter Passwords',
	'SINGLE_Vendors' => 'Vendor',

	//Feedback on removing old version
	'JS_PLEASE_GIVE_YOUR_FEEDBACK' => 'Please Fill your Feedback',
	'JS_PBX_CALL_FROM' => 'Call From',
	'JS_PBX_INCOMING_CALL' => 'Incoming Call',
	'JS_PBX_OUTGOING_SUCCESS'=>'Pick up the extension receiver to dial the number',
	'JS_PBX_OUTGOING_FAILURE'=>'Call Failed',
	'JS_PBX_FILL_ALL_FIELDS'=>'Please fill all the fields',
	'JS_PBX_CAMPAIGN_NAME' => 'Campaign Name',
	'JS_PBX_CAMPAIGN_NUMBER' => 'Campaign Number',
	'JS_MIN_SEARCH_KEY_LENGTH' => 'Search Key should have aleast 3 characters',
	'JS_NO_MATCH' => 'No Matching Records Found',
	'JS_PBX_OUTGOING_CALL' => 'Outgoing Call',
	'JS_PBX_CALL_TO' => 'Call To',
	'JS_REQUIRED' => 'Required',
	'JS_PHONE_NUMBER' => 'Phone Number',
	'JS_NO_CREATE_PERMISSION' => 'Call need to be answered before creating record',
	'HelpDesk' => 'Tickets',
	'Potentials' => 'Opportunities',
	'JS_CALL_NOT_ANSWERED_UPDATE_PERMISSION' => "Call need to be answered before linking record", 
	'JS_CALL_NOT_ANSWERED' => "Call need to be answered before performing the action",
	// ends
	'JS_NO_EDIT_PERMISSION' => 'You don\'t have the permission to edit this event',

	//Google Synchronization
	'SYNC_REMOVED_SUCCESSFULLY' => 'Google synchronization removed successfully.',
	'REMOVE_SYNCHRONIZATION_MESSAGE' => 'Clicking on this will remove existing Gmail authentication. It will not delete any records which are already synchronized.',
	'REMOVE_SYNCHRONIZATION' => 'Remove Synchronization',
	'FIELD_MAPPING' => 'Field Mapping',
	'LBL_SYNC_BUTTON' => 'Synchronize Now',
	'LBL_SYNCRONIZING' => 'Synchronizing....',
	'LBL_NOT_SYNCRONIZED' => 'You have not synchronized yet',
	'LBL_FIELD_MAPPING' => 'Field Mapping',

	'LBL_RESTORE_CONFIRMATION' => 'Are you sure you want to restore this user?',
	'LBL_DELETE_USER_PERMANENT_CONFIRMATION' => 'Once deleted this user cannot be restored back. Are you sure you want to delete this user permanently?',

	'LBL_LANGUAGE_LABEL_VALIDATION' => 'Label value cannot be empty. You must enter some value.',
	'JS_CHANGES_WILL_BE_LOST' => 'Your changes will be lost!',
	'JS_RECORD_DELETED' => 'Record deleted',
	'JS_NO_DELETE_PERMISSION' => 'No delete permission',
	'JS_CONFIRM_MARK_AS_HELD' => 'Are you sure you want to mark Event as Held?',
	'JS_CONFIRM_MARK_AS_COMPLETED' => 'Are you sure you want to mark Task as Completed?',
	'JS_TODO_MARKED_AS_COMPLETED' => 'Task marked as Completed',
	'JS_EVENT_MARKED_AS_HELD' => 'Event marked as Held',
	'JS_FUTURE_EVENT_CANNOT_BE_MARKED_AS_HELD' => 'Future event cannot be marked as Held',
	'JS_PERMISSION_DENIED' => 'Permission denied',
	'LBL_SMS_MAX_CHARACTERS_ALLOWED' => 'Maximum 160 characters are allowed for text message',
	'JS_VIEWNAME_ALERT' => 'Maximum 40 characters are allowed for list name',
	'JS_EXCEEDS_MAX_UPLOAD_SIZE' => 'Exceeded maximum upload size',
	'JS_FUTURE_EVENT_CANNOT_BE_HELD' => 'Cannot Be Held For Future',
	'LBL_WARNING' => 'Warning',
	'DELETE_USER_PERMANENT_WARNING' => 'Deleting a user permanently will transfer all records including comments and history to new user.',
	'JS_DECIMAL_SEPARATOR_AND_GROUPING_SEPARATOR_CANT_BE_SAME' => 'Decimal separator and Grouping separator cant be same',
	'JS_FUTURE_EVENT_CANNOT_BE_HELD' => 'Cannot Be Held For Future',
	'JS_CLOSE' => 'Close',

	// For Line Iteam Currency Symbol select while Import
	'JS_CURRENCY_TOOLTIP_CONTENT_TITLE' => 'Line Items Currency',
	'JS_CURRENCY_TOOLTIP_CONTENT_MESSAGE' => 'For importing Currency values in Line items, Vtiger will use this setting to identify the currency. Any currency values outside the line items tables, are assumed to be in User\'s preferred currency (selected in \'My Preferences\')',
	'LBL_CANT_SELECT_CONTACT_FROM_LEADS' => 'Cannot select related Contacts for Leads',
	'JS_TRY_LATER' => 'Please try later!',
	'JS_FILE_NAME' => 'File Name',
	'JS_EXTERNAL_FILE_URL' => 'File Url',
	'JS_PLEASE_SELECT_A_FILE' => 'Please select a file',
	// SMSNotifier Phone Format Warning
	'JS_PHONEFORMAT_ERROR' => 'Please check the phone number is in internatonal E.164 format with \'+\' prefix and the country code Ex +1 415 599 2671',

	// Leads and Potentials Field Mapping
	'JS_NONE' => 'None',
	'JS_IS_ALREADY_BEEN_MAPPED' => 'is already been mapped',
	'JS_CANT_MAP' => 'Cant map',
	'JS_WITH' => 'with',
	'JS_MAPPING_DELETED_SUCCESSFULLY' => 'Mapping Deleted Successfully',

	//JS Field Type Translation
	'JS_phone' => 'Phone',
	'JS_picklist' => 'Pick List',
	'JS_email' => 'Email',
	'JS_text' => 'String',
	'JS_currency' => 'Currency',
	'JS_multiSelectCombo' => 'Multi-Select Combo Box',
	'JS_time' => 'Time',
	'JS_textArea' => 'Text Area',
	'JS_url' => 'Url',
	'JS_string' => 'String',
	'JS_checkBox' => 'Check Box',
	'JS_date' => 'Date',
	'JS_decimal' => 'Decimal',
	'JS_percent' => 'Percent',
	'JS_skype' => 'Skype',
	'JS_None' => 'None',
	'JS_integer' => 'Integer',
	'JS_double' => 'Decimal',
	'JS_reference' => 'reference',
	'JS_image' => 'Image',

	// AutoFill Overwriting message
	'JS_OVERWRITE_AUTOFILL_MSG1' => 'Would you like to overwrite existing',
	'JS_OVERWRITE_AUTOFILL_MSG2' => 'with selected',

	//Demo Data Module Translatios
	'JS_ADD_DEMO_DATA_CONFIRMATION'=> 'Are you sure you want to add demo records to all modules?',
	'JS_ADD_DEMO_DATA_INFO'=> 'Demo records can be deleted by clicking the "Clear Demo Data" button.',
	'JS_CLEAR_DEMO_DATA_CONFIRMATION'=> 'Are you sure you want to clear demo data in all modules?',
	'JS_CLEAR_DEMO_DATA_INFO'=> 'Demo records can be added by clicking the "Add Demo Data" button.',
	'JS_DEMO_DATA_GETTING_POPULATED'=> 'Demo Data is being added, please wait...',
	'JS_DEMO_DATA_GETTING_CLEARED'=> 'Demo data is being cleared, please wait...',
	'JS_DEMO_DATA_ADDED' => 'Demo data added to all modules.',
	'JS_DEMO_DATA_CLEARED' => 'Demo data cleared from all modules.',
	'JS_HOME_DASH_BOARD_CLEAR_INFO'=>'Note: You can re-enable demo data from',
	'JS_SETTINGS_PATH'=>'Settings > Configuration > Configuration Editor.',
	'JS_PRINT' => 'Print',
	'JS_SAVE_AS_IMAGE' => 'Save As Image',
	'JS_DIRECTORY_IS_EMPTY' => 'Directory is empty',
	'JS_PLEASE_SELECT_AN_RELATED_TO_COPY_ADDRESS' => 'Please select a Lead / Contact Module to copy address',
	'SINGLE_Leads' => 'Lead',
	'JS_SELECTED_LEAD_DOES_NOT_HAVE_AN_ADDRESS' => 'Selected Lead does not contain address to copy',
	'JS_INVALID_EMAILS' => 'Invalid Emails',
	'JS_DIRECTORY_IS_EMPTY' => 'Directory is empty',
	'JS_NO_LINE_ITEM' =>'Line items cannot be empty.',
	'JS_INTERNAL_COMMENT' => 'Internal Comment',
	'JS_INTERNAL_COMMENT_INFO' => 'The comment will only be seen by CRM users, if the internal comment checkbox is enabled. To notify customers (through configurable workflows or customer portal) leave this checkbox disabled',

	'JS_NO_TAXES_EXISTS' => 'No taxes exist',
	'JS_CONFIRM_TAXES_AND_CHARGES_REPLACE' => 'Do you want to update tax & charge values corresponding to selected region?',
	'JS_PRINTTEMPLATEMODULE_DISABLED' => 'PrintTemplates module is disabled. Cannot perform the operation',
	'JS_SENT_FOR_SIGNATURE' => 'Sent for signature',
	'JS_FAILED_TO_SEND_FOR_SIGNATURE' => 'Failed to send for signing',
	'JS_SUITABLE_VTIGER_FIELD_NOT_AVAILABLE_FOR_MAPPING' => 'Suitable vtiger field not available for mapping',
	'JS_SAVED_SUCCESSFULLY' => 'Settings saved successfully',
	'phone' => 'Phone',
	'email' => 'Email',
	'url' => 'Url',
	'home' => 'Home',
	'work' => 'Work',
	'custom' => 'Custom',
	'mobile' => 'Mobile',
	'main' => 'Main',
	'work_fax' => 'Fax',
	'home_fax' => 'Home Fax',
	'pager' => 'Pager',
	'profile' => 'Profile',
	'blog' => 'Blog',
	'home-page' => 'Homepage',
	'address' => 'Address',

	// Cron
	'JS_NONE_OF_THE_VALUES_ARE_CHANGED' => 'None of the values are changed',
	'JS_REMOVE_SYNC_CONFIRMATION' => 'Remove synchronization will only remove existing authentication, it will not delete synchronized records. If you synchronize with same Google account again, duplicate records will be created. Are you sure you want to remove synchronization?',

	//Recipient preferences labels
	'JS_LBL_GETTING_RECIPIENT_PREFS' => 'Getting recipient preferences..',
	'JS_LBL_SAVING_PREFERENCES' => 'Saving preferences..',
	// Social Module Strings
	'JS_PLEASE_WAIT' => 'Please Wait...',
	'JS_SOCIAL_FIELD_ERROR' => 'field is required',
	// Twitter Specific
	'JS_ADD_FAVOURITE_SUCCESS_MSG' => 'Added Tweet to favourite list successfully',
	'JS_UNDO_FAVOURITE_SUCCESS_MSG' => 'Removed Tweet from favourite list successfully',
	'JS_UNDO_RETWEET_SUCCESS_MSG' => 'UndoRetweet successfully',
	'JS_STATUS_UPDATE_SUCCESS_MSG' => 'Updated successfully',
	'JS_TWEET_DELETE_MSG' => 'Status Deleted successfully',
	'JS_INVALID_TWITTER_HANDLER_NAME' => 'Invalid Twitter Username',
	'JS_RELATION_ADDED_SUCESSFULLY' => 'Relation Added Successfully',
	'JS_FAILED_TO_ADD_RELATION' => 'Failed To Add Relation',
	'JS_SOCIAL_POST_DELETE_CONFIRMATION' => 'Are you sure you want to delete?',
	'JS_EVENT_OR_TODO_ADDED_SUCCESS_MSG' => 'Event/Task added sucessfully',
	'JS_LEAD_ADDED_SUCCESS_MSG' => 'Lead added successfully',
	'JS_OPPORTUNITY_ADDED_SUCESS_MSG' => 'Opportunity added successfully',
	'JS_TICKET_ADDED_SUCESS_MSG' => 'Ticket added successfully',
	'JS_CASE_ADDED_SUCESS_MSG' => 'Case added successfully',
	'JS_SELECT_OPTION' => 'Select an Option',

	'JS_LOADING_PLEASE_WAIT' => 'Loading... Please wait..',
	'JS_SAVING_PLEASE_WAIT' => 'Saving.. Please wait..',
	'JS_DUPLICATE_EMAILS_PLEASE_CHECK' => 'Duplicate email addresses. Please check',
	'JS_USER_EXISTS' => 'User already exists',
	'JS_ALERT' => 'Alert',
	'JS_SUCCESS' => 'Success',
	'JS_REMOVE_MASS_TAG_WARNING' => 'Are you sure you want to remove %s tag for selected records',
	'JS_VIEW_ALREADY_EXISTS' => 'View already exists',
	'JS_PLEASE_ENTER_NUMBER_IN_RANGE' => 'Please enter value in the range',
	'JS_UPLOAD' => 'Upload',
	'JS_TODO_ADDED_SUCCESS_MSG' => 'Task added successfully',
	'JS_EVENT_ADDED_SUCCESS_MSG' => 'Event added successfully',
	'JS_ACTIVE' => 'Active',
	'JS_SNOOZED' => 'Snoozed',
	'JS_INVALID_URL' => 'Invalid URL',
	'JS_MAX_ALLOWED_CHARACTERS' => 'Maximum allowed characters is',
	'JS_ARE_YOU_SURE_YOU_WANT_TO_DELETE' => 'Are you sure you want to delete?',
	'JS_TAB_LABEL_EXCEEDS_CHARS' => 'Tab label length should be less than %s characters',
	'JS_STARRED' => 'Unfollow',
	'JS_NOT_STARRED' => 'Follow',
	//Tags
	'JS_NO_TAG_EXISTS' => 'No Tag Exists' ,
	//help wizard
	'JS_HELP_AND_SUPPORT' => 'Help & Support',
	'JS_WHAT_DO_YOU_NEED_HELP_WITH' => 'What do you need help with?',
	'JS_SUBMIT' => 'Submit',

	/** Vtiger7 translations **/
	'JS_ADD_MAX_15_ITEMS' => 'You can only add 15 items',
	'SINGLE_SLA' => 'SLA',

	'JS_DEFAULT_ENABLED' => 'Default enabled',
	'JS_DEFAULT_DISABLED' => 'Default disabled',
	'JS_EDIT_FIELDS' => '%s Fields & Layout',
	'JS_MORE_VTIGER' => 'There are more records to be synchronized in vtiger',
	'JS_MORE_GOOGLE' => 'There are more records to be synchronized in Google',
	'JS_MORE_OFFICE365' => 'There are more records to be synchronized in Office365',
	'JS_TOKEN_EXPIRED' => 'Office365 Authentication has expired. Click on Sign in with Office365 button to re-authorize.',
	'JS_EDIT_FIELDS' => '%s Fields & Layout',
	'JS_WISH_TO_PROCEED' =>"Are you sure you want to proceed?",
	'JS_SWITCH_TO_OLD_LOOK_CONFIRMATION_MESSAGE' => 'Some features, including notifications, picklist colors, follow record, are not available in old version. You may switch back to new version by choosing new version from top right menu.',
	'JS_PROCEED_OLD_VERSION' => 'Proceed to old version',
	'JS_STAY_WITH_NEW_VERSION' => 'Stay with new version',

	//TimeAgo plugin Strings
	'JS_AGO' => 'ago',
	'JS_FROM_NOW' => 'from now',
	'JS_LESSTHAN_A_MINUTE' => 'less than a minute',
	'JS_A_MINUTE' =>'a minute',
	'JS_MINUTES' => 'minutes',
	'JS_AN_HOUR' => 'an hour',
	'JS_HOURS' => 'hours',
	'JS_A_DAY' => 'a day',
	'JS_DAYS' => 'days',
	'JS_A_MONTH' => 'a month',
	'JS_MONTHS' => 'months',
	'JS_A_YEAR' => 'a year',
	'JS_YEARS' => 'years',
	'JS_TODAY' => 'today',
	'JS_TOMORROW' => 'tomorrow',
	'JS_YESTERDAY' => 'yesterday',

	'JS_CREATE_TASK' => 'Create Task',

	//Notifications
	'JS_MENTION_ATLEAST_ONE_USER' => 'Mention atleast one user',
	'JS_LOADING' => 'Loading...',
	'JS_CASE_ACCEPTED_SUCCESSFULLY' => 'Case accepted successfully',

	'JS_UPLOAD_SUCCESSFUL' => 'File Uploaded Successfuly',
	'JS_UPLOAD_FAILED' => 'File Upload Failed',
	'JS_FAILED_TO_UPLOAD_FILE' => 'Failed to upload file',
	'JS_DOCUMENT_CREATED' => 'Document created',
	'JS_DOCUMENT_CREATION_FAILED' => 'Document creation failed',

	'JS_TEMPLATE_TEXT_EXCEEDS_LIMIT' => 'The size of the template exceeds the maximum allowed size of 100 KB. Please remove some text in the template and retry',
	'JS_PLEASE_SELECT_IMAGE' => 'Please select an image',

	'JS_LBL_MY_PREFERENCES' => 'My Preferences',
	'JS_LBL_MY_PREFERENCES_TEXT' => 'Configure your personal preferences including Timezone, Currency, Date Format. You can also upload profile picture from My Preferences.',
	'JS_LBL_HELP' => 'Help',
	'JS_LBL_HELP_TEXT' => 'Click on Help button to find Guides and FAQs, and use the Help menu dropdown to get assistance from Vtiger support team',
	'JS_LBL_RESTART_TOUR' => 'Restart Guided Tour',
	'JS_LBL_RESTART_TOUR_TEXT' => 'Click here to start this tour again',
	'JS_GOOGLE_REMOVE_SYNC_CONFIRMATION' => 'Revoke access will only remove existing Google authentication for Contacts and Calendar, it will not delete synchronized records. If you synchronize with same Google account again, duplicate records will be created. Are you sure you want to revoke access?',
	'JS_OFFICE_REMOVE_SYNC_CONFIRMATION' => 'Revoke access will only remove existing Office365 authentication for Contacts, Calendar and Emails, it will not delete synchronized records. If you synchronize with same Office365 account again, duplicate records will be created. Are you sure you want to revoke access?',
	'JS_FOLLOW_RECORD' => 'Following the record',
	'JS_FOLLOWING' => 'Following',
	'JS_UNFOLLOW_RECORD' => 'Unfollowing the record',
	'JS_UNFOLLOWING' => 'Unfollowing',
	'JS_RECORD_CREATED' => 'Record created',
	'JS_RECORD_UPDATED' => 'Record updated',
	'JS_LIST_SAVED' => 'List saved',
	'JS_TAB_DELETED' => 'deleted',
	'JS_TAB_RENAMED' => 'Renamed',
	'JS_TAB_REORDERED' => 'Reordered',
	'JS_RECIPIENT_PREFERENCES_SAVED' => 'Recipient preferences saved',
	'JS_TASK_ADDED' => 'Task added',
	'JS_MARKED_COMPLETED' => 'Marked as completed',
	'JS_TASK_PRIORITY_CHANGED' => 'Task priority changed',
	'JS_NO_PERMISSION_TO_MARK_AS_HELD' => 'You do not have permission to mark this event as held',
	'JS_TAG_ADDED' => 'Tag added',
	'JS_TAB_DELETED' => 'deleted',
	'JS_TAB_RENAMED' => 'Renamed',
	'JS_TAB_REORDERED' =>'Reordered',
	//Convert Lead
	'JS_CONVERT_LEAD_ERROR' => 'You have to enable either Organizations or Contacts module to convert the Lead.',

	'JS_CHECK_START_AND_END_DATE'=>'End Date & Time should be greater than or equal to Start Date & Time',
	'JS_CHECK_START_AND_END_DATE_SHOULD_BE_GREATER'=> 'End Date & Time should be greater than Start Date & Time',
	'JS_HOLD_FOLLOW_UP_SHOULD_BE_LESS_THAN_CURRENT_DATE'=> 'Hold Followup on should be greater than or equal to Start Date & Time',
	'JS_DUPLICATES_DETECTED' => 'Duplicate(s) detected!',

	'JS_IS' => 'is',
	'JS_IS_NOT' => 'is not',
	'JS_EQUALS' => 'equals',
	'JS_NOT_EQUALS_TO' => 'not equal to',
	'JS_ONLY_LETTERS_AND_NUMBERS_ALLOWED' => 'Only letters (a-z), numbers (0-9), and spaces are allowed',
	'JS_WIDGET_RESIZING_WAIT_MSG' => 'Widget contents will load after resizing.',
	'JS_SLA_FULFILLMENT_RATE' => 'SLA FULFILLMENT RATE',
	'JS_TICKET_COUNT' => 'CASE COUNT',
	'JS_CASES_AGE_HOURS'=>'CASE AGE (Hours)',
	'JS_BACKLOG'=> 'Backlog',
	'JS_AND' => 'and',
	'JS_SEQUENCE_UPDATED_SUCCESSFULLY'=>'Sequence updated successfully',
	'JS_VIEW_RECORD' => 'View Record',
	'JS_HIDE'=>'Hide',
	'JS_SHOW_ALL'=>'Show all',
	'JS_SHOW_LESS' => 'Show less',
	'JS_SHOW_MORE' => 'Show more',

	'JS_KANBAN_ANCHORS_LIMIT_MESSAGE' => 'You can select upto 10 stages only', 
	'JS_KANBAN_NO_MORE_RECORDS' => 'No more records found',
	'JS_DELETED' => 'deleted',
	'JS_CLEAR_TEMPLATE_CONTENT_RECIPIENTS'=>'Changing the module will clear the template selected and recipients from TO field. Do you want to proceed?',
	'JS_WORKFLOW_ACTIONS_LIMIT_EXCEEDED' => 'Exceeded maximum limit of actions in this edition.',
	'JS_RECORD_CREATION_LIMIT_EXCEEDED' => 'Create Record - Exceeded maximum limit of this edition.',
	'JS_KANBAN_NO_ANCHORS_CONFIGURED' => "You do not have any sales stages defined for your Sales pipeline.",
	'JS_KANBAN_NO_ANCHORS_CONFIGURED_NON_ADMIN' => "You do not have any sales stages defined for your Sales pipeline. Please contact your Administrator to define sale stages as per your sales process.",
	'JS_UPDATE_MAPPING_CONFIRMATION' => 'There are some matching columns in CSV file which are not saved in this mapping. Do you want to update this mapping with new columns?',
	'JS_MAPPING_UPDATED' => 'New mapping updated.',
	'JS_MAILCHIMP_REMOVE_SYNC_CONFIRMATION' => 'Revoke access will remove existing MailChimp authentication, it will not delete synchronized records. Are you sure you want to revoke access?',
	'JS_WARNING' => 'Warning',
	'JS_CANT_SELECT_LEAD' => 'Cannot select related Lead',
	'JS_CANT_SELECT_CONTACT' => 'Cannot select related Contact',
	'JS_MSG_EMPTY_RB_CONFIRMATION' => 'Are you sure you want to permanently remove all the deleted records from your database?',
	'JS_LBL_RESTORE_RECORDS_CONFIRMATION' => 'Are you sure you want to restore the records?',
	'JS_COMMENT_POSTED_SUCCESSFULLY'=>'Comment posted successfully',
	'JS_SHARED_PUBLICLY_WITH'=>'Shared publicly with',
	'JS_SHARED_PRIVATELY_WITH'=>'Shared privately with',
	'JS_MAIL_SENT_SUCCESSFULLY'=>'Mail sent successfully',
	'JS_SHARED_PUBLICLY_TITLE'=>'Public Conversation can also be viewed by users outside the linked mailboxes, if they have access to the related Contact ,Opportunity ..etc',
	'JS_SHARED_PRIVATELY_TITLE'=>'Private Conversation can only be viewed by members of the mailboxes it is linked to.',
	'JS_LINKED_RECORDS_SUCCESS'=>'Linked records are successfully updated',
	'JS_MAIL_DRAFTED_SUCCESSFULLY'=>'Mail drafted successfully',

	//Custom view default sort translations.
	'JS_PLEASE_REMOVE_ONE_FIELD_FROM_CHOOSE_COLUMNS_LIST_TO_ADD_DEFAULT_SORT_FIELD' => 'Only 16 columns are allowed in a list view including sort columns.',
	'JS_DEFAULT_SORT_NOTIFY' => 'List is now sorted on default sort column ',
	'JS_ENABLED' => 'Enabled',
	'JS_DISABLED' => 'Disabled',
	'JS_ONLY_ALLOWED_USERS_ARE_ALLOWED_TO_DO_ACTION'=>'We could not mark the conversation(s) as unread/read/delete/done/private/public since you do not own it.',
	'JS_SHARED_WITH'=>'Shared with',
	'JS_DEFAULT_DASHBOARD_TOOLTIP' => 'Make this dashboard as default by reordering it as the first tab!',
	'JS_SET_DEFAULT_TAB' => 'is set as your default dashboard',
	'JS_PASSWORD_MISMATCH_ERROR' => 'Please re-enter passwords. The "new password" and "confirm password" values do not match.',
	'LBL_LIST_DELETE_CONFIRMATION' => 'Are you sure you want to delete?',
	'JS_WIDGET_RESIZING_WAIT_MSG' => 'Widget contents will load after resizing.',
);
