<?php

/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
    $languageStrings = array(
        'Map' => 'Map',
        'EXTENTIONNAME' => 'Google',
        'LBL_UPDATES_CRM' => 'Ενημερώσεις στο CRM',
        'LBL_UPDATES_GOOGLE' => 'Ενημερώσεις στη Google',
        'LBL_UPDATED' => 'Ενημερώθηκε',
        'LBL_ADDED' => 'Προστέθηκε',
        'LBL_DELETED' => 'Διαγράφηκε',
        'LBL_SYNCRONIZED' => 'Συγχρονίστηκε',
        'LBL_NOT_SYNCRONIZED' => 'Δεν έχετε συγχρονίσει ακόμα',
        'LBL_SYNC_BUTTON' => 'Συγχρόνισε Τώρα',
	'LBL_REMOVE_SYNC' => 'Αφαίρεση Συγχρονισμού',
        'LBL_MORE_VTIGER' => 'Υπάρχουν περισσότερες εγγραφές για συγχρονισμό στο vtiger',
        'LBL_MORE_GOOGLE' => 'Υπάρχουν περισσότερες εγγραφές για συγχρονισμό στη Google',
        'Contact Name'=>'Όνομα Επαφής',
        'Email'=>'Email',
        'Mobile Phone'=>'Κινητό',
        'Address' => 'Διεύθυνση',
        'Event Title'=>'Τίτλος Γεγονότος',
        'Start Date'=>'Ημερομηνία Έναρξης',
        'Until Date'=>'Μέχρι την Ημερομηνία',
        'Description'=>'Περιγραφή',
        'Office Phone' => 'Τηλέφωνο γραφείου',
        'Work Phone' => 'Τηλέφωνο εργασίας',
        'Home Phone' => 'Τηλέφωνο Οικίας',
        'SYNC_SETTINGS' => 'Ρυθμίσεις συγχρονισμού επαφών',
        'LBL_SELECT_GOOGLE_GROUP_TO_SYNC' => 'Επιλέξτε Ομάδα Google',
        'LBL_ADD_CUSTOM_FIELD_MAPPING' => 'Προσθέστε προσαρμοσμένη αντιστοίχηση',
        'LBL_EMAIL' => 'Email',
        'LBL_PHONE' => 'Τηλέφωνο',
        'LBL_URL' => 'Url',
        'LBL_CUSTOM' => 'προσαρμοσμένη',
        'LBL_SELECT_SYNC_DIRECTION' => 'Επιλέξτε κατεύθυνση συγχρονισμού',
        'LBL_BI_DIRECTIONAL_SYNC' => 'Συγχρονίστε αμφότερα',
        'LBL_ONLY_SYNC_FROM_GOOGLE_TO_VTIGER' => 'Από το Google μόνο στο Vtiger',
        'LBL_ONLY_SYNC_FROM_VTIGER_TO_GOOGLE' => 'Από το Vtiger μόνο στο Google',
        'Job Title' => 'Τίτλος εργασίας',
        'Company' => 'Εταιρεία',
        'Birthday' => 'Γενέθλια',
        'Phone' => 'Τηλέφωνο',
        'URL' => 'Url',
        'phone' => 'Τηλέφωνο',
        'email' => 'Email',
        'url' => 'Url',
        'home' => 'Σπίτι',
        'work' => 'Εργασία',
        'custom' => 'Προσαρμοσμένο',
        'mobile' => 'Κινητό',
        'main' => 'Κύριο',
        'work_fax' => 'Φαξ',
        'home_fax' => 'Φαξ οικίας',
        'pager' => 'Pager',
        'profile' => 'Προφίλ',
        'blog' => 'Blog',
        'home-page' => 'Ιστοσελίδα',
        'CALENDAR_SYNC_SETTINGS' => 'Ρυθμίσεις συγχρονισμού ημερολογίου',
        'LBL_SELECT_GOOGLE_CALENDAR_TO_SYNC' => 'Επιλέξτε Ημερολόγιο Google',
        'LBL_SAVE_AND_START_SYNC' => 'Αποθήκευση και έναρξη συγχρονισμού',
        'LBL_PRIMARY' => 'Πρωταρχικός',
        'LBL_SYNC_FROM_GOOGLE_TO_VTIGER' => 'Συγχρονισμός από το Google σε vtiger',
        'LBL_SYNC_FROM_VTIGER_TO_GOOGLE' => 'Συγχρονισμός από vtiger σε google',
        'LBL_GOOGLE_CONNECT_MSG' => 'Συνδεθείτε σε έναν λογαριασμό Google για να το λάβετε',
        'LBL_SIGN_IN_WITH_GOOGLE' => 'Συνδεθείτε με Google λογαριασμό',
        'LBL_GOOGLE_ACCOUNT_DETAILS' => 'Στοιχεία λογαριασμού Google',
        'LBL_GOOGLE_ACCOUNT_SYNCED_WITH' => 'Λογαριασμός Google συγχρονισμένος με',
        'LBL_CHANGE_USER' => 'Αλλαγή χρήστη',
        'LBL_SAVE_AND_IMPORT' => 'Αποθήκευση και εισαγωγή',
        'LBL_IMPORT_RESULTS_GOOGLE' => 'Τα αποτελέσματα εισαγωγής Google',
		'LBL_REDIRECT_URL' => 'url Ανακατεύθυνσης',
		'LBL_REDIRECT_URL_MESSAGE' => 'Αντιγράψτε την ακόλουθη διεύθυνση URL ανακατεύθυνσης και επικολλήστε το στο google auth σας όπως παρουσιάζεται στην εικόνα',
    );
    $jsLanguageStrings = array(
        'LBL_SYNC_BUTTON' => 'Συγχρόνισε Τώρα',
        'LBL_SYNCRONIZING' => 'Συγχρονίζει....',
        'LBL_NOT_SYNCRONIZE' => 'Δεν έχετε συγχρονίσει ακόμα',
    );
