<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'LBL_IMPORT_STEP_1' => 'Βήμα 1',
	'LBL_IMPORT_STEP_1_DESCRIPTION' => 'Επιλογή Αρχείου',
	'LBL_IMPORT_SUPPORTED_FILE_TYPES' => '	Υποστηριζόμενοι Τύποι Αρχείων: .CSV, .VCF',
	'LBL_IMPORT_STEP_2' => 'Βήμα 2',
	'LBL_IMPORT_STEP_2_DESCRIPTION' => 'Προσδιορίστε Μορφοποίηση',
	'LBL_FILE_TYPE' => 'Τύπος Αρχείου',
	'LBL_CHARACTER_ENCODING' => 'Κωδικοποίηση Χαρακτήρων',
	'LBL_DELIMITER' => 'Οριοθέτης',
	'LBL_HAS_HEADER' => 'Έχει Κεφαλίδες',
	'LBL_IMPORT_STEP_3' => 'Βήμα 3',
	'LBL_IMPORT_STEP_3_DESCRIPTION' => 'Διαχείριση Διπλότυπων Εγγραφών',
	'LBL_IMPORT_STEP_3_DESCRIPTION_DETAILED' => 'Διαλέξτε την επιλογή αυτήν για να ενεργοποιήσετε και να ρυθμίσετε τα κριτήρια συγχώνευσης διπλοτύπων',
	'LBL_SPECIFY_MERGE_TYPE' => 'Επιλέξτε πως θα διαχειριστείτε τις διπλότυπες εγγραφές',
	'LBL_SELECT_MERGE_FIELDS' => 'Επιλέξτε τα σχετιζόμενα πεδία που ταιριάζουν για να βρείτε τις διπλότυπες εγγραφές',
	'LBL_AVAILABLE_FIELDS' => 'Διαθέσιμα Πεδία',
	'LBL_SELECTED_FIELDS' => 'Πεδία που θα συσχετιστούν',
	'LBL_NEXT_BUTTON_LABEL' => 'Επόμενο',
	'LBL_IMPORT_STEP_4' => 'Βήμα 4',
	'LBL_IMPORT_STEP_4_DESCRIPTION' => 'Αντιστοιχίστε τις στήλες στα πεδία μιας ενότητας',
	'LBL_FILE_COLUMN_HEADER' => 'Κεφαλίδα',
	'LBL_ROW_1' => 'Σειρά 1',
	'LBL_CRM_FIELDS' => 'Πεδία CRM',
	'LBL_DEFAULT_VALUE' => 'Προεπιλεγμένη Τιμή',
	'LBL_SAVE_AS_CUSTOM_MAPPING' => 'Αποθήκευση ως προσαρμοσμένη αντιστοίχηση ',
	'LBL_IMPORT_BUTTON_LABEL' => 'Εισαγωγή',
	'LBL_RESULT' => 'Αποτέλεσμα',
	'LBL_TOTAL_RECORDS_IMPORTED' => 'Οι εγγραφές εισήχθησαν επιτυχώς',
	'LBL_NUMBER_OF_RECORDS_CREATED' => 'Δημιουργήθηκαν εγγραφές',
	'LBL_NUMBER_OF_RECORDS_UPDATED' => 'Εγγραφές που αντικαταστάθηκαν',
	'LBL_NUMBER_OF_RECORDS_SKIPPED' => 'Εγγραφές που αγνοήθηκαν',
	'LBL_NUMBER_OF_RECORDS_MERGED' => 'Εγγραφές που συγχωνεύτηκαν', 
	'LBL_TOTAL_RECORDS_FAILED' => 'Εγγραφές που απέτυχε η εισαγωγή τους',
	'LBL_IMPORT_MORE' => 'Εισαγωγή περισσοτέρων',
	'LBL_VIEW_LAST_IMPORTED_RECORDS' => 'Τελευταίες εισαγωγές εγγραφών',
	'LBL_UNDO_LAST_IMPORT' => 'Αναίρεση τελευταίας εισαγωγής',
	'LBL_FINISH_BUTTON_LABEL' => 'Τέλος',
	'LBL_UNDO_RESULT' => 'Αποτέλεσμα αναίρεσης εισαγωγής',
	'LBL_TOTAL_RECORDS' => 'Συνολικός αριθμός εγγραφών',
	'LBL_NUMBER_OF_RECORDS_DELETED' => 'Αριθμός διαγραμμένων εγγραφών',
	'LBL_OK_BUTTON_LABEL' => 'Ok',
	'LBL_IMPORT_SCHEDULED' => 'Προγραμματίστηκε εισαγωγή',
	'LBL_RUNNING' => 'Εκτελείται',
	'LBL_CANCEL_IMPORT' => 'Ακύρωση εισαγωγής',
	'LBL_ERROR' => 'Σφάλμα',
	'LBL_CLEAR_DATA' => 'Εκκαθάριση Δεδομένων',
	'ERR_LOCAL_INFILE_NOT_ON' => 'local_infile variable is turned off on the database server.',
	'ERR_UNIMPORTED_RECORDS_EXIST' => 'Δεν είναι δυνατή η εισαγωγή περισσότερων δεδομένων για τη συγκεκριμένη παρτίδα. Παρακαλούμε ξεκινήσετε μια νέα εισαγωγή.',
	'ERR_IMPORT_INTERRUPTED' => 'Η τρέχουσα εργασία εισαγωγής έχει διακοπεί. Παρακαλώ δοκιμάστε ξανά αργότερα',
	'ERR_FAILED_TO_LOCK_MODULE' => 'Απέτυχε το κλείδωμα της ενότητας για εισαγωγής. Δοκιμάστε ξανά αργότερα',
	'LBL_SELECT_SAVED_MAPPING' => 'Επιλέξτε αποθηκευμένη αντιστοίχιση',
	'LBL_IMPORT_ERROR_LARGE_FILE' => 'Σφάλμα Εισαγωγής Μεγάλο Αρχείο ',
	'LBL_FILE_UPLOAD_FAILED' => 'Απέτυχε η Μεταφόρτωση Αρχείου',
	'LBL_IMPORT_CHANGE_UPLOAD_SIZE' => 'Εισαγωγή Αλλαγή Μεγέθους Μεταφόρτωσης',
	'LBL_IMPORT_DIRECTORY_NOT_WRITABLE' => 'Φάκελος Εισαγωγής δεν είναι Εγγράψιμος',
	'LBL_IMPORT_FILE_COPY_FAILED' => 'Εισαγωγή Απέτυχε η αντιγραφή Αρχείου',
	'LBL_INVALID_FILE' => 'Μη έγκυρο αρχείο',
	'LBL_NO_ROWS_FOUND' => 'Δεν βρέθηκαν σειρές',
	'LBL_SCHEDULED_IMPORT_DETAILS' => 'Η Εισαγωγή σας έχει προγραμματιστεί και θα αρχίσει μέσα σε 15 λεπτά. Θα λάβετε ένα email μετά την αφού έχει ολοκληρωθεί εισαγωγή.  <br> <br>
										Παρακαλώ βεβαιωθείτε ότι ο διακομιστής εξερχόμενης αλληλογραφίας και η διεύθυνση email σας έχει ρυθμιστεί ώστε να λαμβάνετε ειδοποίηση με email',
	'LBL_DETAILS' => 'Λεπτομέρειες',
	'skipped' => 'Εγγραφές που αγνοήθηκαν',
	'failed' => 'Εγγραφές που απέτυχαν',
	
        'LBL_IMPORT_LINEITEMS_CURRENCY'=> 'Συνάλλαγμα (Για στοιχεία πεδίων γραμμής)',
        'LBL_USE_SAVED_MAPS'=>'Χρησιμοποιήστε Αποθηκευμένες αντιστοιχίσεις',
        'LBL_IMPORT_MAP_FIELDS'=>'Αντιστοιχίστε τις στήλες στα πεδία CRM',
        'LBL_UPLOAD_CSV'=>'Μεταφόρτωση αρχείου CSV', 
        'LBL_UPLOAD_VCF'=>'Μεταφόρτωση αρχείου VCF',
        'LBL_DUPLICATE_HANDLING'=>'Διαχείριση Διπλότυπων',
        'LBL_FIELD_MAPPING'=>'Αντιστοίχιση πεδίων',
        'LBL_IMPORT_FROM_CSV_FILE'=>'Εισαγωγή από αρχείο CSV',
        'LBL_SELECT_IMPORT_FILE_FORMAT'=>'Από πού θέλετε να εισάγετε;',
        'LBL_CSV_FILE'=>'Αρχείο CSV',
        'LBL_VCF_FILE'=>'Αρχείο VCF',
        'LBL_GOOGLE'=>'Google',
        'LBL_IMPORT_COMPLETED'=>'Η εισαγωγή ολοκληρώθηκε',
        'LBL_IMPORT_SUMMARY'=>'Περίληψη εισαγωγής',
        'LBL_DELETION_COMPLETED'=>'Η διαγραφή ολοκληρώθηκε',
        'LBL_TOTAL_RECORDS_SCANNED'=>'Συνολικές εγγραφές που έχουν σαρωθεί',
        'LBL_SKIP_BUTTON'=>'Αγνόηση',
    'LBL_DUPLICATE_RECORD_HANDLING' => 'Διαχείριση διπλότυπων εγγραφών',
    'LBL_IMPORT_FROM_VCF_FILE' => 'Εισαγωγή από αρχείο VCF',
    'LBL_SELECT_VCF_FILE' => 'Επιλέξτε αρχείο VCF',
    'LBL_DONE_BUTTON' => 'Εγινε',
    'LBL_DELETION_SUMMARY' => 'Σύνοψη διαγραφής',

	'LBL_SKIP_THIS_STEP' => 'Παραλείψτε αυτό το βήμα',
	'LBL_ICS_FILE'=>'Αρχείο ICS',
	'LBL_UPLOAD_ICS'=>'Μεταφόρτωση αρχείου ICS',
	'LBL_IMPORT_FROM_ICS_FILE'=>'Εισαγωγή από το αρχείο ICS',
	'LBL_SELECT_ICS_FILE' => 'Επιλέξτε αρχείο ICS',
);
