<?php
/* +***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 * *********************************************************************************** */

$languageStrings = array(
	'ERR_DATABASE_CONNECTION_FAILED' => 'Δεν είναι δυνατή η σύνδεση με διακομιστή βάσης δεδομένων',
	'ERR_DB_NOT_FOUND' => 'Αυτή η βάση δεδομένων δεν βρέθηκε. Δοκιμάστε να αλλάξετε τις ρυθμίσεις βάσης δεδομένων',
	'ERR_DB_NOT_UTF8'  => 'To charset ή collation της βάσης δεδομένων δεν είναι συμβατή με το UTF8',
	'ERR_INVALID_MYSQL_PARAMETERS' => 'Έχουν καθοριστεί μη έγκυρες παράμετροι σύνδεσης MySQL',
	'ERR_INVALID_MYSQL_VERSION' => 'Η έκδοση MySQL δεν υποστηρίζεται, συνδεθείτε με MySQL 5.1.x ή παραπάνω',
	'ERR_UNABLE_CREATE_DATABASE' => 'Δεν είναι δυνατή η δημιουργία βάσης δεδομένων',
	'ERR_DB_SQLMODE_NOTFRIENDLY' => 'Ο διακομιστής MySQL πρέπει να ρυθμιστεί με:<br> sql_mode = ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION',
	'LBL_ADMIN_INFORMATION'=>'Πληροφορίες Διαχειριστή',
	'LBL_ADMIN_USER_INFORMATION' => 'Πληροφορίες Διαχειριστή',
	'LBL_CHOOSE_LANGUAGE' => 'Επιλέξτε την προεπιλεγμένη γλώσσα για αυτήν την εγκατάσταση:',
	'LBL_CONFIRM_CONFIGURATION_SETTINGS' => 'Επιβεβαιώστε τις Ρυθμίσεις διαμόρφωσης',
	'LBL_CREATE_NEW_DB'=>'Δημιουργία νέας βάσης δεδομένων',
	'LBL_CURRENCIES'=>'Συνάλλαγμα',
	'LBL_CURRENCY' => 'Συνάλλαγμα',
	'LBL_DATABASE_INFORMATION' => 'Πληροφορίες βάσης δεδομένων',
	'LBL_DATABASE_TYPE' => 'Τύπος βάσης δεδομένων',
	'LBL_DATE_FORMAT'=>'Μορφή ημερομηνίας',
	'LBL_DB_NAME' => 'Ονομα βάσης δεδομένων',
	'LBL_DISAGREE' => 'Διαφωνώ',
	'LBL_EMAIL' => 'Email',
	'LBL_GD_LIBRARY' => 'Υποστήριξη Βιβλιοθήκης GD',
	'LBL_HOST_NAME' => 'Όνομα υπολογιστή φιλοξενίας',
	'LBL_I_AGREE' => 'Συμφωνώ',
	'LBL_IMAP_SUPPORT' => 'Υποστήριξη Imap',
	'LBL_INSTALLATION_IN_PROGRESS'=>'Εγκατάσταση σε εξέλιξη',
	'LBL_INSTALLATION_WIZARD' => 'Οδηγός εγκατάστασης',
	'LBL_INSTALL_BUTTON' => 'Εγκατάσταση',
	'LBL_INSTALL_PREREQUISITES' => 'Προϋποθέσεις εγκατάστασης',
	'LBL_MORE_INFORMATION' => 'Περισσότερες πληροφορίες',
	'LBL_NEXT' => 'Επόμενο',
	'LBL_ONE_LAST_THING' => 'Κάτι τελευταίο...',
	'LBL_PASSWORD_MISMATCH' => 'Καταχωρίστε ξανά τα συνθηματικά.  Το \"Συνθηματικό\" και η \"Επανάληψη Συνθηματικού\" δεν ταιριάζουν.',
	'LBL_PASSWORD' => 'Συνθηματικό',
	'LBL_PHP_CONFIGURATION' => 'Ρυθμίσεις PHP',
	'LBL_PHP_RECOMMENDED_SETTINGS'=>'Συνιστώμενες ρυθμίσεις PHP',
	'LBL_PHP_VERSION' => 'Έκδοση PHP',
	'LBL_PLEASE_WAIT'=>'Παρακαλώ περιμένετε',
	'LBL_PRESENT_VALUE' => 'Παρούσα τιμή',
	'LBL_READ_WRITE_ACCESS' => 'Πρόσβαση ανάγνωσης / εγγραφής',
	'LBL_RECHECK' => 'Ελέγξτε ξανά',
	'LBL_REQUIRED_VALUE' => 'Απαιτούμενη τιμή',
	'LBL_RETYPE_PASSWORD' => 'Επανάληψη Συνθηματικού',
	'LBL_ROOT_PASSWORD' => 'Συνθηματικό Root',
	'LBL_ROOT_USERNAME' => 'Όναμα χρήστη Root',
	'LBL_SYSTEM_CONFIGURATION' => 'Διαμόρφωση συστήματος',
	'LBL_SYSTEM_INFORMATION' => 'Πληροφορίες συστήματος',
	'LBL_TIME_ZONE' => 'Ζώνη ώρας',
	'LBL_TRUE' => 'Αληθές',
	'LBL_URL' => 'URL',
	'LBL_USERNAME' => 'Ονομα χρήστη',
	'LBL_VTIGER7_SETUP_WIZARD_DESCRIPTION' => 'Αυτός ο οδηγός θα σας καθοδηγήσει στην εγκατάσταση του Vtiger CRM7',
	'LBL_WELCOME_TO_VTIGER7_SETUP_WIZARD' => 'Καλώς ήρθατε στον Οδηγό εγκατάστασης του Vtiger CRM 7',
	'LBL_WELCOME' => 'Καλώς ήρθατε',
	'LBL_ZLIB_SUPPORT' => 'Υποστήριξη Zlib',
	'LBL_SIMPLEXML' => 'Υποστήριξη SimpleXML',
	'MSG_DB_PARAMETERS_INVALID' => 'ο συγκεκριμένος χρήστης της βάσης δεδομένων, το συνθηματικό, όνομα υπολογιστή φιλοξενίας, τύπος βάσης δεδομένων, ή το port είναι μή έγκυρο',
	'MSG_DB_ROOT_USER_NOT_AUTHORIZED' => 'Μήνυμα: ο Root χρήστης της βάση δεδομένων που έχετε ορίσει, δεν έχει άδεια για να δημιουργήσει τη βάση δεδομένων ή το όνομα βάσης δεδομένων έχει ειδικούς χαρακτήρες. Δοκιμάστε να αλλάξετε τις ρυθμίσεις της βάσης δεδομένων',
	'MSG_DB_USER_NOT_AUTHORIZED' => 'ο συγκεκριμένος χρήστης της βάσης δεδομένων δεν έχει πρόσβαση για να συνδεθείτε στο διακομιστή της βάσης δεδομένων από τον κεντρικό υπολογιστή',
	'MSG_LIST_REASONS' => 'Αυτό μπορεί να οφείλεται στους εξής λόγους',
	'LBL_MYSQLI_CONNECT_SUPPORT'=>'υποστήριξη mysqli',
	'LBL_OPEN_SSL'=>'υποστήριξη openssl',
	'LBL_CURL'=>'υποστήριξη cURL',
);
