<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'Reports'=>'Αναφορές',
	'SINGLE_Reports' => 'Αναφορά',

	// Basic Strings
	'LBL_FOLDER_NOT_EMPTY' => 'Ο φάκελος δεν είναι κενός',
	'LBL_MOVE_REPORT' => 'Μετακίνηση Αναφορών',
	'LBL_CUSTOMIZE' => 'Προσαρμογή',
	'LBL_REPORT_EXPORT_EXCEL' => 'Εξαγωγή σε Excel',
	'LBL_REPORT_PRINT' => 'Εκτύπωση',
	'LBL_CREATING_REPORT' => 'Δημιουργία αναφοράς',
	'LBL_EDITING_REPORT' => 'Επεξεργασία αναφοράς',
	'LBL_REPORT_DETAILS' => 'Λεπτομέρειες Αναφοράς',
	'LBL_SELECT_COLUMNS' => 'Επιλέξτε Στήλες',
	'LBL_FILTERS' => 'Φίλτρα',
	'LBL_FOLDERS' => 'Φάκελοι',
	'LBL_ADD_NEW_FOLDER' => 'Προσθήκη Νέου φακέλου',
	'LBL_FOLDER_NAME' => 'Όνομα Φακέλου',
	'LBL_FOLDER_DESCRIPTION' => 'Περιγραφή Φακέλου',
	'LBL_WRITE_YOUR_DESCRIPTION_HERE' => 'Εισαγωγή Περιγραφής',
	'LBL_DUPLICATES_EXIST' => 'Το Όνομα Αναφοράς υπάρχει ήδη',
	'LBL_FOLDERS_LIST' => 'Λίστα Φακέλων',
	'LBL_DENIED_REPORTS' => 'Απορριφθείσες Αναφορές',
	'LBL_NO_OF_RECORDS' => 'Αριθμός εγγραφών',
	'LBL_MORE_RECORDS_TXT'=>'Μόνο 500 εγγραφές εμφανίζονται παρακάτω. Παρακαλώ εξάγετε για να δείτε όλες τις εγγραφές',
	'LBL_SCHEDULE_REPORTS' => 'Προγραμματισμός αναφορών',
	'LBL_AT_TIME' => 'Κατά το χρόνο',

	'LBL_DAILY' => 'Καθημερινά',
	'LBL_WEEKLY' => 'Εβδομαδιαίος',
	'LBL_MONTHLY_BY_DATE' => 'Μηνιαία με ημερομηνία',
	'LBL_YEARLY' => 'Ετήσια',
	'LBL_SPECIFIC_DATE' => 'Σε συγκεκριμένη ημερομηνία',
	'LBL_CHOOSE_DATE' => 'Επιλέξτε Ημερομηνία',
	'LBL_ON_THESE_DAYS' => 'Σε αυτές τις μέρες',
	'LBL_SELECT_MONTH_AND_DAY' => 'Επιλέξτε Μήνα και Ημερομηνία',
	'LBL_SELECTED_DATES' => 'Επιλεγμένες ημερομηνίες',
	'LBL_EXCEEDING_MAXIMUM_LIMIT' => 'Υπέρβαση ανώτατου ορίου',
	'LBL_NEXT_TRIGGER_TIME' => 'Επόμενος χρόνος ενεργοποίησης',
	'LBL_RUN_REPORT' =>'Εκτέλεση αναφοράς',
	'LBL_SELECT_RECIEPIENTS' => 'Επιλέξτε Παραλήπτες',
	'LBL_SPECIFIC_EMAIL_ADDRESS' => 'Αποστολή σε συγκεκριμένο email',
	'LBL_SAME_LEVEL_ROLES' => 'Ρόλοι ίδιου επιπέδου',
	'LBL_SUBORDINATE_ROLES' => 'Ρόλοι χαμηλότερου επιπέδου',
	//ListView Actions
	'LBL_ADD_RECORD' => 'Προσθήκη Αναφοράς',
	'LBL_ADD_FOLDER' => 'Προσθήκη Φακέλου',
	'LBL_REPORT_DELETE_DENIED' => 'Άρνηση δικαιώματος διαγραφής της Αναφοράς',

	//Folder Actions
	'LBL_FOLDER_NOT_EMPTY' => 'Ο φάκελος δεν είναι κενός',
	'LBL_FOLDER_CAN_NOT_BE_DELETED' => 'Αυτός ο φάκελος δεν μπορεί να διαγραφεί',

	//Mass Actions
	'LBL_REPORTS_LIST' => 'Λίστα Αναφορών',

	//Step1 Strings
	'LBL_REPORT_NAME' => 'Όνομα Φακέλου',
	'LBL_REPORT_FOLDER' => 'Φάκελος Αναφοράς',
	'LBL_DESCRIPTION' => 'Περιγραφή',
	'PRIMARY_MODULE' => 'Κύρια Ενότητα',
	'LBL_SELECT_RELATED_MODULES' => 'Επιλέξτε Σχετικές Ενότητες',
	'LBL_MAX' => 'Μέγιστο',
	'LBL_NEXT' => 'Επόμενο',
	'LBL_REPORTS' => 'Λίστα Αναφορών',
	'LBL_SELECT_RELATED_MODULES' => 'Επιλέξτε Σχετικές Ενότητες',

	//Step2 Strings
	'LBL_GROUP_BY' => 'Ομαδοποίηση κατά',
	'LBL_SORT_ORDER' => 'Σειρά Ταξινόμησης',
	'LBL_ASCENDING' => 'Αύξουσα',
	'LBL_DESCENDING' => 'Φθίνουσα',
	'LBL_CALCULATIONS' =>'Υπολογισμοί',
	'LBL_COLUMNS' => 'Στήλες',
	'LBL_SUM_VALUE' => 'Άθροισμα',
	'LBL_AVERAGE' => 'Μέσος Όρος',
	'LBL_LOWEST_VALUE' => 'Χαμηλότερη Τιμή',
	'LBL_HIGHEST_VALUE' => 'Υψηλότερη τιμή',

	//Step3 Strings
	'LBL_GENERATE_REPORT' => 'Αποθήκευση και Δημιουργία Αναφοράς',

	//DetailView
	'LBL_SUM' => 'Αθρ.',
	'LBL_AVG' => 'Μεσ. Ορ',
	'LBL_MAX' => 'Μέγ',
	'LBL_MIN' => 'Ελάχ',
	'LBL_FIELD_NAMES' => 'Ονόματα Πεδίων',
	'LBL_REPORT_CSV' => 'Εξαγωγή CSV',
	'LBL_VIEW_DETAILS' => 'Εμφάνιση Λεπτομερειών',
	'LBL_GENERATE_NOW' => 'Δημιουργία τώρα',

	//List View Headers
	'Report Name' => 'Όνομα Αναφοράς',

	//Default Folders Names, Report Names and Description
	'Account and Contact Reports'=>'Αναφορές Εταιρειών και Πελτατών',
	'Lead Reports'=>'Αναφορές Δυνητικών',
	'Potential Reports'=>'Αναφορές Ευκαιριών',
	'Activity Reports'=>'Αναφορές Δραστηριοτήτων',
	'HelpDesk Reports'=>'Αναφορές Αιτημάτων',
	'Product Reports'=>'Αναφορές Προϊόντων',
	'Quote Reports'=>'Αναφορές Προσφορών',
	'PurchaseOrder Reports'=>'Αναφορές Εντολών Αγοράς',
	'SalesOrder Reports'=>'Αναφορές Παραγγελιών Πωλήσεων', //Added for SO
	'Invoice Reports'=>'Αναφορές Τιμολογίων',
	'Campaign Reports'=>'Αναφορές Καμπανιών', //Added for Campaigns
	'Contacts by Accounts'=>'Πελάτες ανά Εταιρείες',
	'Contacts without Accounts'=>'Πελάτες χωρίς Εταιρείες',
	'Contacts by Potentials'=>'Πελάτες ανά Ευκαιρίες',
	'Contacts related to Accounts'=>'Πελάτες σχετιζόμενοι με Εταιρείες',
	'Contacts not related to Accounts'=>'Πελάτες μη σχετιζόμενοι με Εταιρείες',
	'Contacts related to Potentials'=>'Πελάτες σχετιζόμενοι με Ευκαιρίες',
	'Lead by Source'=>'Δυνητικοί ανα Πηγή προέλευσης',
	'Lead Status Report'=>'Αναφορά Κατάστασης Δυνητικών',
	'Potential Pipeline'=>'Pipeline Ευκαιριών',
	'Closed Potentials'=>'Κλειστές Ευκαιρίες',
	'Potential that have Won'=>'Κερδισμένες Ευκαιρίες',
	'Tickets by Products'=>'Αιτήματα ανά Προϊόντα',
	'Tickets by Priority'=>'Αιτήματα ανά Προτεραιότητα',
	'Open Tickets'=>'Ανοιχτά Αιτήματα',
	'Tickets related to Products'=>'Αιτήματα σχετιζόμενα με Προϊόντα',
	'Tickets that are Open'=>'Αιτήματα που είναι ανοιχτά',
	'Product Details'=>'Λεπτομέρειες Προϊόντων',
	'Products by Contacts'=>'Προϊόντα ανα Πελάτες',
	'Product Detailed Report'=>'Λεπτομερείς Αναφορά Προϊόντος',
	'Products related to Contacts'=>'Προϊόντα σχετιζόμενα με Επαφές',
	'Open Quotes'=>'Ανοιχτές Προσφορές',
	'Quotes Detailed Report'=>'Λεπτομερείς Αναφορά Προσφορών',
	'Quotes that are Open'=>'Προσφορές που είναι ανοιχτές',
	'PurchaseOrder by Contacts'=>'Ενοτλές Αγορών ανα Πελάτη',
	'PurchaseOrder Detailed Report'=>'Λεπτομερείς Αναφορά Εντολών Αγοράς',
	'PurchaseOrder related to Contacts'=>'Εντολές Αγορών σχετιζόμενες με Πελάτες',
	'Invoice Detailed Report'=>'Λαπτομερείς Αναφορά Τιμολογίων',
	'Last Month Activities'=>'Δραστηριότητες Τελευταίου Μήνα',
	'This Month Activities'=>'Δραστηριότητες Αυτού του Μήνα',
	'Campaign Expectations and Actuals'=>'Προσδοκίες Καμπανιών και Πραγματικές', //Added for Campaigns
	'SalesOrder Detailed Report'=>'Λεπτομερείς Αναφορά Παραγγελίας Πωλήσεων', //Added for SO

	'Email Reports'=>'Αναφορές Email',
	'Contacts Email Report'=>'Αναφορά Email Πελατών',
	'Accounts Email Report'=>'Αναφορά Email Εταιρειών',
	'Leads Email Report'=>'Αναφορά Email Δυνητικών',
	'Vendors Email Report'=>'Αναφορά Email Προμηθευτών',

	'Emails sent to Contacts' => 'Απεσταλμένα Email σε Πελάτες',
	'Emails sent to Organizations' => 'Απεσταλμένα Email σε Εταιρείες',
	'Emails sent to Leads' => 'Απεσταλμένα Email σε Δυνητικούς',
	'Emails sent to Vendors' => 'Απεσταλμένα Email σε Προμηθευτές',

	'LBL_PRINT_REPORT' => 'Εκτύπωση αναφοράς',
	'LBL_RECORDS' => 'Εγγραφές',
	'LBL_LIMIT_EXCEEDED' => 'Μόνο 1000 + εγγραφές προβάλλονται. Χρησιμοποιείστε τις επιλογές CSV η Εξαγωγή σε Excel για να δείτε όλες τις εγγραφές',
	'LBL_TOP' => 'Κορυφαίες',
	'LBL_ALL_REPORTS' => 'Όλες οι Αναφορές',
	'LBL_CALCULATION_CONVERSION_MESSAGE' => 'Οι υπολογισμοί βασίζονται στο νόμισμα που ορίσατε στις Προτιμήσεις μου του CRM σας',

	//Summary/Pivot Reports
	'LBL_CREATING_PIVOT_REPORT' => 'Δημιουργία αναφοράς Συγκεντρωτικού Πίνακα',
	'LBL_EDITING_PIVOT_REPORT' => 'Επεξεργασία αναφοράς Συγκεντρωτικού Πίνακα',
	'LBL_SELECT_PIVOT_FIELDS' => 'Επιλέξτε πεδία Συγκεντρωτικού Πίνακα',
	'LBL_SELECT_ROWS' => 'Επιλέξτε Γραμμές ',
	'LBL_SELECT_DATA_FIELDS' => 'Επιλέξτε Πεδία Δεδομένων ',
	'LBL_ADD_ROWS' => 'Προσθήκη γραμμών',
	'LBL_ADD_COLUMNS' => 'Προσθέστε στήλες',
	'LBL_ADD_DATA_FIELDS' => 'Προσθήκη Πεδίων Δεδομένων',
	'LBL_PIVOT_FIELDS' => 'Επιλεγμένα πεδία Συγκεντρωτικού Πίνακα',
	'LBL_RECORD_COUNT' => 'Καταμέτρηση εγγραφών',
	'LBL_SELECT_PIVOT_FIELDS_WARNING' => 'Προειδοποίηση: Επιλέξτε τουλάχιστον ένα πεδίο γραμμής, πεδίο στήλης και πεδίο δεδομένων.',
	'LBL_PIVOT_DATA_FIELDS_WARNING' => 'Προειδοποίηση: Στη στήλη δεδομένων - οι συναρτήσεις συναθροίσεων (άθροισμα, μέση τιμή, ελάχιστο και μέγιστο) δεν πρέπει να επαναλαμβάνονται.',
	'LBL_MODIFY_CONDITIONS' => 'Τροποποίηση συνθηκών',
	'LBL_PIVOT_PREVIEW_EX' => 'Προεπισκόπηση αναφοράς Συγκεντρωτικού Πίνακα (παράδειγμα)',

	//charts labels
	'LBL_SELECT_CHART_TYPE' => 'Επιλέξτε τύπο γραφήματος',
	'LBL_CLICK_THROUGH_NOT_AVAILABLE' => 'Το κλικ δεν είναι διαθέσιμο καθώς έχετε επιλέξει περισσότερες από μία ενότητες',
	'LBL_TOTAL_SUM_OF' => 'Συνολικό άθροισμα %s',
	'LBL_AVG_OF' => 'Μέσος όρος %s',
	'LBL_MIN_OF' => 'Ελάχιστος %s',
	'LBL_MAX_OF' => 'Μέγιστος %s',
	'LBL_RECORD_COUNT' => 'Καταμέτρηση εγγραφών',
	'LBL_PIE_CHART' => 'Γράφημα πίτας',
	'LBL_VERTICAL_BAR_CHART' => 'Κάθετο γράφημα ράβδων',
	'LBL_HORIZONTAL_BAR_CHART' => 'Οριζόντιο γράφημα ράβδων',
	'LBL_LINE_CHART' => 'Γράφημα γραμμής',
	'LBL_SELECT_CHART' => 'Επιλέξτε Γράφημα',
	'LBL_CREATING_CHART_REPORT' => 'Δημιουργία αναφοράς γραφήματος',
	'LBL_EDITING_CHART_REPORT' => 'Επεξεργασία αναφοράς γραφήματος',
	'LBL_GENERATE_CHART' => 'Δημιουργία γραφήματος',
	'LBL_SELECT_GROUP_BY_FIELD' => 'Επιλέξτε Ομάδα ανα πεδίο',
	'LBL_SELECT_DATA_FIELD' => 'Επιλέξτε Πεδία δεδομένων',
	'LBL_MODIFY_CONDITION' => 'Τροποποίηση συνθηκών',
	'LBL_PLEASE_SELECT_ATLEAST_ONE_GROUP_FIELD_AND_DATA_FIELD' => 'Επιλέξτε τουλάχιστον μια Ομάδα ανα πεδίο και ένα πεδίο Δεδομένων.',
	'LBL_FOR_BAR_GRAPH_AND_LINE_GRAPH_SELECT_3_MAX_DATA_FIELDS' => 'Για γραφήματα στηλών και γραμμών, μπορείτε να επιλέξετε έως και 3 πεδία δεδομένων.',
	'LBL_DETAIL_REPORT' => 'Λεπτομερής αναφορά',
	'LBL_PIVOT_REPORT' => 'Αναφορά Συγκεντρωτικού Πίνακα',
	'LBL_CHARTS' => 'Γραφήματα',
	//Schedule Reports - Mail Content
	'LBL_AUTO_GENERATED_REPORT_EMAIL' => 'Αυτό είναι ένα αυτοματοποιημένο email που δημιουργήθηκε απο προγραμματισμένη αναφορά.',
	'LBL_PIN_CHART_TO_DASHBOARD' => 'Καρφιτσώστε το γράφημα στον Πίνακα Ελέγχου',
	'LBL_FILE_FORMAT' => 'Μορφή αρχείου',

	'Report Type' => 'Τύπος αναφοράς',
	'tabular' => 'Λεπτομέρεια',
	'summary' => 'Πινακοειδής',
	'pivot' => 'Συγκεντρωτικός',
	'chart' => 'Γράφημα',

	'LBL_REPORTS_MOVED_SUCCESSFULLY'=>'Οι αναφορές μεταφέρθηκαν με επιτυχία.',
	'LBL_SAME_SOURCE_AND_TARGET_FOLDER'=>'Ο φάκελος προορισμού είναι ο ίδιος με τον φάκελο πηγής.',
	'LBL_SHARE_REPORT' => 'Διαμοιρασμός Αναφοράς',
	'LBL_SHARED_REPORTS' => 'Μοιράστηκε μαζί μου',
	'LBL_PINNED' => 'Καρφιτσωμένο',
	'LBL_UNPINNED' => 'Ξεκαρφιτσωμένο',
	'LBL_SEARCH_FOR_FOLDERS' => 'Αναζήτηση για φακέλους',
	'LBL_CHART_REPORT' => 'Αναφορά γραφημάτων',
	'LBL_UNPIN_CHART_FROM_DASHBOARD' => 'Ξεκαρφιτσώστε το γράφημα από τον πίνακα ελέγχου',
	'LBL_REPORTS_DELETED_SUCCESSFULLY' => 'Οι αναφορές διαγράφηκαν με επιτυχία',
);
$jsLanguageStrings = array(
	'JS_DUPLICATE_RECORD' => 'Διπλότυπη αναφορά',
	'JS_CALCULATION_LINE_ITEM_FIELDS_SELECTION_LIMITATION' => 'Περιορισμός: Τα πεδία του στοιχείου γραμμής (Λίστα Τιμής, Έκπτωση και Ποσότητα) μπορούν να χρησιμοποιηθούν μόνο όταν δεν έχουν επιλεγεί άλλα πεδία υπολογισμών.',
	'JS_NO_CHART_DATA_AVAILABLE' => 'Τα δεδομένα δεν είναι διαθέσιμα, ελέγξτε τα επιλεγμένα πεδία',
	'JS_CHART_PINNED_TO_DASHBOARD' => 'Το γράφημα καρφιτσώθηκε στον Πίνακα Ελέγχου',
	'JS_CHART_ALREADY_PINNED_TO_DASHBOARD' => 'Το γράφημα έχει ήδη καρφιτσωθεί στον Πίνακα Ελέγχου',
	'JS_MOVE_REPORTS'=>'Μετακίνηση αναφορών',
	'JS_SCHEDULED_DATE_TIME_ERROR' => 'Η προγραμματισμένη ημερομηνία και ώρα πρέπει να είναι μεγαλύτερη από την τρέχουσα ημερομηνία και ώρα',
	'JSLBL_PIN_CHART_TO_DASHBOARD' => 'Καρφιτσώστε το γράφημα στον Πίνακα Ελέγχου',
	'JSLBL_UNPIN_CHART_FROM_DASHBOARD' => 'Ξεκαρφιτσώστε το γράφημα από τον πίνακα ελέγχου',
	'JS_CHART_REMOVED_FROM_DASHBOARD' => 'Το γράφημα αφαιρέθηκε από τον πίνακα ελέγχου',
);
