<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'LBL_ADD_RECORD' => 'Προσθήκη Χρήστη',

	//MyPreference Blocks
	'LBL_MY_PREFERENCES'  =>  'Οι Προτιμήσεις Μου',
	'LBL_MORE_INFORMATION'  =>  'Περισσότερες Πληροφορίες',
	'LBL_USERLOGIN_ROLE'  =>  'Είσοδος χρήστη & Ρόλος',
	'LBL_USER_IMAGE_INFORMATION' => 'Φωτογραφία Χρήστη',
	'LBL_CURRENCY_CONFIGURATION' =>  'Διαμόρφωση Πεδίων Συναλλάγματος και Αριθμών',
	'LBL_ADDRESS_INFORMATION' => 'Διεύθυνση Χρήστη',
	'LBL_USER_ADV_OPTIONS' => 'Προχωρημένες Ρυθμίσεις Χρήστη',
	'Asterisk Configuration'  =>  'Διαμόρφωση Asterisk',
	'LBL_HOME_PAGE_COMPONENTS' => 'Στοιχεία Αρχικής Σελίδας',
	'LBL_TAG_CLOUD_DISPLAY' => 'Εμφάνιση Ετικετοσύννεφο',

	//MyPreference Fields
	'Role' => 'Ρόλος',
	'Admin' => 'Διαχειριστής',
	'User Name' => 'Όνομα Χρήστη',
	'Default Activity View' => 'Προεπιλεγμένη προβολή Δραστηριότητας',
	'Default Calendar View' => 'Προεπιλεγμένη προβολή Ημερολογίου',
	'Default Lead View' => 'Προεπιλεγμένη Προβολή Δυνητικού',
	'Title' => 'Τίτλος',
	'Office Phone' => 'Τηλέφωνο Γραφείου',
	'Department' => 'Τμήμα',
	'Reports To' => 'Αναφέρετε στον',
	'Yahoo id' => 'Yahoo',
	'Home Phone' => 'Τηλ.Οικίας',
	'User Image' => 'Φωτογραφία Χρήστη',
	'Date Format' => 'Μορφη Ημερομηνίας',
	'Tag Cloud' => 'Ετικετοσύννεφο',
	'Signature' => 'Υπογραφή',
	'Street Address' => 'Διεύθυνση',
	'Password' => 'Συνθηματικό',
	'Confirm Password' => 'Επιβεβαίωση Συνθηματικό',
	'LBL_SHOWN' => 'Εμφανής',
	'LBL_HIDDEN' => 'Κρυμμένο',
	'LBL_SHOW' => 'Εμφάνισε',
	'LBL_HIDE' => 'Κρύψε',
	'LBL_HOME_PAGE_COMPO' => 'Στοιχεία Αρχικής Σελίδας',
	'LBL_LOGIN_HISTORY' => 'Ιστορικό Σύνδεσης',
	'LBL_USERDETAIL_INFO' => 'Προβολή των στοιχείων του χρήστη',
	'LBL_DELETE_GROUP' => 'Διαγραφή Ομάδας',
	'LBL_DELETE_GROUPNAME' => 'Η Ομάδα που Πρόκειται να Διαγραφεί',
	'LBL_TRANSFER_GROUP' => 'Μεταφορά κυριότητας σε/στον: ',
	'LBL_DELETE_USER' => 'Ο Χρήστης που Πρόκειται να Διαγραφεί',
	'LBL_REMOVE_USER' => 'Διαγραφή',
	'LBL_MORE_OPTIONS' => 'Περισσότερες επιλογές',
	'LBL_TRANSFER_USER' => 'Μεταφορά κυριότητας στον Χρήστη',
	'LBL_RESTORE_USER' => 'Επαναφορά Χρήστη',
	'LBL_DELETE_PROFILE' => 'Διαγραφή Προφίλ',
	'LBL_TRANSFER_ROLES_TO_PROFILE' => 'Μεταφορά Ρόλων στο Προφίλ',
	'LBL_PROFILE_TO_BE_DELETED' => 'Το Προφίλ που Πρόκειται να Διαγραφεί',
	'INTERNAL_MAIL_COMPOSER' => 'Εσωτερική Σύνταξη Email',
	'Asterisk Extension'  =>  'Επέκταση Asterisk',
	' Receive Incoming Calls'  =>  'Λήψη εισερχόμενων κλήσεων',
	'Webservice Access Key' => 'Κλειδάριθμος Διαδικτυακής Υπηρεσίας',
	'Language' => 'Γλώσσα',
	'Theme' =>  'Εμφάνιση',
	'Time Zone'  =>  'Ζώνη Ώρας',
	'Decimal Separator'  =>  'Δεκαδικός Διαχωριστής',
	'Digit Grouping Pattern'  =>  'Πρότυπο Ομαδοποίησης Ψηφίου',
	'Digit Grouping Separator'  =>  'Διαχωριστικό Ομαδοποίησης Ψηφίου',
	'Symbol Placement'  =>  'Τοποθέτηση Συμβόλου',
	'Number Of Currency Decimals'  =>  'Αριθμός Δεκαδικών συναλλάγματος',
	'Truncate Trailing Zeros'  =>   'Περικόψτε μηδενικά',
	'Default Call Duration' => 'Προεπιλεγμένη Διάρκεια Κλήσεων (Λεπτά)',
	'Other Event Duration' => 'Διάρκεια Άλλων Συμβάντων (Λεπτά)',
	'Calendar Hour Format' => 'Μορφή Ώρας Ημερολογίου',
	'Tag Cloud' => 'Ετικετοσύννεφο',

	//Time zones-Dont change any value
	'Kwajalein'  =>  '(UTC-12:00) International Date Line West',
	'Pacific/Midway'  =>  '(UTC-11:00) Coordinated Universal Time-11',
	'Pacific/Samoa'  =>  '(UTC-11:00) Samoa',
	'Pacific/Honolulu'  =>  '(UTC-10:00) Hawaii',
	'America/Anchorage'  =>  '(UTC-09:00) Alaska',
	'America/Los_Angeles'  =>  '(UTC-08:00) Pacific Time (US &amp; Canada)',
	'America/Tijuana'  =>  '(UTC-08:00) Tijuana, Baja California',
	'America/Denver'  =>  '(UTC-07:00) Mountain Time (US &amp; Canada)',
	'America/Chihuahua'  =>  '(UTC-07:00) Chihuahua, La Paz, Mazatlan',
	'America/Mazatlan'  =>  '(UTC-07:00) Mazatlan',
	'America/Phoenix'  =>  '(UTC-07:00) Arizona',
	'America/Regina'  =>  '(UTC-06:00) Saskatchewan',
	'America/Tegucigalpa'  =>  '(UTC-06:00) Central America',
	'America/Chicago'  =>  '(UTC-06:00) Central Time (US &amp; Canada)',
	'America/Mexico_City'  =>  '(UTC-06:00) Mexico City',
	'America/Monterrey'  =>  '(UTC-06:00) Monterrey',
	'America/New_York'  =>  '(UTC-05:00) Eastern Time (US &amp; Canada)',
	'America/Bogota'  =>  '(UTC-05:00) Bogota, Lima, Quito',
	'America/Lima'  =>  '(UTC-05:00) Lima',
	'America/Rio_Branco'  =>  '(UTC-05:00) Rio Branco',
	'America/Indiana/Indianapolis'  =>  '(UTC-05:00) Indiana (East)',
	'America/Caracas'  =>  '(UTC-04:30) Caracas',
	'America/Halifax'  =>  '(UTC-04:00) Atlantic Time (Canada)',
	'America/Manaus'  =>  '(UTC-04:00) Manaus',
	'America/Santiago'  =>  '(UTC-04:00) Santiago',
	'America/La_Paz'  =>  '(UTC-04:00) La Paz',
	'America/Cuiaba'  =>  '(UTC-04:00) Cuiaba',
	'America/Asuncion'  =>  '(UTC-04:00) Asuncion',
	'America/St_Johns'  =>  '(UTC-03:30) Newfoundland',
	'America/Argentina/Buenos_Aires'  =>  '(UTC-03:00) Buenos Aires',
	'America/Sao_Paulo'  =>  '(UTC-03:00) Brasilia',
	'America/Godthab'  =>  '(UTC-03:00) Greenland',
	'America/Montevideo'  =>  '(UTC-03:00) Montevideo',
	'Atlantic/South_Georgia'  =>  '(UTC-02:00) Mid-Atlantic',
	'Atlantic/Azores'  =>  '(UTC-01:00) Azores',
	'Atlantic/Cape_Verde'  =>  '(UTC-01:00) Cape Verde Is.',
	'Europe/London'  =>  '(UTC) London, Edinburgh, Dublin, Lisbon',
	'UTC'  =>  '(UTC) Coordinated Universal Time, Greenwich Mean Time',
	'Africa/Monrovia'  =>  '(UTC) Monrovia, Reykjavik',
	'Africa/Casablanca'  =>  '(UTC) Casablanca',
	'Europe/Belgrade'  =>  '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',
	'Europe/Sarajevo'  =>  '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb',
	'Europe/Brussels'  =>  '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris',
	'Africa/Algiers'  =>  '(UTC+01:00) West Central Africa',
	'Europe/Amsterdam'  =>  '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
	'Europe/Minsk'  =>  '(UTC+02:00) Minsk',
	'Africa/Cairo'  =>  '(UTC+02:00) Cairo',
	'Europe/Helsinki'  =>  '(UTC+02:00) Helsinki, Riga, Sofia, Tallinn, Vilnius',
	'Europe/Athens'  =>  '(UTC+02:00) Athens, Bucharest',
	'Europe/Istanbul'  =>  '(UTC+02:00) Istanbul',
	'Asia/Jerusalem'  =>  '(UTC+02:00) Jerusalem',
	'Asia/Amman'  =>  '(UTC+02:00) Amman',
	'Asia/Beirut'  =>  '(UTC+02:00) Beirut',
	'Africa/Windhoek'  =>  '(UTC+02:00) Windhoek',
	'Africa/Harare'  =>  '(UTC+02:00) Harare',
	'Asia/Kuwait'  =>  '(UTC+03:00) Kuwait, Riyadh',
	'Asia/Baghdad'  =>  '(UTC+03:00) Baghdad',
	'Africa/Nairobi'  =>  '(UTC+03:00) Nairobi',
	'Europe/Moscow'  =>  '(UTC+03:00) Moscow, Volgograd',
	'Asia/Tehran'  =>  '(UTC+03:30) Tehran',
	'Asia/Tbilisi'  =>  '(UTC+04:00) Tbilisi',
	'Asia/Muscat'  =>  '(UTC+04:00) Abu Dhabi, Muscat',
	'Asia/Baku'  =>  '(UTC+04:00) Baku',
	'Asia/Yerevan'  =>  '(UTC+04:00) Yerevan',
	'Asia/Karachi'  =>  '(UTC+05:00) Islamabad, Karachi',
	'Asia/Tashkent'  =>  '(UTC+05:00) Tashkent',
	'Asia/Kolkata'  =>  '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi',
	'Asia/Colombo'  =>  '(UTC+05:30) Sri Jayawardenepura',
	'Asia/Katmandu'  =>  '(UTC+05:45) Kathmandu',
	'Asia/Dhaka'  =>  '(UTC+06:00) Dhaka',
	'Asia/Almaty'  =>  '(UTC+06:00) Almaty',
	'Asia/Yekaterinburg'  =>  '(UTC+06:00) Ekaterinburg',
	'Asia/Rangoon'  =>  '(UTC+06:30) Yangon (Rangoon)',
	'Asia/Novosibirsk'  =>  '(UTC+07:00) Novosibirsk',
	'Asia/Bangkok'  =>  '(UTC+07:00) Bangkok, Jakarta',
	'Asia/Brunei'  =>  '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi',
	'Asia/Krasnoyarsk'  =>  '(UTC+08:00) Krasnoyarsk',
	'Asia/Ulaanbaatar'  =>  '(UTC+08:00) Ulaan Bataar',
	'Asia/Kuala_Lumpur'  =>  '(UTC+08:00) Kuala Lumpur, Singapore',
	'Asia/Taipei'  =>  '(UTC+08:00) Taipei',
	'Australia/Perth'  =>  '(UTC+08:00) Perth',
	'Asia/Irkutsk'  =>  '(UTC+09:00) Irkutsk',
	'Asia/Seoul'  =>  '(UTC+09:00) Seoul',
	'Asia/Tokyo'  =>  '(UTC+09:00) Tokyo',
	'Australia/Darwin'  =>  '(UTC+09:30) Darwin',
	'Australia/Adelaide'  =>  '(UTC+09:30) Adelaide',
	'Australia/Canberra'  =>  '(UTC+10:00) Canberra, Melbourne, Sydney',
	'Australia/Brisbane'  =>  '(UTC+10:00) Brisbane',
	'Australia/Hobart'  =>  '(UTC+10:00) Hobart',
	'Asia/Vladivostok'  =>  '(UTC+10:00) Vladivostok',
	'Pacific/Guam'  =>  '(UTC+10:00) Guam, Port Moresby',
	'Asia/Yakutsk'  =>  '(UTC+10:00) Yakutsk',
	'Etc/GMT-11' => '(UTC+11:00) Solomon Is., New Caledonia',
	'Pacific/Fiji'  =>  '(UTC+12:00) Fiji',
	'Asia/Kamchatka'  =>  '(UTC+12:00) Kamchatka',
	'Pacific/Auckland'  =>  '(UTC+12:00) Auckland',
	'Asia/Magadan'  =>  '(UTC+12:00) Magadan',
	'Pacific/Tongatapu'  =>  '(UTC+13:00) Nukualofa',

	'Summary' => 'Σύνοψη',
	'Detail' => 'Λεπτομέρης',
	'LBL_USER_LIST_DETAILS' => 'Λεπτομέρειες',

	'LBL_OLD_PASSWORD' => 'Παλιό Συνθηματικό',
	'LBL_CHANGE_PASSWORD' => 'Αλλαγή Συνθηματικού',
	'LBL_NEW_PASSWORD' => 'Νέο Συνθηματικό',
	'LBL_CONFIRM_PASSWORD' => 'Επιβεβαίωση Συνθηματικού',

	'LBL_CHANGE_ACCESS_KEY' => 'Αλλαγή Κλειδάριθμου',
	'LBL_ACCESS_KEY_UPDATED_SUCCESSFULLY' => 'Ο Κλειδάριθμος έχει ενημερωθεί με επιτυχία',
	'LBL_FAILED_TO_UPDATE_ACCESS_KEY' => 'Δεν ήταν δυνατή η ενημέρωση του Κλειδάριθμου',
	'LBL_TRANSFER_OWNERSHIP' => 'Μεταβίβαση Κυριότητας',
	'LBL_LOGIN_AS' => 'Σύνδεση ως ',
	'LBL_USER_DELETED_SUCCESSFULLY' => 'Ο χρήστης διαγράφηκε επιτυχώς',
	'LBL_ACTIVE_USERS' => 'Ενεργοί χρήστες',
	'LBL_INACTIVE_USERS' => 'Αδρανείς χρήστες',
	'LBL_CREATE_USER' => 'Δημιουργία χρήστη',
	'LBL_DELETE_USER_PERMANENTLY' => 'Διαγραφή χρήστη μόνιμα',
	'LBL_DELETE_USER_PERMANENTLY_INFO' => 'Η διαγραφή ενός χρήστη μόνιμα θα μεταφέρει όλες τις εγγραφές, συμπεριλαμβανομένων των σχολίων και του ιστορικού, σε νέο χρήστη.',
	'LBL_RESTORE' => 'Επαναφορά',
	'LBL_USER_RESTORED_SUCCESSFULLY' => 'Ο χρήστης επαναφέρθηκε με επιτυχία',
	//Login strings
	'LBL_TO_CRM' => 'Σύνδεση στο Vtiger CRM',
	'LBL_INVALID_USER_OR_PASSWORD' => 'Μη Έγκυρο ΄Ονομα η Συνθηματικό Χρήστη.',
	'LBL_INVALID_USER_OR_EMAIL' => 'Μη Έγκυρο Όνομα Χρήστη η Email.',
	'LBL_EMAIL_SEND' => 'Σάς Έχουμε Αποστείλει Email για την Ανάκτηση του Συνθηματικού σας.',
	'ForgotPassword' => 'Ξεχάσατε τον Συνθηματικό σας',
	'LBL_CONNECT_WITH_US' => 'Επικοινωνήστε Μαζί μας',
	'LBL_GET_MORE' => 'Αποκτήστε περισσότερα από το Vtiger',

	'LBL_TRANSFER_RECORDS_TO_USER' => 'Μεταφορά εγγραφών στον Χρήστη',
	'LBL_USER_TO_BE_DELETED' => 'Ο Χρήστης Πρόκειται να Διαγραφεί',
	'LBL_ALMOST_THERE'	=>	'Σχεδόν τελειώσαμε!',
	'LBL_ABOUT_ME'		=>	'Σχετικά με μένα',
	'LBL_WE_PROMISE_TO_KEEP_THIS_PRIVATE'	=>	'(Υποσχόμαστε να διατηρήσουμε αυτό ιδιωτικό)',
	'LBL_ALL_FIELDS_BELOW_ARE_REQUIRED'		=>	'(Όλα τα παρακάτω πεδία είναι υποχρεωτικά)',
	'LBL_GET_STARTED'	=> 'Ξεκινήστε',
	'LBL_YOUR_CONTACT_NUMBER' => 'Ο αριθμός τηλεφώνου σας',
	'LBL_WHERE_ARE_YOU_FROM' =>	'Από που είστε;',
	'LBL_SELECT_COUNTRY'	=> 'Επιλέξτε χώρα',
	'LBL_COMPANY_SIZE'		=> 'Μέγεθος εταιρείας',
	'LBL_JOB_TITLE'			=> 'Τίτλος εργασίας',
	'LBL_DEPARTMENT'		=> 'Τμήμα',
	'LBL_BASE_CURRENCY'		=> 'Βασικό Συνάλλαγμα',
	'LBL_CHOOSE_BASE_CURRENCY'	=> 'Επιλέξτε το Βασικό Συνάλλαγμα',
	'LBL_OPERATING_CURRENCY'	=> 'Το βασικό συνάλλαγμα δεν μπορεί να τροποποιηθεί αργότερα. Επιλέξτε το συνάλλαγμα που χρησιμοποιείτε',
	'LBL_LANGUAGE' => 'Γλώσσα',
	'LBL_CHOOSE_LANGUAGE'	=> 'Επιλογή Γλώσσας',
	'LBL_CHOOSE_TIMEZONE'	=> 'Επιλογή Ζώνη Ώρας',
	'LBL_DATE_FORMAT'		=> 'Μορφή ημερομηνίας',
	'LBL_CHOOSE_DATE_FORMAT'=> 'Επιλογή Μορφή ημερομηνίας',
	'LBL_PHONE'	=> 'Τηλέφωνο',
	'Space' => 'Χώρος',
	//picklist values for Default Calendar View field in MyPreference Page
	'ListView' => 'Προβολή λίστας',
	'MyCalendar' => 'Το ημερολόγιό μου',
	'SharedCalendar' => 'Κοινόχρηστο ημερολόγιο',

	'LBL_CHANGE_OWNER' => 'Αλλαγή κυριότητας',
	'LBL_TRANSFER_OWNERSHIP' => 'Μεταβίναση Κυριότητας',
	'LBL_TRANSFER_OWNERSHIP_TO_USER' => 'Μεταβίναση Κυριότητας στον Χρήστη',
	'LBL_OWNERSHIP_TRANSFERRED_SUCCESSFULLY' => 'Η Κυριότητα του CRM άλλαξε με επιτυχία',
	'LBL_OWNERSHIP_TRANSFERRED_FAILED' => 'Αποτυχία αλλαγής Κυριότητας CRM',
	'Account Owner' => 'Ιδιοκτήτης Λογαριασμού',
	'Starting Day of the week' => 'Ημέρα έναρξης της εβδομάδας',
	'Day starts at' => 'Η Ημέρα ξεκινάει από',
	'Default Event Status' => 'Προεπιλεγμένη κατάσταση συμβάντος',
	'Default Activity Type' => 'Προεπιλεγμένος τύπος δραστηριότητας',
	'Default Record View' => 'Προεπιλεγμένη προβολή εγγραφής',
	'Left Panel Hide' => 'Απόκρυψη του αριστερού πλαισίου',
	'Row Height' => 'Ύψος σειράς',

	//Change Username labels
	'LBL_CHANGE_USERNAME' => 'Αλλαγή ονόματος χρήστη',
	'LBL_USERNAME_CHANGED' => 'Το όνομα χρήστη άλλαξε με επιτυχία',
	'ERROR_CHANGE_USERNAME' => 'Σφάλμα κατά την αλλαγή ονόματος χρήστη. Παρακαλώ δοκιμάστε αργότερα',

	'LBL_RESTORE_USER_FAILED' => 'Αποτυχία επαναφοράς του χρήστη. Υπάρχει ήδη χρήστης CRM με αυτό το όνομα χρήστη.',

	'LBL_DUPLICATE_USER_EXISTS' => 'Ο χρήστης υπάρχει ήδη',

	/* For Vtiger7*/
	'LBL_USERS_SETTINGS' => 'ΡΥΘΜΙΣΕΙΣ ΧΡΗΣΤΩΝ',
	'LBL_TEMPLATES' => 'Πρότυπα',
);

$jsLanguageStrings = array(

	//Curency seperator validation messages
	'JS_ENTER_OLD_PASSWORD'=>'Παρακαλώ Εισάγετε τον Παλίο σας Συνθηματικό.',
	'JS_ENTER_NEW_PASSWORD'=>'Παρακαλώ Πληκτρολογήστε το Νέο σας Συνθηματικό.',
	'JS_ENTER_CONFIRMATION_PASSWORD'=>'Παρακαλώ Εισάγετε το Συνθηματικό Επιβεβαίωσης.',
	'JS_REENTER_PASSWORDS'=>'Παρακαλω Ξανα Εισάγετε. Τα \"Νέο Συνθηματικό\" και \"Συνθηματικό Επιβεβαίωσης\" δεν Ταιριάζουν.',
	'JS_INVALID_PASSWORD'=>'Παρακαλω Καθορίστε ένα Έγκυρο Όνομα Χρήστη και Συνθηματικό.',
	'JS_PASSWORD_CHANGE_FAILED_1'=>'Η Αλλαγή του Συνθηματικού Απέτυχε λόγο ',
	'JS_PASSWORD_CHANGE_FAILED_2'=>' αποτυχία. Πρέπει να Εισαχθεί νέο Συνθηματικό..',
	'JS_PASSWORD_INCORRECT_OLD'=>'Λάθος Παλίο Συνθηματικό. Εισάγετε Ξανά το Συνθηματικό.',
	'JS_ENTERED_CURRENT_USERNAME_MSG' => 'Εισήγατε το τρέχον όνομα χρήστη. Εισαγάγετε νέο όνομα χρήστη.',
	'JS_NEW_ACCESS_KEY_REQUESTED' => 'Αιτήθηκε νέος Κλειδάριθμος',
	'JS_CHANGE_ACCESS_KEY_CONFIRMATION' => 'You have requested for a new Access key.&lt;br&gt;&lt;br&gt;With the new Access key provision, you have to replace the old access key with the new one in all installed extensions.&lt;br&gt;&lt;br&gt;Do you want to continue?',
);
