<?php
/* +**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.1
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is: vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 * ***********************************************************************************/

$languageStrings = array(
	'LBL_PUBLISHER' => 'Εκδότης',
	'LBL_LICENSE' => 'Άδεια',
	'LBL_PUBLISHED_ON' => 'Δημοσιεύθηκε στις',
	'LBL_INSTALL' => 'Εγκατάσταση',
	'LBL_UPGRADE' => 'Αναβάθμιση',
	'LBL_VERSION' => 'Έκδοση',
	'LBL_DECLINE' => 'Άρνηση',
	'LBL_ACCEPT_AND_INSTALL' => 'Αποδοχή και εγκατάσταση',
	'LBL_OK' => 'OK',
	'LBL_EXTENSION_NOT_COMPATABLE' => 'Η επέκταση δεν είναι συμβατή',
	'LBL_INVALID_FILE' => 'Μη έγκυρο αρχείο',
	'LBL_NO_LICENSE_PROVIDED' => 'Δεν παρέχεται κάποια Άδεια',
	'LBL_INSTALLATION' => 'Εγκατάσταση',
	'LBL_FAILED' => 'Απέτυχε',
	'LBL_SUCCESSFULL' => 'Επιτυχής',
	'LBL_INSTALLATION_LOG' => 'Αναφορά εγκατάστασης',
	'LBL_UPDATED_MODULE' => ' ενημερώθηκε με επιτυχία.',
	'LBL_UPDATING_MODULE' => 'Ενημέρωση ενότητας',
	'LBL_MARKET_PLACE' => 'Market Place',

	//Extension Store translations
	'LBL_VTIGER_EXTENSION_STORE' => 'Κατάστημα επεκτάσεων Vtiger',
	'LBL_SEARCH_FOR_AN_EXTENSION' => 'Αναζήτηση για επέκταση..',
	'LBL_DOWNLOADS' => 'Λήψεις',
	'LBL_NO_EXTENSIONS_FOUND' => 'Δεν βρέθηκαν επεκτάσεις',
	'LBL_REGISTER_TO_MARKET_PLACE' => 'Εγγραφείτε στο Marketplace',
	'LBL_MARKETPLACE_REGISTRATION' => 'Εγγραφή στο Marketplace',
	'LBL_MARKETPLACE_LOGIN' => 'Είσοδος στο Marketplace',
	'LBL_NEW_TO_MARKETPLCAE' => 'Νέος χρήστης του Marketplace;',
	'LBL_CREATE_AN_ACCOUNT' => 'Δημιούργησε νέο λογαριασμό',
	'LBL_SETUP_CARD_DETAILS' => 'Ρύθμιση στοιχείων κάρτας',
	'LBL_SETUP_CARD' => 'Ρύθμιση κάρτας',
	'LBL_CARD_NUMBER' => 'Αριθμός κάρτας',
	'LBL_EXP_MONTH' => 'Μήνας λήξης',
	'LBL_EXP_YEAR' => 'Έτος λήξης',
	'LBL_CVC_CODE' => 'Κωδικός CVC',
	'LBL_RESET' => 'Επαναφορά',
	'LBL_EXTENSION_STORE' => 'Κατάστημα επεκτάσεων',
	'LBL_INSTALLED' => 'Εγκαταστήθηκε',
	'LBL_UPDATE_CARD_DETAILS' => 'Ενημέρωση λεπτομεριών Κάρτας',
	'LBL_BY' => 'από',
	'LBL_RATINGS' => 'Αξιολογήσεις',
	'LBL_DESCRIPTION' => 'Περιγραφή',
	'LBL_AUTHOR_INFORMATION' => 'Πληροφορίες Δημιουργού',
	'LBL_AUTHOR_NAME' => 'Όνομα Δημιουργού',
	'LBL_PHONE' => 'Τηλέφωνο',
	'LBL_EMAIL' => 'Email',
	'LBL_SCREEN_SHOTS' => 'Στιγμιότυπα',
	'LBL_CUSTOMER_RATINGS' => 'Αξιολογήσεις πελατών',
	'LBL_CUSTOMER_REVIEWS' => 'Κριτικές πελατών',
	'LBL_WRITE_A_REVIEW' => 'Γράψτε μια κριτική',
	'LBL_CUSTOMER_REVIEW' => 'Κριτική πελάτη',
	'LBL_REVIEW' => 'Κριτική',
	'LBL_CUSTOMERS_REVIEWED' => 'Πελάτες εξέτασαν',
	'LBL_SINGLE_CUSTOMER_REVIEWED' => 'Κριτική ενός πελάτη',
	'LBL_INSTALLATION_FAILED' => 'Η εγκατάσταση απέτυχε',
	'LBL_SUCCESSFULL_INSTALLATION' => 'Επιτυχής εγκατάσταση',
	'LBL_INSTALL_FROM_ZIP' => 'Εγκαταστήστε από Zip',
	'LBL_MORE_DETAILS' => 'Περισσότερες λεπτομέρειες',
	'Install' => 'Εγκατάσταση',
	'Upgrade' => 'Αναβάθμιση',
	'LBL_RATE_IT' => 'Βαθμολογήστε το.',
	'LBL_UNINSTALL' => 'Απεγκατάσταση',
	'LBL_LAUNCH' => 'Εκκίνηση',
	'LBL_SIGN_UP_FOR_FREE' => 'Εγγραφείτε δωρεάν',
	'LBL_EMAIL_ADDRESS' => 'Email',
	'LBL_FIRST_NAME' => 'Ονομα',
	'LBL_LAST_NAME' => 'Επίθετο',
	'LBL_COMPANY_NAME' => 'Ονομα εταιρείας',
	'LBL_PASSWORD' => 'Συνθηματικό',
	'LBL_CONFIRM_PASSWORD' => 'Επιβεβαιώση Συνθηματικού',
	'LBL_REGISTER' => 'Εγγραφή',
	'LBL_EXTENSION_STORE_LOGIN' => 'Είσοδος Καταστήματος επεκτάσεων',
	'LBL_REMEMBER_ME' => 'Θυμήσου με',
	'LBL_TRY_IT' => 'Δοκίμασέ το',
	'LBL_TRIAL_INSTALLED' => 'Δοκιμαστική εγκατάσταση',
	'LBL_BUY' => 'Αγορά ',
	'LBL_LOGIN_TO_MARKET_PLACE' => 'Είσοδος στο Marketplace',
	'LBL_LOGIN' => 'Είσοδος',
	'LBL_PHP_EXTENSION_LOADER_IS_NOT_AVAIABLE' => 'Εγκαταστήστε τον φορτωτή επέκτασης',
	'LBL_INSTALL_EXTENSION_LOADER' => 'Εγκατάσταση φορτωτή επέκτασης',
	'LBL_TO_CONTINUE_USING_EXTENSION_STORE' => 'Για να συνεχίσετε να χρησιμοποιείτε το Κατάστημα Επεκτάσεων, εγκαταστήστε το ',
	'LBL_DOWNLOAD' => 'Λήψη',
	'LBL_COMPATIABLE_EXTENSION' => ' και να το ενεργοποιήσετε ως zend_extension.',
	'LBL_MORE_DETAILS_ON_INSTALLATION' => 'Για περισσότερες λεπτομέρειες σχετικά με την εγκατάσταση ',
	'LBL_READ_HERE' => 'διαβάστε εδώ',
	'LBL_REVIEWS' => 'Κριτικές',
	'LBL_SIGNUP_FOR_MARKET_PLACE' => 'Εγγραφείτε στο Marketplace',
	'LBL_UNAUTHORIZED' => 'Ανεξουσιοδότητος',
	'LBL_EXPIRY_DATE' => 'Ημερομηνία λήξης',
	'LBL_LOGOUT' => 'Αποσύνδεση',

	'firstname' => 'Ονομα',
	'lastname' => 'Επίθετο',
	'email' => 'Email',
	'company' => 'Εταιρεία',
	'Phone' => 'Τηλέφωνο',
	'Website' => 'Ιστοσελίδα',
	'LBL_SECURITY_CODE' => 'Κωδικός ασφαλείας',
	'LBL_WHAT_IS_SECURITY_CODE' => 'Τι είναι ο Κωδικός ασφαλείας;',
	'LBL_CARD_NUMBER_PLACEHOLDER' => '16 ψηφία στην κάρτα σας',
	'LBL_SECURITY_CODE_HELP_CONTENT' => 'Ο αριθμός CVV (τιμή επαλήθευσης κάρτας) στην πιστωτική / χρεωστική σας κάρτα είναι ένας τριψήφιος αριθμός στις πιστωτικές / χρεωστικές κάρτες VISA®, MasterCard® κλπ.',
	'LBL_ENTER_REGISTERED_EMAIL' => 'Εισαγάγετε το καταχωρημένο email σας',
	'LBL_RESET_PASSWORD_LINK_EMAILED' => 'Ο σύνδεσμος Επαναφοράς συνθηματικού έχει αποσταλεί στο email σας!',
	'LBL_FORGOT_PASSWORD' => 'Ξεχάσατε το συνθηματικό',
	'LBL_ALREADY_INSTALLED_MODULE_BUILDER' => 'Δημιουργήθηκε ήδη από τον κατασκευαστή ενοτήτων',
	'LBL_REVIEW_RESTRICTED' => 'Περιορισμός Κριτικών',
);
$jsLanguageStrings = array(
	'JS_PLEASE_SETUP_CARD_DETAILS_TO_INSTALL_THIS_EXTENSION' => 'Ρυθμίστε τις λεπτομέρειες κάρτας για να εγκαταστήσετε αυτήν την επέκταση',
	'JS_UPDATE_CARD_DETAILS' => 'Ενημέρωση στοιχείων κάρτας',
	'JS_ON' => 'on',
	'JS_RATINGS' => 'Αξιολογήσεις',
	'JS_INSTALLED' => 'Εγκαταστήθηκε',
	'JS_TRIAL_INSTALLED' => 'Δοκιμαστική εγκατάσταση',
	'JS_PLEASE_INSTALL_EXTENSION_LOADER_TO_INSTALL_THIS_EXTENSION_FROM_BELOW_LINK' => 'Εγκαταστήστε τον φορτωτή επέκτασης για να εγκαταστήσετε αυτήν την επέκταση από τον παρακάτω σύνδεσμο',
	'JS_PLEASE_LOGIN_TO_MARKETPLACE_FOR_INSTALLING_EXTENSION' => 'Συνδεθείτε στο Marketplace για εγκατάσταση επέκτασης',
	'JS_PLEASE_SETUP_CARD_DETAILS_TO_INSTALL_EXTENSION' => 'Ρυθμίστε τα στοιχεία της κάρτας για την εγκατάσταση της επέκτασης',
	'JS_PLEASE_LOGIN_TO_MARKETPLACE_FOR_UNINSTALLING_EXTENSION' => 'Συνδεθείτε στο Marketplace για απεγκατάσταση της επέκτασης',
	'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_INSTALL_THIS_EXTENSION' => 'Είστε βέβαιοι ότι θέλετε να εγκαταστήσετε αυτήν την επέκταση;',
	'JS_CARD_DETAILS_UPDATED' => 'Τα στοιχεία της κάρτας ενημερώθηκαν!',
	'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_LOGOUT_FROM_EXTENSION' => 'Είστε βέβαιοι ότι θέλετε να αποσυνδεθείτε από την επέκταση;',
	'JS_PASSWORDS_MISMATCH' => "Τα συνθηματικά δεν ταιριάζουν!",
	'JS_ARE_YOU_SURE_UNINSTALL' => 'Είστε βέβαιοι ότι θέλετε να απεγκαταστήσετε αυτήν την επέκταση',
	'JS_ARE_YOU_SURE_INSTALL' => 'Είστε βέβαιοι ότι θέλετε να εγκαταστήσετε αυτήν την επέκταση',
);
