<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'LayoutEditor' => 'Επεξεργασία Διάταξης',
	'LBL_FIELDS_AND_LAYOUT_EDITOR' => 'Πεδία and Επεξεργασία διάταξης',
	'LBL_CREATE_CUSTOM_FIELD' => 'Δημιουργία προσαρμοσμένου πεδίου',
	'LBL_DETAILVIEW_LAYOUT' => 'Διάταξη Λεπτομερείς Προβολής',
	'LBL_ARRANGE_RELATED_TABS' => 'Οργάνωση σχετικών καρτελών',
	'LBL_ADD_CUSTOM_FIELD' => 'Προσθήκη Προσαρμοσμένου Πεδίου',
	'LBL_ADD_CUSTOM_BLOCK' => 'Προσθήκη Πλαισίου',
	'LBL_SAVE_FIELD_SEQUENCE' => 'Αποθήκευση Ακολουθίας Πεδίου',
	'LBL_BLOCK_NAME' => 'Όνομα Πλαισίου',
	'LBL_ADD_AFTER' => 'Προσθέστε Μετά απο',
	'LBL_ACTIONS' => 'Ενέργειες',
	'LBL_ALWAYS_SHOW' => 'Πάντα Εμφάνιση',
    'LBL_SHOW_INACTIVE_FIELDS' => 'Ανενεργά Πεδία',
	'LBL_SHOW_HIDDEN_FIELDS' => 'Προβολή κρυμμένων Πεδίων',
	'LBL_DELETE_CUSTOM_BLOCK' => 'Διαγραφή Προσαρμοσμένου Πλαισίου',
	'LBL_MANDATORY_FIELD' => 'Υποχρεωτικό Πεδίο',
	'LBL_ACTIVE' => 'Ενεργά',
	'LBL_QUICK_CREATE' => 'Γρήγορη Δημιουργία',
	'LBL_SUMMARY_FIELD' => 'Συνοπτική Προβολή',
    'LBL_KEY_FIELD_VIEW' => 'Προβολή πεδίου κλειδιού',
	'LBL_MASS_EDIT' => 'Μαζική Επεξεργασία',
	'LBL_DEFAULT_VALUE' => 'Προεπιλεγμένη Τιμή',
	'LBL_SELECT_FIELD_TYPE' => 'Επιλέξτε Τύπο πεδίου',
	'LBL_LABEL_NAME' => 'Όνομα ετικέτας',
	'LBL_LENGTH' => 'Μήκος',
	'LBL_DECIMALS' => 'Δεκαδικά',
	'LBL_ENTER_PICKLIST_VALUES' => 'Εισάγετε Τιμές στη Λίστα Επιλογών..',
	'LBL_PICKLIST_VALUES' => 'Τιμές Λίστας Επιλογών',
	'LBL_INACTIVE_FIELDS' => 'Ανενεργά Πεδία',
	'LBL_REACTIVATE' => 'Επανενεργοποίηση',
	'LBL_ARRANGE_RELATED_LIST' => 'Οργάνωση Σχετικής Λίστας',
	'LBL_SELECT_MODULE_TO_ADD' => 'Επιλέξτε Ενότητα για να προσθέσετε',
	'LBL_SELECT_HIDDEN_MODULE' => 'Επιλέξτε κρυμμένη ενότητα',
	'LBL_NO_RELATED_INFORMATION' => 'Μη Σχετικές Πληροφορίες',
	'LBL_RELATED_LIST_INFO' => 'Σύρετε για να αναδιατάξετε τη λίστα',
	'LBL_REMOVE_INFO' => 'Κάντε κλικ στο εικονίδιο για να αφαιρέσετε το άρθρωμα από τη λίστα',
	'LBL_ADD_MODULE_INFO' => 'Επιλέξτε το Άρθρωμα απο τα αφαιρεθέντα Αρθρώματα για να προστεθεί πίσω στην λίστα',
	'LBL_MANY_MANY_TEXT' => 'Πολλά-προς-πολλά σχέσεις είναι διαθέσιμες αυτήν τη στιγμή μόνο για %s και %s',	
	'LBL_SELECT_MODULE' => 'Επιλογή Ενότητας..',
	'LBL_DUPLICATES_EXIST' => 'Το Όνομα Πλαισίου Υπάρχει Ήδη',
	'LBL_NON_ROLE_BASED_PICKLIST' => 'Λίστα επιλογών Μη βασισμένου σε Ρόλους',
	'LBL_DUPLICATE_FIELD_EXISTS' => 'Το Διπλότυπο Πεδίο Υπάρχει',
	'LBL_WRONG_FIELD_TYPE' => 'Λάθος Τύπος πεδίου',
	'LBL_ROLE_BASED_PICKLIST' => 'Λίστα επιλογών Βασισμένος σε Ρόλους',
	'LBL_CLICK_HERE_TO_EDIT' => 'Κλικ Εδώ για Επεξεργασία',
	'LBL_EDIT_FIELD' => 'Επεξεργασία ιδιοτήτων πεδίου: %s',

	//Field Types
	'Text'=>'Κείμενο',
	'Decimal'=>'Δεκαδικό',
	'Integer'=>'Ακέραιος',
	'Percent'=>'Ποσοστό',
	'Currency'=>'Νόμισμα',
	'Date'=>'Ημερομηνία',
	'Email'=>'Email',
	'Phone'=>'Τηλέφωνο',
	'PickList'=>'Λίστα Επιλογών',
	'MultiSelectCombo'=>'Πλαίσιο Πολλαπλών Επιλογών',
	'URL' => 'URL',
	'Checkbox' => 'Πλαίσιο ελέγχου',
	'TextArea' => 'Περιοχή Κειμένου',
	'Skype'=>'Skype',
	'Time'=>'Ώρα',
	
	//Translation for module
	'Calendar' => 'Εργασία',
	'LBL_FIELD_COULD_NOT_BE_CREATED'=>'Το πεδίο %s δεν μπόρεσε να δημιουργηθεί',
	'SELECT_MODULE' => 'Επιλέξτε Ενότητα',
    
    //Related Lists 
    'LBL_RELATION_SHIPS' => 'Συσχέτιση',
    'LBL_ADD_RELATIONSHIP' => 'Προσθήκη Συσχέτισης',
    'LBL_RELATED_MODULE' => 'Σχετιζόμενη Ενότητα',
    'LBL_ADDING_RELATIONSHIP' => 'Προσθήκη Συσχέτισης για %s',
    'LBL_SELECTED_RELATED_MODULE' => 'Επιλέξτε σχετική ενότητα',
    'LBL_SELECTED_RELATION_TYPE' => 'Επιλέξτε τύπο Συσχέτισης',
    'ONE_ONE_AND_MANY_ONE_RELATIONSHIP' => 'Συσχετίσεις Ένα-προς-ένα και Πολλά-προς-ένα',
    'ONE_MANY_RELATIONSHIP' => 'Συσχετίσεις Ένα-προς-πολλά & Πολλά-προς-πολλά',
    '1-1' => 'Ένα προς Ένα',
    '1-N' => 'Ένα προς Πολλά',
    'N-1' => 'Πολλά προς Ένα',
    'N-N' => 'Πολλά προς Πολλά',
    
	
	//New layout translations
	'LBL_FIELD_TYPES'                   => 'Τύποι Πεδίου', 
	'LBL_BASIC_FIELDS'             => 'Βασικά Πεδία', 
	'LBL_MANDATORY'                => 'Υποχρεωτικά Πεδία', 
	'LBL_PROPERTIES'               => 'Ιδιότητες', 
	'LBL_DRAG_UI_TYPE'             => 'Σύρετε το πεδίο εδώ', 
	'LBL_RELATION_FIELDS'          => 'Πεδία συσχέτισης', 
	'LBL_SELECT_BLOCK'             => 'Επιλέξτε πλαίσιο', 
    'LBL_RELATION_ADDED_SUCCESS'   => 'Η συσχέτιση προστέθηκε με επιτυχία',
    
    'FIELD_NAME_IN_PRIMARY_MODULE' => 'Πεδίο συσχέτισης στο %s',
    'FIELD_NAME_IN_RELATED_MODULE' => 'Πεδίο συσχέτισης μέσα σε %s',
    'TAB_IN_PRIMARY_MODULE'        => 'Πίνακας/Καρτέλα στό %s',
    'TAB_IN_RELATED_MODULE'        => 'Πίνακας/Καρτέλα in %s',
    
    'LBL_DETAIL_VIEW'              => 'Προβολή λεπτομερειών',
    'LBL_EXPANDED'                 => 'Eπέκταση',
    'LBL_COLLAPSED'                => 'Σύμπτυξη',
    
    'LBL_FILED_IN_PRIMARY_HELP_TEXT' => 'Πεδίο αναφοράς της %s ενότητας',
    'LBL_TAB_IN_PRIMARY_HELP_TEXT'   => 'Πίνακας/Καρτέλα της %s ενότητας',
    'LBL_FILED_IN_RELATED_HELP_TEXT' => 'Πεδίο αναφοράς της %s ενότητας',
    'LBL_TAB_IN_RELATED_HELP_TEXT'   => 'Πίνακας/Καρτέλα της %s ενότητας',
    'LBL_NO_RELATION_TYPE'         => 'Δεν υπάρχει συσχέτιση αυτού του τύπου',

	'LBL_CREATE_ITEM_CUSTOM_FIELD' => 'Δημιουργία προσαρμοσμένου πεδίου στοιχείου γραμμής',
	'LBL_MAP_PRODUCT_FIELD' => 'Πεδίο Διασύνδεσης προς προϊόντα',
	'LBL_MAP_SERVICE_FIELD' => 'Πεδίο Διασύνδεσης προς υπηρεσίες',
	'LBL_ENABLE_TO_MAP_PRODUCT_FIELD' => 'Ενεργοποίηση πεδίο διασύνδεσης προς προϊόντα',
	'LBL_ENABLE_TO_MAP_SERVICE_FIELD' => 'Ενεργοποίηση πεδίο διασύνδεσης προς υπηρεσία',
    
    //Vtiger7 Strings
    'LBL_NO_RELATED_INFO' => 'Δεν υπάρχει κάποια Συσχέτιση',
    'LBL_ADD_NEW_FIELD_HERE' => 'Προσθέστε νέο πεδίο εδώ',
    'LBL_SAVE_LAYOUT' => 'Αποθήκευση διάταξης',
    'LBL_SHOW_FIELD' => 'Εμφάνιση πεδίου',
    'LBL_ENABLE_OR_DISABLE_FIELD_PROP' => 'Ενεργοποίηση / απενεργοποίηση ιδιοτήτων πεδίου',
    'LBL_PROP_MANDATORY' => 'υποχρεωτικό',
    'LBL_DEFAULT_VALUE_NOT_SET' => 'Η προεπιλεγμένη τιμή δεν έχει οριστεί',
    'LBL_INFO' => 'Πληροφορίες',
    'LBL_PRODUCTFIELDDEFAULTVALUE' => ' (Προϊόντα)',
    'LBL_SERVICEFIELDDEFAULTVALUE' => ' (Υπηρεσίες)',
    'LBL_SHOW_THIS_FIELD_IN' => 'Κάντε κλικ εδώ για να εμφανίσετε αυτό το πεδίο σε %s προβολή',
    'LBL_MAKE_THIS_FIELD' => 'Κάντε κλικ εδώ για να κάνετε αυτό το πεδίο %s',
    'LBL_HIDE_THIS_FIELD_IN' => 'Κάντε κλικ εδώ για να κρύψετε αυτό το πεδίο σε %s προβολή',
    'LBL_NOT_MAKE_THIS_FIELD' => 'Κάντε κλικ εδώ για να κάνετε αυτό το πεδίο μη-%s',
    'LBL_TAB_NAME_HELP_TEXT' => 'Λίστα απο %s προβάλεται στην %s εγγραφή',
    'LBL_TAB_NAME_TEXT' => 'Όνομα καρτέλας απο %s στην %s εγγραφή',
    'LBL_FILED_NAME_HELP_TEXT' => 'Ένα πεδίο αναφοράς στο %s στην %s εγγραφή θα προστεθεί',
    'LBL_FIELD_NAME_TEXT' => 'Όνομα πεδίου του %s στην εγγραφή %s',
	'LBL_COLLAPSE_BLOCK' => 'Σύμπτυξη πλαισίου',
	'LBL_COLLAPSE_BLOCK_DETAIL_VIEW' => 'Σύμπτυξη του πλαισίου στην λεπτομερή προβολή',
    'LBL_HEADER' => 'Κεφαλίδα',
    'LBL_DETAIL_HEADER' => 'Κεφαλίδα εγγραφής',
    'LBL_HEADER_FIELD' => 'Προβολή κεφαλίδας',

	'LBL_DUPLICATE_HANDLING' => 'Πρόλυψη Διπλότυπου',
	'LBL_DUPLICATE_CHECK' => 'Ενεργοποίηση ελέγχου για διπλότυπα',
	'LBL_DUPLICATION_INFO_MESSAGE' => 'Η δυνατότητα πρόληψης διπλότυπων αποτρέπει μόνο τη δημιουργία νέων διπλότυπων εγγραφών από τους χρήστες και τις εξωτερικές εφαρμογές. Οι εγγραφές που έχουν δημιουργηθεί από την Εισαγωγή και από τις Ροές εργασιών δεν θα ελεγχθούν για διπλότυπα. <br><br> Οι υπάρχουσες διπλότυπες εγγραφές μπορούν να καταργηθούν χρησιμοποιώντας τη λειτουργία "Εύρεση διπλότυπων" από τη σελίδα της ενότητας.',
	'LBL_SELECT_FIELDS_FOR_DUPLICATION' => 'Επιλέξτε τα μοναδικά πεδία στα οποία πρέπει να ελεγχθούν οι διπλότυπες εγγραφές',
	'LBL_SELECT_FIELDS' => 'Επιλέξτε πεδία',
	'LBL_MAX_3_FIELDS' => 'Μέγιστo 3 πεδία',
	'LBL_SELECT_RULE' => 'Επιλέξτε κανόνα για τον χειρισμό διπλότυπων',
	'LBL_ALLOW_DUPLICATES' => 'Επιτρέψτε Διπλότυπα',
	'LBL_DO_NOT_ALLOW_DUPLICATES' => 'Μην επιτρέπετε Διπλότυπα',
	'LBL_DUPLICATES_IN_SYNC_MESSAGE' => 'Διαδικασία που θα ακολουθηθεί εάν εντοπιστεί διπλότυπη εγγραφή κατά το συγχρονισμό με εξωτερική εφαρμογή',
	'LBL_PREFER_LATEST_RECORD' => 'Προτιμήστε την τελευταία εγγραφή',
	'LBL_PREFER_INTERNAL_RECORD' => 'Προτιμήστε την εσωτερική εγγραφή',
	'LBL_PREFER_EXTERNAL_RECORD' => 'Προτιμήστε την εξωτερική εγγραφή',
	'LBL_SYNC_TOOLTIP_MESSAGE' => 'Προτιμήστε την τελευταία εγγραφή - Τα πιο πρόσφατα τροποποιημένα δεδομένα εγγραφής θα διατηρηθούν <br> Προτιμήστε την εσωτερική εγγραφή - Η υπάρχουσα εγγραφή θα διατηρηθεί όπως είναι <br> Προτιμήστε την εξωτερική εγγραφή - Θα αντιγραφούν δεδομένα από την εξωτερική εφαρμογή',
);

$jsLanguageStrings = array(
	'JS_BLOCK_VISIBILITY_SHOW' => 'Το Πλαίσιο είναι Ενεργό',
	'JS_BLOCK_VISIBILITY_HIDE' => 'Η απόκρυψη πλαισίου είναι Ενεργή',
	'JS_CUSTOM_BLOCK_ADDED' => 'Νέο Προσαρμοσμένο Πλαίσιο Προστέθηκε',
	'JS_BLOCK_SEQUENCE_UPDATED' => 'Η Ακολουθία Πλαισίων Ενημερώθηκε',
	'JS_SELECTED_FIELDS_REACTIVATED' => 'Τα επιλεγμένα πεδία επανενεργοποιήθηκαν',
	'JS_FIELD_DETAILS_SAVED' => 'Οι Λεπτομέρειες των Πεδίων Αποθηκεύτηκαν',
	'JS_CUSTOM_BLOCK_DELETED' => 'Το Προσαρμοσμένο Πλαίσιο διαγράφηκε',
	'JS_CUSTOM_FIELD_ADDED' => '%s προσαρμοσμένο πεδίο Προστέθηκε',
	'JS_CUSTOM_FIELD_DELETED' => 'Το Προσαρμοσμένο πεδίο Διαγράφηκε',
	'JS_LENGTH_SHOULD_BE_LESS_THAN_EQUAL_TO' => 'Το Μήκος πρέπει να είναι μικρότερο ή ίσο προς',
	'JS_PLEASE_ENTER_NUMBER_IN_RANGE_2TO5' => 'Το Δεκαδικό θα πρέπει να είναι στην κλίμακα 2 έως 5',
	'JS_SAVE_THE_CHANGES_TO_UPDATE_FIELD_SEQUENCE' => 'Αποθηκεύστε τις αλλαγές για να ενημερώσετε την ακολουθία των Πεδίων',
	'JS_RELATED_INFO_SAVED' => 'Σχετικές πληροφορίες Αποθηκεύτηκαν',
	'JS_BLOCK_NAME_EXISTS' => 'Το όνομα πλαισίου υπάρχει ήδη',
	'JS_NO_HIDDEN_FIELDS_EXISTS' => 'Δεν υπάρχουν ανενεργά πεδία',
	'JS_SPECIAL_CHARACTERS' => 'Ειδικοί χαρακτήρες όπως',
	'JS_NOT_ALLOWED' => 'δεν επιτρέπονται',
	'JS_FIELD_SEQUENCE_UPDATED' => 'Η ακολουθία πεδίου ενημερώθηκε',
	'JS_DUPLICATES_VALUES_FOUND' => 'Βρέθηκαν Διπλότυπες Τιμές',
    'JS_FIELD_IN_RELATED_MODULE'  => 'Πεδίο συσχέτισης στο %s',
    'JS_TAB_IN_RELATED_MODULE' => 'Πίνακας/Καρτέλα σε %s',
    'JS_FILED_IN_RELATED_HELP_TEXT' => 'Πεδίο αναφοράς της %s ενότητας',
    'JS_TAB_IN_RELATED_HELP_TEXT' => 'Πίνακας/Καρτέλα της %s ενότητας',
    'JS_TAB_FIELD_DELETION'   => 'Η διαγραφή της συσχέτισης θα διαγράψει το %s πεδίο στην %s ενότητα και θα διαγράψει τον %s Πίνακα/Καρτέλα στο %s. Θέλετε να προχωρήσετε;',
    'JS_ONE_ONE_RELATION_FIELD_DELETE' => 'Αυτό θα διαγράψει το %s πεδίο στη %s ενότητα και θα διαγράψει το %s πεδίο στην %s ενότητα. Θέλετε να συνεχίσετε;',
	'JS_CUSTOM_FIELDS_MAX_LIMIT' => 'Μπορείτε να προσθέσετε το μέγιστο %s προσαρμοσμένα πεδία σε %s πλαίσιο',
    'JS_DEFAULT_VALUE_NOT_SET' => 'Η προεπιλεγμένη τιμή δεν έχει οριστεί',
    'JS_DEFAULT_VALUE' => 'Προεπιλεγμένη Τιμή',
    'JS_SAVE_MODULE_SEQUENCE' => 'Αποθηκεύστε τις αλλαγές για να ενημερώσετε τη σχετική ακολουθία ενότητας',
    'JS_PRODUCTFIELDDEFAULTVALUE' => ' (Προϊόντα)',
    'JS_SERVICEFIELDDEFAULTVALUE' => ' (Υπηρεσίες)',
    'JS_TAB_TAB_DELETION' => 'Αυτό θα διαγράψει την %s καρτέλα στη %s ενότητα και τα δεδομένα της. Θέλετε να προχωρήσετε;',
    'JS_SHOW_THIS_FIELD_IN' => 'Κάντε κλικ εδώ για να εμφανίσετε αυτό το πεδίο %s προβολή',
    'JS_MAKE_THIS_FIELD' => 'Κάντε κλικ εδώ για να κάνετε αυτό το πεδίο %s',
    'JS_HIDE_THIS_FIELD_IN' => 'Κάντε κλικ εδώ για να αποκρύψετε αυτό το πεδίο στην %s προβολή',
    'JS_NOT_MAKE_THIS_FIELD' => 'Κάντε κλικ εδώ για να κάνετε αυτό το πεδίο μη-%s',
    'JS_TAB_NAME_HELP_TEXT' => 'Λίστα απο %s εμφανίζεται στην %s εγγραφή',
    'JS_TAB_NAME_TEXT' => 'Όνομα καρτέλας του %s στην %s εγγραφή',
    'JS_FILED_NAME_HELP_TEXT' => 'Θα προστεθεί ένα πεδίο αναφοράς στο %s στην εγγραφή %s',
    'JS_FIELD_NAME_TEXT' => 'Όνομα πεδίου του %s στην %s εγγραφή',
    'JS_PROP_MANDATORY' => 'υποχρεωτικό',
    'JS_SUMMARY' => 'Περίληψη',
    'JS_KEY_FIELD' => 'Πεδίο Κλειδιού',
    
    'JS_QUICK_CREATE' => 'Γρήγορη δημιουργία',
    'JS_MASS_EDIT' => 'Μαζική Επεξεργασία',
    'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_DELETE' => 'Αυτή η λειτουργία θα οδηγήσει σε μόνιμη αφαίρεση των δεδομένων.
                                                 Όταν διαγραφεί ένα πεδίο, οι τιμές που αποθηκεύονται σε αυτό το πεδίο θα διαγραφούν και δεν μπορούν να ανακτηθούν.
                                                 Εάν δεν είστε σίγουροι και θέλετε να μπορείτε να προβάλετε αυτά τα δεδομένα στο μέλλον, μπορείτε να επισημάνετε το πεδίο ως Ανενεργό αντί να το διαγράψετε. Τα ανενεργά πεδία μπορούν αργότερα να ενεργοποιηθούν ανά πάσα στιγμή.
                                                 Είστε βέβαιοι ότι θέλετε να διαγράψετε αυτό το πεδίο;',
    'JS_FIELD_DELETE_CONFIRMATION' => 'Διαγραφή - Δεν χρειάζομαι τα δεδομένα σε αυτό το πεδίο.',
	'JS_STATUS_CHANGED_SUCCESSFULLY' => 'Η κατάσταση άλλαξε με επιτυχία',
    'JS_FIELD_CAN_EITHER_BE_HEADER_OR_SUMMARY_ENABLED' => 'Το πεδίο μπορεί να είναι είτε πεδίο κεφαλίδας είτε πεδίο κλειδιού',
    'JS_DETAIL_HEADER' => 'Κεφαλίδα εγγραφής',
    'JS_MAXIMUM_HEADER_FIELDS_ALLOWED' => 'Επιτρέπονται το μέγιστο %s κεφαλίδες πεδίων',
    'JS_NAME_FIELDS_APPEAR_IN_HEADER_BY_DEFAULT' => 'Τα πεδία ονόματος εμφανίζονται στην Κεφαλίδα από προεπιλογή',
    'JS_FIELD_IS_HEADER_ENABLED_FOR_VTIGER7' => 'Αυτό το πεδίο είναι ενεργοποιημένο με κεφαλίδα για το Vtiger7, Θα εμφανιστεί στη Προβολή Σύνοψης',

	'JS_DUPLICATE_HANDLING_SUCCESS_MESSAGE' => 'Ενημερώθηκε με επιτυχία για να ληφθούν υπόψη τα επιλεγμένα πεδία στην πρόληψη διπλότυπων',
	'JS_DUPLICATE_HANDLING_FAILURE_MESSAGE' => 'Αποτυχία να ληφθούν υπόψη τα επιλεγμένα πεδία σε πρόληψη διπλότυπων',
	'JS_DUPLICATE_CHECK_DISABLED' => 'Ο έλεγχος διπλότυπων είναι απενεργοποιημένος',
);
