<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	// Basic Strings
	'Settings' => 'Ρυθμίσεις',
	'LBL_MAILROOM'=>'Mailroom',
	'LBL_SEARCH_SETTINGS_PLACEHOLDER' => 'Αναζήτηση στις Ρυθμίσεις',
	'LBL_SUMMARY' => 'Σύνοψη',
	'LBL_ACTIVE_USERS' => 'Χρήστες',
	'LBL_WORKFLOWS_ACTIVE' => 'Ροές Εργασιών',
	'LBL_MODULES' => 'Ενότητες',
	'LBL_SETTINGS_SHORTCUTS' => 'Συντομεύσεις Ρυθμίσεων',
	'LBL_UNPIN' => 'Ξεκαρφίτσωμα',
	'LBL_PIN' => 'καρφίτσωμα',

	// Blocks
	'LBL_STUDIO' => 'Κέντρο Σχεδιασμού',
	'LBL_COMMUNICATION_TEMPLATES' => 'Πρότυπα',
	'LBL_USER_MANAGEMENT' => 'Διαχείριση Χρηστών & Πρόσβασης',
	'LBL_ACCESS_MANAGEMENT' => 'Διαχείριση Πρόσβασης',
	'LBL_MODULE_MANAGER' => 'Διαχείριση Ενοτήτων',
	'LBL_NOTIFICATIONS' => 'Ειδοποιήσεις',
	'LBL_EXTERNAL_SERVER_SETTINGS' => 'Ρυθμίσεις Απομακρυσμένου Server',
	'LBL_OTHER_SETTINGS' => 'Λοιπές Ρυθμίσεις',
	'LBL_EXTENSIONS_PLACE' => 'Τοποθεσία Επεκτάσεων',
	'LBL_EXTENSIONS' => 'Επεκτάσεις',

	'LBL_PBXMANAGER' => 'PBXManager',
    'LBL_INTEGRATION' => 'Integration',
    'LBL_EXCHANGE_CONNECTOR' => 'Διασύνδεση με Exchange',
    
    // Fields
	'LBL_DESCRIPTION' => 'Περιγραφή',
    
	// Other Strings
	'LBL_USER_DESCRIPTION' => 'Διαχείριση Χρηστών πού έχουν Πρόσβαση στο vtiger CRM',
	'LBL_ROLES' => 'Ρόλοι',
	'LBL_ROLE_DESCRIPTION' => 'Δημιουργία Ιεραρχίας των Ρόλων και Ανάθεσης στους Χρήστες',

	'LBL_PROFILES' => 'Προφίλ Χρηστών',
	'LBL_PROFILE_DESCRIPTION' => 'Διαχείριση πρόσβασης ενοτήτων ανά χρήστη προς διαφορετικούς ρόλους',

	'USERGROUPLIST' => 'Ομάδες',
	'LBL_GROUP_DESCRIPTION' => 'Διαχείριση τύπων ομάδων βασισμένων ανά ρόλο, χρήστες και προφίλ',

	'LBL_SHARING_ACCESS' => 'Κανόνες Διαμερισμού',
	'LBL_SHARING_ACCESS_DESCRIPTION' => 'Διαχείριση κανόνων προσαρμοσμένου διαμοιρασμού και κανόνων διαμοιρασμού ενοτήτων',

	'LBL_WORKFLOW_LIST' => 'Λίστα Ροής Εργασιών',
	'LBL_AVAILABLE_WORKLIST_LIST' => 'Διαθέσιμες Ροές Εργασιών',
	'LBL_FIELDFORMULAS' => 'Φόρμουλες Πεδίων',
	'LBL_FIELDFORMULAS_DESCRIPTION' => 'Προσθήκη προσαρμοσμένων εξισώσεων στα προσαρμοσμένα πεδία',

	'VTLIB_LBL_MODULE_MANAGER' => 'Ενότητες',
	'VTLIB_LBL_MODULE_MANAGER_DESCRIPTION' => 'Διαχείριση συμπεριφοράς ενοτήτων εντός του vtiger CRM',
	'LBL_PICKLIST_EDITOR' => 'Τιμές Λίστας Επιλογών',
	'LBL_PICKLIST_DESCRIPTION' => 'Προσαρμογή Τιμών στις Λίστες Επιλογών σε κάθε ενότητα',
	'LBL_PICKLIST_DEPENDENCY_SETUP' => 'Εξαρτήσεις της Λίστας Επιλογών',
	'LBL_PICKLIST_DEPENDENCY_DESCRIPTION' => 'Εγκατάσταση Εξαρτήσεων μεταξύ των τιμών της Λίστας Επιλογών μέσα σε κάθε ενότητα',

	'LBL_FIELDFORMULAS' => 'Φόρμουλες Πεδίων',
	'LBL_FIELDFORMULAS_DESCRIPTION' => 'Προσθήκη προσαρμοσμένων εξισώσεων στα προσαρμοσμένα πεδία',

	'LBL_MENU_EDITOR' => 'Κύριο Μενού',
	'LBL_MENU_DESC' => 'Προσαρμογή Σειράς Μενού',
	'LBL_MENU_EDITOR_MESSAGE' => 'Ο πραγματικός αριθμός των στοιχείων μενού που εμφανίζονται εξαρτάται από το μέγεθος της οθόνης και ενδέχεται να είναι μικρότερος από τα επιλεγμένα στοιχεία.',

	'EMAILTEMPLATES' => 'Πρότυπα E-mail',
	'LBL_EMAIL_TEMPLATE_DESCRIPTION' => 'Διαχείριση Προτύπων για την ενότητα του E-Mail',

	'LBL_COMPANY_DETAILS' => 'Λεπτομέρειες Εταιρείας',
	'LBL_COMPANY_DESCRIPTION' => 'Προσδιορισμός Διεύθυνσης τής Εταιρείας',

	'LBL_MAIL_MERGE' => 'Συγχώνευση Email',
	'LBL_MAIL_MERGE_DESCRIPTION' => 'Διαχείριση Προτύπων για τη Συγχώνευση Email',

	'LBL_TAX_SETTINGS' => 'Υπολογισμός Φόρων',
	'LBL_TAX_DESCRIPTION' => 'Διαχείριση φόρων και των αντίστοιχων φορολογικών συντελεστών',

	'LBL_MAIL_SERVER_SETTINGS' => 'Διακομιστής Εξερχομένων',
	'LBL_MAIL_SERVER_DESCRIPTION' => 'Διαμόρφωση Λεπτομερειών Διακομιστή Εξερχομένων',

	'INVENTORYTERMSANDCONDITIONS' => 'Αποθήκη: Όροι και Προϋποθέσεις',
	'LBL_INV_TANDC_DESCRIPTION' => 'Καθορίστε τους όρους και τις προϋποθέσεις για Προσφορές, Τιμολόγια και Παραγγελίες Πωλήσεων',

	'LBL_ANNOUNCEMENT_DESCRIPTION' => 'Διαχειριστείτε τις ανακοινώσεις της εταιρείας',

	'LBL_CURRENCY_SETTINGS' => 'Συναλλάγματα',
	'LBL_CURRENCY_DESCRIPTION' => 'Διαχείριση διεθνών νομισμάτων και συναλλαγματικών ισοτιμιών',

	'LBL_CUSTOMIZE_MODENT_NUMBER' => 'Αρίθμηση Ενοτήτων',
	'LBL_CUSTOMIZE_MODENT_NUMBER_DESCRIPTION' => 'Προσαρμογή Αρίθμησης Οντότητας Ενότητας',

	'LBL_MAIL_SCANNER' => 'Μετατροπέας Email',
	'LBL_MAIL_SCANNER_DESCRIPTION' => 'Προσαρμογή Εισερχομένων email προς σάρωση και επισυναπτόμενων εγγραφών',

	'LBL_LIST_WORKFLOWS' => 'Ροές Εργασιών',
	'LBL_LIST_WORKFLOWS_DESCRIPTION' => 'Δημιουργία και Επεξεργασία Ροής Εργασίας',
    'LBL_SELECT_DATE' => 'Επιλογή Ημερομηνιών',

	'Configuration Editor' => 'Επεξεργαστής Ρυθμίσεων',
	'LBL_CONFIG_EDITOR_DESCRIPTION' => 'Ενημέρωση αρχείου ρυθμίσεων της εφαρμογής',
	'Update configuration file of the application' => 'Ενημέρωση αρχείου ρυθμίσεων της εφαρμογής',
	'LBL_PERSONAL_EMAIL_TRACKING_INFO' => 'Για να παρακολουθήσετε το άνοιγμα των άμεσων email που αποστέλλονται στις επαφές, ενεργοποιήστε αυτό το πλαίσιο ελέγχου. Λάβετε υπόψη ότι τα email που αποστέλλονται από την ενότητα "Καμπάνιες ηλεκτρονικού ταχυδρομείου" παρακολουθούνται πάντα και δεν επηρεάζονται από αυτήν τη ρύθμιση',
	'LBL_CUSTOMER_PORTAL' => 'Διαδικτυακή Πύλη Πελατών',
	'PORTAL_EXTENSION_DESCRIPTION' => 'Σας Επιτρέπει την Διαμόρφωση της επέκτασης: Διαδικτυακή Πύλη Χρηστών',
	
	'LBL_LAYOUT_EDITOR_DESCRIPTION' => 'Σχεδιασμός και Τροποποίηση Εμφάνισης της κάθε ενότητας',
	'LBL_WEBFORMS_DESCRIPTION' => 'Δημιουργία και διαχείριση δικτυακής φόρμας που μπορεί να συλλέξει Δυνητικούς, Επαφές, Αιτήματα κλπ',
	'LBL_TO_ADD_NEW_USER_PLEASE_CLICK_ON' => 'Για την Προσθήκη Νέου Χρήστη Κάντε Κλικ στο ',
	'LBL_SETTINGS_ICON' => 'Εικονίδιο Ρυθμίσεων',
	'LBL_ADD_OR_DELETE_USERS' => 'Προσθήκη/Διαγραφή Χρηστών',
	'LBL_ADD_USER' => 'Προσθήκη Χρήστη',
	
'LBL_LABELS_EDITOR' => 'Επεξεργαστής Ονομάτων Πεδίων',
	'LBL_LABELS_EDITOR_DESCRIPTION' => 'Lets you customize module names, field labels and other strings according to your business requirements',

	'Scheduler' => 'Scheduler',
	'Allows you to Configure Cron Task' => 'Σας επιτρέπει να ρυθμίσετε τις παραμέτρους του Cron Task',

	'Webforms' => 'Δικτυακές Φόρμες',
	'Allows you to manage Webforms' => 'Διαχείριση Δικτυακής Φόρμας',
	'LBL_CREATING_NEW' => 'Δημιουργία νέας',
	'LBL_EDITING' => 'Επεξεργασία',
	'LBL_EDIT_RECORD' => 'Επεξεργασία',
	'LBL_DELETE_RECORD' => 'Διαγραφή',

	//Menu Editor
	'LBL_ADD_MOVE_MENU_ITEMS' => 'Προσθήκη/Μετακίνηση Αντικειμένων Μενού',
	'LBL_ADD_MENU_ITEM' => 'Προσθήκη Αντικειμένου Μενού',
	'LBL_MAX' => 'Μέγιστο',
	
	//Tax Calculations
	'LBL_TAX_CALCULATIONS' => 'Υπολογισμός Φόρου',
	'LBL_TAX_DESC'=>'Διαχειριστείτε διαφορετικούς τύπους φορολογικών συντελεστών για τους φόρους, όπως ο φόρος επί των πωλήσεων, ΦΠΑ κλπ.,',
	'LBL_PRODUCT_SERVICE_TAXES' => 'Φορολογία Υπηρεσιών και Προϊόντων',
	'LBL_SHIPPING_HANDLING_TAXES' => 'Φόροι αποστολής & διακίνησης',
	'LBL_ADD_NEW_TAX' => 'Προσθήκη Νέου Φόρου',
	'LBL_EDIT_TAX' => 'Επεξεργασία Φόρου',
	'LBL_TAX_NAME' =>  'Όνομα Φόρου',
	'LBL_TAX_VALUE' => 'Τιμή αξία',
	'LBL_STATUS' => 'Κατάσταση',
	'LBL_TAX_STATUS_DESC' => 'Ενεργοποιείστε το πλαίσιο ελέγχου για να καταστεί ο φόρος ενεργός',
	'LBL_ENTER_TAX_NAME' => 'Εισαγωγή Ονομασίας Φόρου',
	'LBL_ENTER_TAX_VALUE' => 'Εισαγωγή Τιμής Φόρου',
	'LBL_TAX_NAME_EXIST' => 'Αυτό το Όνομα Φόρου Υπάρχει ήδη',

	'LBL_TAXES' => 'Φόροι',
	'LBL_CHARGES_AND ITS_TAXES' => 'Χρεώσεις (και φόροι)',
	'LBL_TAX_REGIONS' => 'Εύρος φόρων',
	'LBL_NO_REGION_EXISTS' => 'Δεν υπάρχει εύρος',
	'LBL_TYPE' => 'Τύπος',
	'LBL_CALCULATION' => 'Υπολογισμός',
	'LBL_ADD_NEW_CHARGE' => 'Προσθήκη νέας χρέωσης',
	'LBL_ADD_NEW_TAX_FOR_CHARGE' => 'Προσθέστε νέο φόρο για χρέωση',
	'LBL_CHARGE_NAME' => 'Όνομα Χρέωσης',
	'LBL_CHARGE_NAME_EXIST' => 'Το όνομα χρέωσης υπάρχει ήδη',
	'LBL_VALUE' => 'Τιμή',
	'LBL_IS_TAXABLE' => 'Είναι φορολογητέα',
	'LBL_AVAILABLE_REGIONS' => 'Διαθέσιμο Εύρος',
	'LBL_ADD_NEW_REGION' => 'Προσθήκη νέου Εύρους',
	'LBL_TAX_REGION_DESC' => 'Το φορολογικό εύρος θα εμφανίζεται κατά τη δημιουργία μεταβλητών φόρων και μπορούν να επιλεγούν κατά τη δημιουργία των προσφορών, των τιμολογίων, της παραγγελίας πώλησης, της εντολής αγοράς',
	'LBL_TAX_CALCULATION' => 'Υπολογισμός φόρου',
	'LBL_SIMPLE' => 'Απλό',
	'LBL_COMPOUND' => 'Σύνθετο',
	'LBL_DEDUCTED' => 'Εκπίπτει',
	'LBL_TAX_TYPE' => 'Φορολογικός τύπος',
	'LBL_FIXED' => 'Σταθερός',
	'LBL_VARIABLE' => 'Μεταβλητός',
	'LBL_COMPOUND_ON' => 'Σύνθετο σε',
	'LBL_DEFAULT_VALUE' => 'Προκαθορισμένο',
	'LBL_ADD_TAX_BRACKET' => 'Προσθέστε φορολογική βάση',
	'LBL_TAX_BRACKETS_DESC' => 'Εάν δεν έχετε καθορίσει φορολογική τιμή για ένα εύρος, θα χρησιμοποιηθεί η προεπιλεγμένη τιμή',
	'LBL_SELECT_SIMPLE_TAXES' => 'Επιλέξτε Απλούς Φόρους',
	'LBL_REGION_NAME' => 'Όνομα Εύρους',
	'LBL_ENTER_REGION_NAME' => 'Εισαγωγή Ονόματος εύρους',
	'LBL_EDIT_REGION' => 'Επεξεργασία Εύρους',
	'LBL_TAX_REGION_EXIST' => 'Το όνομα εύρους υπάρχει ήδη',
	'LBL_EDIT_CHARGE' => 'Επεξεργασία Χρέωσης',
	'LBL_CHARGE_FORMAT' => 'Μορφή Χρέωσης',
	'LBL_FLAT' => 'κατ αποκοπή',
	'LBL_DIRECT_PRICE' => 'Άμεση τιμή',
	'LBL_PERCENT' => 'Ποσοστό',
	'LBL_CHARGE_TYPE' => 'Τύπος χρέωσης',
	'LBL_CHARGE_VALUE' => 'Τιμή Χρέωσης',
	'LBL_ENTER_CHARGE_NAME' => 'Εισαγωγή Ονόματος Χρέωσης',
	'LBL_ENTER_CHARGE_VALUE' => 'Εισαγωγή Τιμής Ονόματος',
	'LBL_REGIONS' => 'Εύρος',
	'LBL_ENABLE_TAXES_FOR_CHARGE' => 'Ενεργοποιήστε εάν η χρέωση είναι φορολογητέα',
	'LBL_SELECT_TAX' => 'Επιλογή Φόρου',
	'LBL_SELECT_TAXES' => 'Επιλογές Φόρων',
	'LBL_SELECT_REGIONS' => 'Επιλογή Πεδίων',
	'LBL_SELECT_TAX_DESC' => 'Εμφανίζονται μόνο οι φόροι επί των χρεώσεων',
	'LBL_CHARGE_STORE_DISC' => 'Η τιμή χρέωσης αποθηκεύεται πάντα σε βασικό συνάλλαγμα',
	'LBL_DEDUCTED_TAX_DISC' => 'Οι εκπιπτόμενοι φόροι υπολογίζονται επί των συνολικών στοιχείων και αφαιρούνται από το Σύνολο',

	//Terms & conditions
	'LBL_TERMS_AND_CONDITIONS' => 'Όροι και Προϋποθέσεις',
	'LBL_SPECIFY_TERMS_AND_CONDITIONS' => 'Προσδιορίστε Όρους και Προϋποθέσεις εδώ',
	//Announcements
	'LBL_ANNOUNCEMENTS' => 'Ανακοινώσεις',
	'LBL_ENTER_ANNOUNCEMENT_HERE' => 'Εισαγωγή Ανακοίνωσης Εδώ',
	'LBL_ANNOUNCEMENT_DESC' => 'Αλλάξτε το κείμενο που εμφανίζεται στην ανακοίνωση στην κορυφή κάθε σελίδας',

	//Outgoing Server
	'LBL_RESET_TO_DEFAULT' => 'Επαναφορά στις Προεπιλογές',
	'LBL_SERVER_NAME' => 'Όνομα Διακομιστή',
	'LBL_USER_NAME' => 'Όνομα Χρήστη',
	'LBL_PASSWORD' => 'Συνθηματικό',
	'LBL_FROM_EMAIL' => 'Από Email',
	'LBL_SERVER_TYPE' => 'Τύπος Διακομιστή',
	'LBL_OTHERS' => 'Άλλοι',
	'LBL_GMAIL' => 'Gmail',
	'LBL_HOTMAIL' => 'Hotmail',
	'LBL_YAHOO' => 'Yahoo',
	'LBL_OFFICE365' => 'Office365',
	'LBL_VTIGER' => 'Vtiger',
	'LBL_REQUIRES_AUTHENTICATION' => 'Απαιτείται Πιστοποίηση',
	'LBL_OUTGOING_SERVER' => 'Διακομιστής Εξερχομένων',
	'LBL_OUTGOING_SERVER_DESC' => 'Διαμορφώστε τις λεπτομέρειες του Διακομιστής Εξερχομένων',
	
	'LBL_DEFAULT'=>'Από προεπιλογή, οι ρυθμίσεις του λογαριασμού SMTP για το διακομιστή εξερχόμενων έχουν ρυθμιστεί στον od1.vtiger.com mail server. Για να αποφύγετε προβλήματα φιλτραρίσματος των εξερχόμενων email από τα φίλτρα spam στον παραλήπτη διακομιστή αλληλογραφίας του ISP σας, σας προτείνουμε να εφαρμοστούν ένα από τα ακόλουθα.',
	'LBL_OPTIONS1'=>'Αποστολή emails από τον δικό σας mail server<br>
					- Εισαγωγή στοιχείων λογαριασμού SMTP (Όνομα Διακομιστή, Όνομα Χρήστη, Συνθηματικό) για τον ίδιο λογαριασμό όπως εισήχθη στο ΑΠΟ email.',
	'LBL_OPTIONS2'=>"Προσθήκη του vtiger.com ως πιστοποιημένου αποστολέα για το δικό σας domain. <b>(your_company.com)</b> όταν χρησιμοποιείτε το <b> Από Email (πχ : support@your_company.com)</b>.<br>
						-Για να διασφαλίσετε ότι τα μηνύματά σας δεν απορρίπτονται από τον διακομιστή του παραλήπτη ως SPAM, 
						η παρακάτω εγγραφή TXT θα πρέπει να προστεθεί στο αρχείο DNS του τομέα σας",
	'LBL_MAIL_SERVER_SMTP'=>'Ρυθμίσεις διακομιστή (SMTP)',
	'LBL_OUTGOING_SERVER_FROM_FIELD'=>'ΣΗΜΕΙΩΣΗ: Αν το πεδίο "Από Email" είναι κενό, τότε θα ληφθεί η διεύθυνση ηλεκτρονικού ταχυδρομείου χρήστη.',
	'LBL_TESTMAILSTATUS'=>'Κατάστασης Δοκιμής Mail : ',
	'LBL_MAILSENDERROR'=>'Δεν ήταν δυνατή η αποστολή email στον χρήστη admin. Ελέγξτε τις ρυθμίσεις admin στο emailid / Server',
	
	//Configuration Editor
	'LBL_CONFIG_EDITOR' => 'Επεξεργαστής Ρυθμίσεων',
	'LBL_CONFIG_DESCRIPTION' => 'Επεξεργασία λεπτομερειών Ρυθμίσεων του vtiger CRM',
	'LBL_CONFIG_FILE' => 'config.inc.php',
	'LBL_MB' => 'MB',

	//Config Editor Fields
	'LBL_MINI_CALENDAR_DISPLAY' => 'Εμφάνιση μικρού Ημερολογίου',
	'LBL_WORLD_CLOCK_DISPLAY' => 'Εμφάνιση Παγκόσμιου Ρολογιού',
	'LBL_CALCULATOR_DISPLAY' => 'Εμφάνιση Αριθμομηχανής',
	'LBL_USE_RTE' => 'Χρήση RTE',
	'LBL_HELPDESK_SUPPORT_EMAILID' => 'Email του Τμήματος Υποστήριξης',
	'LBL_HELPDESK_SUPPORT_NAME' => 'Όνομα Τμήματος Υποστήριξης',
	'LBL_MAX_UPLOAD_SIZE' => 'Μέγιστο Μέγεθος Μεταφόρτωσης (Max %sMB)',
	'LBL_MAX_HISTORY_VIEWED' => 'Μέγιστη Προβολή Ιστορικού',
	'LBL_DEFAULT_MODULE' => 'Προεπιλεγμένη Ενότητα',
	'LBL_MAX_TEXT_LENGTH_IN_LISTVIEW' => 'Μέγιστο μήκος του κειμένου στην προβολή λίστας',
	'LBL_MAX_ENTRIES_PER_PAGE_IN_LISTVIEW' => 'Μέγιστες εγγραφές ανά σελίδα στην προβολή λίστας',
	'LBL_EMAIL_TRACKING' => 'Enable email tracking',
	'LBL_INVALID_EMAILID' => 'Μη Έγκυρο Email',
	'LBL_INVALID_SUPPORT_NAME' => 'Μη Έγκυρο Όνομα',
	'LBL_INVALID_MODULE' => 'Μη Έγκυρη Ενότητα',
	'LBL_INVALID_NUMBER' => 'Μη Έγκυρος Αριθμός',
	'LBL_FIELDS_INFO_IS_EMPTY' => 'Οι πληροφορίες Πεδίων είναι κενές',

	//CustomRecordNumbering
	'LBL_SUCCESSFULLY_UPDATED' => 'Επιτυχής ενημέρωση',
	'LBL_CUSTOMIZE_RECORD_NUMBERING' => 'Αρίθμηση Ενοτήτων',
	'LBL_MODULE_ENTITY_NUMBER_CUSTOMIZATION' => 'Προσαρμογή Αρίθμησης Οντότητας Ενοτήτων',
	'LBL_UPDATE_MISSING_RECORD_SEQUENCE' => 'Ενημέρωση Ελλιπής Ακολουθίας Εγγραφών',
	'LBL_USE_PREFIX' => 'Χρήση Προθέματος',
	'LBL_PREFIX_IN_USE' => 'Το Πρόθεμα χρησιμοποιείται ήδη',
	'LBL_START_SEQUENCE' => 'Έναρξη Ακολουθίας',

	//Company Details
	'organizationname' => 'Όνομα Εταιρείας',
	'logoname' => 'Εταιρικό Λογότυπο',
	'address' => 'Διεύθυνση',
	'city' => 'Πόλη',
	'state' => 'Νομός',
	'code'  => 'Τ.Κ',
	'country' => 'Χώρα',
	'phone' => 'Τηλέφωνο',
	'fax' => 'Φαξ',
	'website' => 'Ιστοσελίδα',
	'vatid' => 'Αναγνωριστικό ΦΠΑ',
	'facebook' => 'Facebook',
	'twitter' => 'Twitter',
	'linkedin' => 'LinkedIn',
	'LBL_IMAGE_CORRUPTED' => 'Έχει ανιχνευθεί Ιός ή Μεταμορφώθηκε κατεστραμμένη εικόνα',
	'LBL_LOGO_RECOMMENDED_MESSAGE' => 'Επιτρεπόμενο μέγεθος 150X40 pixels( .jpeg , .jpg , .png , .gif , .pjpeg , .x-png ).',
	'LBL_COMPANY_INFORMATION' => 'Στοιχεία Επιχείρησης',
	'LBL_UPDATE' => 'Ενημέρωση',
	'LBL_UPDATE_LOGO' => 'Ενημέρωση Λογότυπου',
	'LBL_COMPANY_LOGO' => 'Λογότυπο Εταιρείας',
	'LBL_NO_LOGO_EDIT_AND_UPLOAD' => 'Δεν υπάρχει εικόνα, επεξεργασία και μεταφόρτωση εικόνας',
	'LBL_EDIT_COMPANY_DETAILS_MESSAGE' => 'Για να επεξεργαστείτε τα στοιχεία της επιχείρησης, κάντε κλικ στο εικονίδιο Ρυθμίσεις> Προσθήκη / Διαγραφή χρηστών> Εταιρεία ',
    
    'LBL_ACTIVE' => 'Ενεργό',
    'LBL_INACTIVE' => 'Ανενεργό',
    
    //show last scan in workflows and mailconverter
    'LBL_DISABLED' => 'Απενεργοποιημένο',
    'LBL_RUNNING' => 'Εκτελείται',
    'LBL_LAST_SCAN_TIMED_OUT' => 'Λήξη χρονικού περιθωρίου της τελευταίας σάρωσης',
    'LBL_LAST_SCAN_AT' => 'Τελευταία σάρωση στις ',
    'LBL_TIME_TAKEN' => ' διήρκεσε ',
    'LBL_SHORT_SECONDS' => 'δευτ',
	
	//Email Templates
	'EmailTemplate' => 'Πρότυπο Email',
	'LBL_TEMPLATE_NAME' => 'Όνομα Προτύπου',
	'LBL_DESCRIPTION' => 'Περιγραφή',
	'LBL_SUBJECT' => 'Θέμα',
	
	//User Login History
	'LoginHistory' => 'Ιστορικό εισόδου Χρήστη',
	'LBL_LOGIN_HISTORY_DETAILS' => 'Ιστορικό εισόδου',
	'LBL_LOGIN_HISTORY_DESCRIPTION' => 'Λεπτομέρειες Ιστορικού εισόδου',
	'LBL_USER_NAME'=> 'Όνομα Χρήστη',
	'LBL_USER_IP_ADDRESS'=> 'Διεύθυνση IP του Χρήστη', 
	'LBL_LOGIN_TIME' => 'Ώρα Εισόδου',
	'LBL_LOGGED_OUT_TIME' => '΄Ώρα Εξόδου', 
	'LBL_STATUS' => 'Κατάσταση',

    // Leads and Potentials Mapping 
    'LBL_SAVED_SUCCESSFULLY' => 'Αποθηκεύτηκε επιτυχώς',
	'LBL_DELETED_SUCCESSFULLY' => 'Διαγράφηκε επιτυχώς',
	'LBL_INVALID_MAPPING' => 'Μη έγκυρη Διασύνδεση',
    'LBL_FIELD_LABEL' => 'Όνομα Πεδίου',
	'LBL_FIELD_TYPE' => 'Τύπος Πεδίου',
	'LBL_MAPPING_WITH_OTHER_MODULES' => 'Διασύνδεση με άλλες ενότητες',
    'LBL_ADD_MAPPING' => 'Προσθήκη Διασύνδεσης',
	'LBL_NONE' => 'Κανένα',
    
    //Field Type Translation
	'phone' => 'Τηλέφωνο',
	'picklist' => 'Λίστα επιλογών',
	'email' => 'Email',
	'text' => 'Κείμενο',
	'currency' => 'Συνάλλαγμα',
	'multiSelectCombo' => 'Σύνθετου πλαίσιο πολλαπλών επιλογών',
	'time' => 'Χρόνος',
	'textArea' => 'Περιοχή κειμένου',
	'url' => 'Url',
	'string' => 'Συμβολοσειρά',
	'checkBox' => 'Πλαίσιο ελέγχου',
	'date' => 'Ημερομηνία',
	'decimal' => 'Δεκαδικός',
	'percent' => 'Τοις εκατό',
	'skype' => 'Skype',
	'image' => 'Εικόνα',
	'LBL_DEFAULT_TAX_MODE' => 'Προεπιλεγμένη φορολογική λειτουργία',
	'LBL_RELATIONSHIPS' => 'Συσχέτιση',
    
    'LBL_MODULE_BUILDER_DESCRIPTION' => 'Δημιουργία νέας ενότητας (module)',
    
	'LBL_EXTENSION_STORE' => 'Extension Store',
    'LBL_GATEWAY_CONFIGURATION' => 'Διαμόρφωση της πύλης πληρωμών',
    'MAIN_PRODUCT_WHITELABEL' => 'CRM white labeling',
    'LBL_WHITE_LABELING_INFO' => 'Η ενεργοποίηση αυτής, θα καταργήσει το εικονίδιο feedback, συνδέσμους βίντεο, τα βίντεο νέων δυνατοτήτων και το υποσέλιδο από το CRM.',
    'LBL_WHITE_LABELING_INFO_MSG' => 'Με την ενεργοποίηση αυτή θα καταργηθεί το κουμπί βοήθειας και το υποσέλιδο από το CRM.',
	/*Vtiger7 Language Strings*/
    'LBL_USER_MANAGEMENT' => 'Διαχείριση χρηστών',
    'LBL_MODULE_MANAGEMENT' => 'Διαχείριση ενοτήτων',
    'LBL_AUTOMATION' => 'Αυτοματισμοί',
    'LBL_CONFIGURATION' => 'Διαμόρφωση',
    'LBL_MARKETING_SALES' => 'Marketing & Πωλήσεις',
    'LBL_INVOICES' => 'Τιμολόγια',
    'LBL_SUPPORT' => 'Υποστήριξη',
    'LBL_TEMPLATES' => 'Πρότυπα',
    'LBL_MODULE_CUSTOMIZATION' => 'Διάταξη & Πεδία Ενότητας',
    'LBL_TAX_MANAGEMENT' => 'Φορολογική διαχείριση',
    'LBL_TERMS_AND_CONDITIONS' => 'Όροι και Προϋποθέσεις',
    'LBL_GATEWAY_CONFIGURATION' => 'Συνδρομές',
    'LBL_LEAD_MAPPING' => 'Διασύνδεση δεδομένων μετατροπής Δυνητικών',
    'LBL_OPPORTUNITY_MAPPING' => 'Διασύνδεση Ευκαιρίας σε Έργο',
    'LBL_PICKLIST_DEPENDENCY' => 'Εξαρτήσεις Λίστας Επιλογών',
    'LBL_MY_TAGS' => 'Οι ετικέτες μου',
	'LBL_ADD_MODULE' => 'Προσθήκη Ενότητας',
    'LBL_SMART_NOTIFICATIONS' => 'Έξυπνες ειδοποιήσεις',
    'LBL_FORECAST_SETTINGS' => 'Ρυθμίσεις Προβλέψεων',
    'LBL_SEARCH_FOR_SETTINGS' => 'Ρυθμίσεις αναζήτησης',
    'LBL_GOOGLE' => 'Google',
    'LBL_QUICKBOOKS' => 'QuickBooks',
    'LBL_XERO' => 'Xero',
    'LBL_TALLY' => 'Tally',
    'LBL_SHOPPINGCART' => 'ShoppingCart',
	'LBL_PHONE_CONFIGURATION' => 'Διαμόρφωση τηλεφώνου',
);

$jsLanguageStrings = array(
	'JS_PLEASE_SELECT_ATLEAST_ONE_MEMBER_FOR_A_GROUP' => 'Παρακαλούμε επιλέξτε τουλάχιστον ένα μέλος μιας ομάδας',
	'JS_GROUP_DELETED_SUCCESSFULLY' => 'Η Ομάδα Διαγράφηκε Επιτυχώς',
	'JS_TAX_SAVED_SUCCESSFULLY' => 'Ο Φόρος Αποθηκεύτηκε Επιτυχώς',
	'JS_TAX_DISABLED' => 'Ο φόρος απενεργοποιήθηκε',
	'JS_TAX_ENABLED' => 'Ο φόρος ενεργοποιήθηκε',
	'JS_SELECT_SIMPLE_TAXES' => 'Επιλέξτε Απλούς Φόρους',
	'JS_TAX_REGION_SAVED_SUCCESSFULLY' => 'Φορολογικό εύρος αποθηκεύτηκε επιτυχώς',
	'JS_TAX_REGION_DELETED_SUCCESSFULLY' => 'Φορολογικό εύρος Διαγράφηκε επιτυχώς',
	'JS_INVENTORY_CHARGE_SAVED_SUCCESSFULLY' => 'Η χρέωση αποθέματος αποθηκεύτηκε επιτυχώς',
	'JS_INVENTORY_CHARGE_DELETED_SUCCESSFULLY' => 'Η χρέωση αποθέματος διαγράφηκε επιτυχώς',
	'JS_DELETE_CHARGE_DESC' => 'Η διαγραφή αυτής της χρέωσης θα επηρεάσει όλες τις εγγραφές αποθήκης με αυτήν την υπάρχουσα χρέωση. Θέλετε να συνεχίσετε;',
	'JS_DELETE_REGION_DESC' => 'Η διαγραφή αυτού του εύρους θα επηρεάσει όλους τους φόρους αποθήκης με αυτή την υπάρχουσα περιοχή εύρους. Θέλετε να συνεχίσετε;',
	'JS_SELECT_REGIONS' => 'Επιλογή Εύρους',
	'JS_DELETE' => 'Διαγραφή',
	'JS_EDIT' => 'Επεξεργασία',
	'JS_ANNOUNCEMENT_SAVED' => 'Η Ανακοίνωση Αποθηκεύτηκε',
	'JS_CONFIRM_DEFAULT_SETTINGS' => 'Είστε σίγουροι ότι θέλετε να αλλάξετε τα στοιχεία του διακομιστή με τις προεπιλεγμένες τιμές διακομιστή',
	'JS_PLEASE_ENTER_NUMBER_IN_RANGE_1TO5' => 'Παρακαλώ εισάγετε τιμή μεταξύ 1-%sMB',
	'JS_PLEASE_ENTER_NUMBER_IN_RANGE_1TO100' => 'Παρακαλώ εισάγετε τιμή μεταξύ 1-100',
	'JS_RECORD_NUMBERING_SAVED_SUCCESSFULLY_FOR' => 'Αρίθμηση Εγγραφών αποθηκεύτηκε με επιτυχία για ',
	'JS_RECORD_NUMBERING_UPDATED_SUCCESSFULLY_FOR' => 'Αρίθμηση Εγγραφών ενημερώθηκε με επιτυχία για',
	'JS_SEQUENCE_NUMBER_MESSAGE' => 'Ο Αριθμός Ακολουθίας θα πρέπει να είναι μεγαλύτερο η ίσο με',
	'LBL_WRONG_IMAGE_TYPE' => 'Μη υποστηριζόμενος Τύπος Εικόνας',
	'LBL_MAXIMUM_SIZE_EXCEEDS' => 'Μπορείτε να μεταφορτώσετε το μέγιστο μέγεθος του 1MB μόνο',
	'LBL_NO_LOGO_SELECTED' => 'Κανένα Λογότυπο δεν έχει Επιλεχτεί',
	'JS_CONFIGURATION_DETAILS_SAVED' => 'Αποθηκεύτηκαν οι Λεπτομέρειες διαμόρφωσης',
	'JS_TERMS_AND_CONDITIONS_SAVED' => 'Οι Όροι Και Προϋποθέσεις Αποθηκεύτηκαν',
	'JS_DEFAULT_TAX_MODE_SET_AS' => 'Η προεπιλεγμένη φορολογική λειτουργία έχει οριστεί ως ',
    'JS_INVALID_URL' => 'Μη έγκυρο URL',
    'JS_LBL_TAX_REGION_EXIST' => 'Όνομα εύρους υπάρχει ήδη',
    'JS_LOGO_IMAGE_DIMENSIONS_WRONG' => 'Οι διαστάσεις εικόνας του λογότυπου δεν αντιστοιχούν στην επιτρεπόμενη διάσταση. Κάντε αλλαγή μεγέθους στην εικόνα και προσπαθήστε ξανά.',
);
