<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	//Basic Field Names
	'LBL_NEW' => 'Νέο',
	'LBL_WORKFLOW' => 'Ροή ΔιΔιεργασιών',
	'LBL_CREATING_WORKFLOW' => 'Δημιουργία Ροής ΔιΔιεργασιών',
	'LBL_EDITING_WORKFLOW' => 'Επεξεργασία ροής ΔιΔιεργασιών',
	'LBL_NEXT' => 'Επόμενο',

	//Edit view
	'LBL_STEP_1' => 'Βήμα 1',
	'LBL_ENTER_BASIC_DETAILS_OF_THE_WORKFLOW' => 'Εισάγετε βασικά στοιχεία της ροής Διεργασιών',
	'LBL_SPECIFY_WHEN_TO_EXECUTE' => 'Καθορίστε πότε να εκτελεστεί αυτή η ροή Διεργασιών',
	'ON_FIRST_SAVE' => 'Μόνο κατά την πρώτη αποθήκευση',
	'ONCE' => 'Μέχρι την πρώτη φορά που η συνθήκη θα είναι αληθής',
	'ON_EVERY_SAVE' => 'Κάθε φορά που η εγγραφή αποθηκεύεται',
	'ON_MODIFY' => 'Κάθε φορά που η εγγραφή τροποποιείται',
	'ON_SCHEDULE' => 'Προγραμματισμός',
	'MANUAL' => 'Σύστημα',
	'SCHEDULE_WORKFLOW' => 'Προγραμματισμός Ροής Διεργασιών',
	'ADD_CONDITIONS' => 'Προσθήκη Συνθηκών',
	'ADD_TASKS' => 'Προσθήκη Ενεργειών',

	//Step2 edit view
	'LBL_EXPRESSION' => 'Έκφραση',
	'LBL_FIELD_NAME' => 'Πεδίο',
	'LBL_SET_VALUE' => 'Ορισμός Τιμής',
	'LBL_USE_FIELD' => 'Πεδίο Χρήσης',
	'LBL_USE_FUNCTION' => 'Συνάρτηση Χρήσης',
	'LBL_RAW_TEXT' => 'Ακατέργαστο κείμενο',
	'LBL_ENABLE_TO_CREATE_FILTERS' => 'Ενεργοποιήστε για να δημιουργήσετε φίλτρα',
	'LBL_CREATED_IN_OLD_LOOK_CANNOT_BE_EDITED' => 'Αυτή η ροή Διεργασιών δημιουργήθηκε σε παλαιότερη εμφάνιση. Όροι δημιουργήθηκαν σε παλαιότερες ματιά δεν μπορεί να επεξεργαστεί. Μπορείτε να επιλέξετε να αναδημιουργήσει τις προϋποθέσεις, ή χρησιμοποιήστε τις υπάρχουσες συνθήκες, χωρίς να αλλάζει τους.',
	'LBL_USE_EXISTING_CONDITIONS' => 'Χρησιμοποιήστε τις υπάρχουσες συνθήκες',
	'LBL_RECREATE_CONDITIONS' => 'Αναδημιουργία Συνθηκών',
	'LBL_SAVE_AND_CONTINUE' => 'Αποθήκευση & Συνέχεια',

	//Step3 edit view
	'LBL_ACTIVE' => 'Ενεργό',
	'LBL_TASK_TYPE' => 'Τύπος Ενέργειας',
	'LBL_TASK_TITLE' => 'Τίτλος Ενέργειας',
	'LBL_ADD_TASKS_FOR_WORKFLOW' => 'Προσθήκη ενέργειας για ροές Διεργασιών',
	'LBL_EXECUTE_TASK' => 'Εκτέλεση ενέργειας',
	'LBL_SELECT_OPTIONS' => 'Διαλέξτε Επιλογές',
	'LBL_ADD_FIELD' => 'Προσθήκη πεδίου',
	'LBL_ADD_TIME' => 'Προσθήκη Ώρας',
	'LBL_TITLE' => 'Τίτλος',
	'LBL_PRIORITY' => 'Προτεραιότητα',
	'LBL_ASSIGNED_TO' => 'Σχετικό με',
	'LBL_TIME' => 'Χρόνος',
	'LBL_DUE_DATE' => 'Έως τις',
	'LBL_THE_SAME_VALUE_IS_USED_FOR_START_DATE' => 'Η ίδια τιμή χρησιμοποιείται για την Ημερομηνία Έναρξης',
	'LBL_EVENT_NAME' => 'Όνομα συμβάντος',
	'LBL_TYPE' => 'Τύπος',
	'LBL_METHOD_NAME' => 'Όνομα Μεθόδου',
	'LBL_RECEPIENTS' => 'Παραλήπτες',
	'LBL_ADD_FIELDS' => 'Προσθήκη πεδίων',
	'LBL_SMS_TEXT' => 'SMS',
	'LBL_SET_FIELD_VALUES' => 'Ορισμός τιμών Πεδίου',
	'LBL_ADD_FIELD' => 'Προσθήκη πεδίου',
	'LBL_IN_ACTIVE' => 'Αδρανής',
	'LBL_SEND_NOTIFICATION' => 'Αποστολή Ειδοποίησης',
	'LBL_START_TIME' => 'Ώρα Έναρξης',
	'LBL_START_DATE' => 'Ημερομηνία έναρξης',
	'LBL_END_TIME' => 'Ώρα λήξης',
	'LBL_END_DATE' => 'Ημερομηνία Λήξης',
	'LBL_ENABLE_REPEAT' => 'Ενεργοποίηση Επανάληψης',
	'LBL_NO_METHOD_IS_AVAILABLE_FOR_THIS_MODULE' => 'Καμία μέθοδος δεν είναι διαθέσιμη για αυτή την ενότητα',
	
	'LBL_NO_TASKS_ADDED' => 'Καμία Ενέργεια',
	'LBL_CANNOT_DELETE_DEFAULT_WORKFLOW' => 'Δεν μπορείτε να διαγράψετε προεπιλεγμένη ροή διεργασίας',
	'LBL_MODULES_TO_CREATE_RECORD' => 'Ενότητα που δημιουργεί εγγραφή',
	'LBL_EXAMPLE_EXPRESSION' => 'Έκφραση',
	'LBL_EXAMPLE_RAWTEXT' => 'Ακατέργαστο Κείμενο',
	'LBL_VTIGER' => 'Vtiger',
	'LBL_EXAMPLE_FIELD_NAME' => 'Πεδίο',
	'LBL_NOTIFY_OWNER' => 'ειδοποίηση_κατόχου',
	'LBL_ANNUAL_REVENUE' => 'ετήσια_έσοδα',
	'LBL_EXPRESSION_EXAMPLE2' => "if mailingcountry == 'India' then concat(firstname,' ',lastname) else concat(lastname,' ',firstname) end",
	'LBL_FROM' => 'Από',
	'LBL_RUN_WORKFLOW' => 'Εκτέλεση Ροής Διεργασιών',
	'LBL_AT_TIME' => 'Σε χρόνο',
	'LBL_HOURLY' => 'Ωριαίος',
	'Optional' => 'Προαιρετικός',
	'ENTER_FROM_EMAIL_ADDRESS'=> 'Εισαγάγετε - Από - email',
	'LBL_ADD_TASK' => 'Προσθέστε ενέργεια',
    'Portal Pdf Url' =>'Portal Pdf Url',

	'LBL_DAILY' => 'Καθημερινά',
	'LBL_WEEKLY' => 'Εβδομαδιαίος',
	'LBL_ON_THESE_DAYS' => 'Σε αυτές τις μέρες',
	'LBL_MONTHLY_BY_DATE' => 'Μηνιαία με ημερομηνία',
	'LBL_MONTHLY_BY_WEEKDAY' => 'Μηνιαία από την εβδομάδα',
	'LBL_YEARLY' => 'Ετήσια',
	'LBL_SPECIFIC_DATE' => 'Σε συγκεκριμένη ημερομηνία',
	'LBL_CHOOSE_DATE' => 'Επιλέξτε Ημερομηνία',
	'LBL_SELECT_MONTH_AND_DAY' => 'Επιλέξτε Μήνα και Ημερομηνία',
	'LBL_SELECTED_DATES' => 'Επιλεγμένες ημερομηνίες',
	'LBL_EXCEEDING_MAXIMUM_LIMIT' => 'Υπέρβαση ανώτατου ορίου',
	'LBL_NEXT_TRIGGER_TIME' => 'Επόμενος χρόνος ενεργοποίησης',
    'LBL_ADD_TEMPLATE' => 'Προσθήκη πρότυπου',
    'LBL_LINEITEM_BLOCK_GROUP' => 'Στοιχεία γραμμής πλαισίου για ομάδα φόρου',
    'LBL_LINEITEM_BLOCK_INDIVIDUAL' => 'Στοιχεία γραμμής πλαισίου για ατομικός φόρο',
	'LBL_MESSAGE' => 'Μήνυμα',
    'LBL_ADD_PDF' => 'Προσθήκη PDF',
	
	//Translation for module
	'Calendar' => 'Εργασία',
	'Send Mail' => 'Αποστολή Mail',
	'Invoke Custom Function' => 'Invoke Custom Function',
	'Create Todo' => 'Δημιουργία Εργασίας',
	'Create Event' => 'Δημιουργία Συμβάντος',
	'Update Fields' => 'Ενημέρωση Πεδίων',
	'Create Entity' => 'Δημιουργία Εγγραφής',
	'SMS Task' => 'Εργασία SMS',
	'Mobile Push Notification' => 'Mobile Push Notification',
    
    // v7 translations
    'LBL_WORKFLOW_NAME' => 'Όνομα ροής εργασίας',
    'LBL_TARGET_MODULE' => 'Ενότητα στόχου',
    'LBL_WORKFLOW_TRIGGER' => 'Στοιχείο ενεργοποίησης Ροής εργασίας',
    'LBL_TRIGGER_WORKFLOW_ON' => 'Ενεργοποίηση ροής εργασίας στις',
    'LBL_RECORD_CREATION' => 'Δημιουργία Εγγραφής',
    'LBL_RECORD_UPDATE' => 'Ενημέρωση Εγγραφής',
    'LBL_TIME_INTERVAL' => 'Χρονικό διάστημα',
    'LBL_RECURRENCE' => 'Επανάληψη',
    'LBL_FIRST_TIME_CONDITION_MET' => 'Την πρώτη φορά που η συνθήκη θα είναι αληθής',
    'LBL_EVERY_TIME_CONDITION_MET' => 'Κάθε φορά που η συνθήκη θα είναι αληθής',
    'LBL_WORKFLOW_CONDITION' => 'Συνθήκη Ροής Διεργασιών',
    'LBL_WORKFLOW_ACTIONS' => 'Ενέργειες Ροής Διεργασιών',
    'LBL_DELAY_ACTION' => 'Ενέργεια Καθυστέρησης',
    'LBL_FREQUENCY' => 'Συχνότητα',
    'LBL_SELECT_FIELDS' => 'Επιλέξτε πεδία',
    'LBL_INCLUDES_CREATION' => 'Περιλαμβάνει τη Δημιουργία',
    'LBL_ACTION_FOR_WORKFLOW' => 'Ενέργεια για τη ροή Διεργασιών',
    'LBL_WORKFLOW_SEARCH' => 'Αναζήτηση βάσει ονόματος',
	'LBL_ACTION_TYPE' => 'Τύπος ενέργειας (Active Count)',
	'LBL_VTEmailTask' => 'Email',
    'LBL_VTEntityMethodTask' => 'Προσαρμοσμένη λειτουργία',
    'LBL_VTCreateTodoTask' => 'Εργασία',
    'LBL_VTCreateEventTask' => 'Συμβάν',
    'LBL_VTUpdateFieldsTask' => 'Ενημέρωση Πεδίων',
    'LBL_VTSMSTask' => 'SMS', 
    'LBL_VTPushNotificationTask' => 'Mobile Notification',
    'LBL_VTCreateEntityTask' => 'Δημιουργία εγγραφών',
	'LBL_MAX_SCHEDULED_WORKFLOWS_EXCEEDED' => 'Έχει ξεπεραστεί ο μέγιστος αριθμός (%s) προγραμματισμένων ροών εργασίας',
);

$jsLanguageStrings = array(
	'JS_STATUS_CHANGED_SUCCESSFULLY' => 'Η Κατάσταση άλλαξε με επιτυχία',
	'JS_TASK_DELETED_SUCCESSFULLY' => 'Η ενέργεια διαγράφηκε με επιτυχία',
	'JS_SAME_FIELDS_SELECTED_MORE_THAN_ONCE' => 'Τα ίδια πεδία έχουν επιλεγεί περισσότερες από μία φορές',
	'JS_WORKFLOW_SAVED_SUCCESSFULLY' => 'Η Ροή Διεργασίας αποθηκεύτηκε επιτυχώς',
    'JS_CHECK_START_AND_END_DATE'=>'Η ημερομηνία και η ώρα λήξης θα πρέπει να είναι μεγαλύτερες ή ίσες με την Ημερομηνία και ώρα έναρξης',
    'JS_TASK_STATUS_CHANGED' => 'Η κατάσταση της εργασίας άλλαξε επιτυχώς.',
    'JS_WORKFLOWS_STATUS_CHANGED' => 'Η κατάσταση της ροής εργασίας άλλαξε επιτυχώς.',
    'VTEmailTask' => 'Αποστολή Mail',
	'VTEntityMethodTask' => 'Ενεργοποίηση προσαρμοσμένης λειτουργίας',
    'VTCreateTodoTask' => 'Δημιουργία εργασίας',
    'VTCreateEventTask' => 'Δημιουργία συμβάντος',
    'VTUpdateFieldsTask' => 'Ενημέρωση πεδίων',
    'VTSMSTask' => 'Εργασία SMS', 
    'VTPushNotificationTask' => 'Ειδοποιήσεις κινητού τηλεφώνου',
    'VTCreateEntityTask' => 'Δημιουργία Εγγραφών',
    'LBL_EXPRESSION_INVALID' => 'Η έκφραση δεν είναι έγκυρη',
);
